### ISSUE TITLE
[Feature request] Set proxy authentication

### ISSUE THREAD

**Issue by dizzy80** [Kong/unirest-java#103]
Please add the feature to set the authentication credentials for a set proxy to the API.

**Comment by adpande** [comment]
+1 for this.. We really need this functionality. Thanks!

**Comment by subay** [comment]
Proxy authentication would be awesome!

**Comment by freshsid** [comment]
+1

**Comment by beeme1mr** [comment]
+1

**Comment by negste** [comment]
+1

**Comment by odirus** [comment]
+1

**Comment by faisalbasra** [comment]
+1

**Comment by faisalbasra** [comment]
Any chance to reply/implement this ?

**Comment by shashiranjan84** [comment]
@faisalbasra sorry currently we are busy with our other products but feel free to contribute with a PR.

**Comment by fabiangerson** [comment]
+1

**Comment by csvan** [comment]
+1

**Comment by Samuel3** [comment]
+1

**Comment by p4ali** [comment]
+1

**Comment by re1ax** [comment]
+1

**Comment by ventskus-roman** [comment]
+1

**Comment by xlavecat** [comment]
Partial solution provided in https://stackoverflow.com/questions/40864167/how-to-set-credentials-for-unirest-proxy

I think we can add something like that inside class `HttpHost`

**Comment by ventskus-roman** [comment]
@xlavecat thanks, this solutions works fine =) 
But anyway, it would be cool if there was a solution out of box

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
