### ISSUE TITLE
support https

### ISSUE THREAD

**Issue by yc850k** [Kong/unirest-java#106]
please support https

**Comment by zodvik** [comment]
HTTPS is supported. Do you face any specific problem?

**Comment by frankind** [comment]
I found some problems about https as below:
com.mashape.unirest.http.exceptions.UnirestException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by ToroLiu** [comment]
https://github.com/Mashape/unirest-java/issues/70

**Comment by ryber** [comment]
This is an issue with Java not with Unirest specifically
