### ISSUE TITLE
Options.refresh : always start a new SyncIdleConnectionMonitorThread

### ISSUE THREAD

**Issue by gdecad** [Kong/unirest-java#112]
Options.refresh method always create a new SyncIdleConnectionMonitorThread and start it, even if another already exists in Options.SYNC_MONITOR.

It's problematic when we use Unirest.setXXX methods wich call Options.refresh. Because Options.refresh is already called staticaly in Options.

**Comment by d716042** [comment]
if you use Unirest to set objectMapper,  it will have another SyncIdleConnectionMonitorThread  in background without clean up,  

if you use the unirest in tomcat, when the application is undeploy, it will has error message, thread is the terminated.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
