### ISSUE TITLE
unirest  so many AsyncIdleConnectionMonitorThread  running !!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by yudatou123** [Kong/unirest-java#115]
if i use unirest asyn, when many requests,  my server will happen heap outofmermory beacuase  so 

 many AsyncIdleConnectionMonitorThread  running backround! how i use unirest .shutdown() to sovle this prolem！

if my code like this :

Unirest.setTimeouts(0, 0);
        Future<HttpResponse<JsonNode>> future = Unirest.post(url)
                  .header("accept", "application/json")
                  .fields(map)
                  .asJsonAsync(new Callback<JsonNode>() {
                        public void failed(UnirestException e) {
                            try {
                                Unirest.shutdown();
                            } catch (IOException e1) {
                                e1.printStackTrace();
                            }
                        }
                        public void completed(HttpResponse<JsonNode> response) {
                            try {
                                Unirest.shutdown();
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                        }
                        public void cancelled() {
                            try {
                                Unirest.shutdown();
                            } catch (IOException e) {
                            }
                        }

```
                });
```

**Comment by CrazyPython** [comment]
Please don't use so many exclamation marks.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
