### ISSUE TITLE
Unirest.setProxy leaves open file descriptors systemwide [Critical]

### ISSUE THREAD

**Issue by gadLinux** [Kong/unirest-java#119]
The library leaves file descriptors opened in a way there's no way to be handled outside the Unirest core. 

Unirest call is doing an    Options.refresh() that causes it to create a new
ioreactor each time. Without deallocating what it was allocated before:

ioreactor = new DefaultConnectingIOReactor();
            asyncConnectionManager = new PoolingNHttpClientConnectionManager(ioreactor);
            asyncConnectionManager.setMaxTotal((Integer) maxTotal);
            asyncConnectionManager.setDefaultMaxPerRoute((Integer) maxPerRoute);

This causes a new pair of descriptors to be created and not freed. So we can run without files descriptors causing a havoc in the system.

Unirest.shutdown() at least should deallocate them but it does not. 

There's a simple way to test this. 

Create a junit that calls several times to Unirest.setProxy(null); Locate process an run 

watch 'lsof -p <processid> | grep pipe | nl | tail'

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
