### ISSUE TITLE
SSL connections with required client auth throw bad_certificate errors.

### ISSUE THREAD

**Issue by WiteCastle** [Kong/unirest-java#120]
I'm trying to make Unirest calls to internal servers that require client auth but I keep getting bad_certificate errors. I've checked everything about the client certs I'm using and they all check out. I've tried making openssl and curl calls with the same certs and they connect to the server via ssl just fine. I spent days troubleshooting the certificate to no avail. Then I finally decided to try making a simple URLConnection with the same certs and it worked fine. Is there a bug in Unirest that doesn't allow for SSL connections that require client auth?

```
// Set all ssl properties
System.setProperty("javax.net.ssl.keyStore", "/path/to/keystore");
System.setProperty("javax.net.ssl.keyStorePassword", "keystorePass");
System.setProperty("javax.net.ssl.trustStore", "/path/to/trustStore");
System.setProperty("javax.net.ssl.trustStorePassword", "truststorePass");

String uri = "https://server.net/REST/endpoint";
URL url = new URL(uri);

// This works fine
URLConnection con = url.openConnection();

// This does not work and throws bad_certificate errors
HttpResponse<JsonNode> jsonResp = Unirest.get(uri).asJson();
```

**Comment by WiteCastle** [comment]
@shashiranjan84 I'm still getting this error. I've found it happens with a jetty server setup with needClientAuth="true". Are you able to reproduce?

**Comment by ryber** [comment]
I think you would need to set a custom Apache client, but we can look at an easier way to pass in that information. There is a config property for using system settings for the client which might possibly work. 

See this https://stackoverflow.com/questions/21223084/how-do-i-use-an-ssl-client-certificate-with-apache-httpclient

**Comment by ryber** [comment]
Addressed in https://github.com/Kong/unirest-java/commit/1496ba891d022d903bdeb9a4228305f8be223676 https://github.com/Kong/unirest-java/commit/8ef6ad306345b968ef4fee7e0efd763b9c6a75e8

version 2.1.02
