### ISSUE TITLE
404 that returns "Content-Type: text/html" is treated as Json, and explodes

### ISSUE THREAD

**Issue by david-bakin** [Kong/unirest-java#122]
I'm using WireMock which, as it happens, responds (by default) to a 404 not with JSON but with an HTML text. But `HttpResponse`'s constructor (v1.4.7, line 52) ignores that and tries to treat it as JSON (line 95), which of course fails.

I don't know enough about web services to know if 404s from a web service are _required_ to return `application/json`, but it seems plausible that it could happen.  Unirest shouldn't throw a `UnirestException` in that case, but simply return a normal `HttpResponse` with status code 404 and empty body (or some kind of string body).

(My actual web service returns a JSON body for a 404 and I'll find a way to make WireMock do that too, but this seems a flaw regardless that I found it in a unit test context. Thanks.)

**Comment by rnc** [comment]
I can see this as well when attempting to contact a remote service that returns a 404 (and some html). I can replicate it in a unit test as well where the test returns a 404 and some sample html. The problem in my case is that it attempts to process the body (using the ObjectMapper code) - this is after reading the 404 status code.

Can anything be done here?

**Comment by ryber** [comment]
If you call .asJson() (or any of them), it's going to attempt to parse the response as that type. the mime type doesn't really matter. Well written REST API's will respond to a ANY response (including 500's) with a valid parsable response. In any case Unirest 2, doesn't bubble up the parsing error and lets you continue on
