### ISSUE TITLE
Current build crashes

### ISSUE THREAD

**Issue by CrazyPython** [Kong/unirest-java#126]
The java guide tells you to directly clone from the github repo. (http://blog.mashape.com/installing-unirest-java-with-the-maven-assembly-plugin/) I cannot build with maven and Travis CI shows build:error. Is there a stable branch to clone from?

**Comment by amiraliakbari** [comment]
+1 Tests are failing..

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
