### ISSUE TITLE
"restarting" Unirest after shutdown()

### ISSUE THREAD

**Issue by david-bakin** [Kong/unirest-java#127]
Unirest is a singleton, and once you call `shutdown()` you can't use it anymore, due to it shutting down its connection pool (and I suppose other stuff too).  
Unless you call `Options.refresh()`.  That restarts everything just fine.

But its somewhat obscure, also undocumented, that that works.

My suggestion:  Provide a static method on class `Unirest` that is the official correct way to restart it after `shutdown()`.  Because there are valid use cases where you'd like to stop Unirest then restart it sometime later.

(Plus see #112 which should be fixed for this to work right.)

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.

**Comment by Barumugam3** [comment]
Hi Team,
Kong unirest , post method I am calling every request Unirest.reset(). connectionTimeout(600000). enableCookieManagement(false):
Unirest.post("http://127.0.0.1").asJson();.
After continues different api call I'm getting socket exception : socket closed and some time I got illicalstateexception connection pool shutdown

Kindly correct me. If I am doing wrong configuration

**Comment by ryber** [comment]
You shouldn't be resetting the connection over and over again, the configuration on an instance should be fairly static. Any time you call reset() you are going to end up closing the existing pool
