### ISSUE TITLE
ACCEPT_ENCODING_HEADER can't be removed

### ISSUE THREAD

**Issue by m-emelchenkov** [Kong/unirest-java#129]
It's necessary to have an ability to remove ACCEPT_ENCODING_HEADER from request headers. If it is not set then it set its default value which is not acceptable for my use-case, where there should not be this header at all.

**Comment by m-emelchenkov** [comment]
It's necessary to remove the code from unirest-java which adds the ACCEPT_ENCODING_HEADER and also call something like CloseableHttpClient client = HttpClientBuilder.create().disableContentCompression().build(), or this header will be added by Apache framework.

**Comment by shashiranjan84** [comment]
You can set custom HttpClient object with desired configuration in Unirest.setHttpClient public interface.

**Comment by m-emelchenkov** [comment]
Hi! I don't think so because you have the code in `HttpClientHelper.java` in function `prepareRequest()`:
```
		if (!request.getHeaders().containsKey(ACCEPT_ENCODING_HEADER)) {
			request.header(ACCEPT_ENCODING_HEADER, "gzip");
		}
```

It is always called, even for custom HttpClient, isn't it? Please excuse me if I wrong.

**Comment by shashiranjan84** [comment]
Sorry I should have checked. Reopening the issue But expect delayed resolution. Feel free to contribute to project with a PR :)

**Comment by CoryKniefel** [comment]
What the? Really? This is a blocker for me and I've wasted 3 hours on this library.

**Comment by ryber** [comment]
i've exposed a config option to turn off default compression. should get released later today
