### ISSUE TITLE
Unirest reads entire stream to memory even if requested to get InputStream

### ISSUE THREAD

**Issue by amirlanesman** [Kong/unirest-java#130]
Even when requested to return response as an InputStream (.asBinary()) the entire response is read to memory, this makes it impossible to get responses that don't fit into memory.

**Comment by dangxunb** [comment]
Is the above commit fixed this issue?

**Comment by ewencluley** [comment]
I dont think it has been fixed, although I am not 100% sure.  The below code produces an input stream which seems to have buffered the whole response ( 103KB) into a byte array. I am using 1.4.9 which should include this commit.

`HttpResponse<InputStream> is = Unirest.get("http://localhost:8080/endpoint")
                .header("x-api-client", "me")
                .asBinary();`

<img width="329" alt="screen shot 2017-03-14 at 21 25 22" src="https://cloud.githubusercontent.com/assets/971597/23923064/ea39287a-08fc-11e7-9a64-d6715496d5eb.png">

**Comment by ewencluley** [comment]
So while I think the above commit will fix this issue (from looking at the code) the pull request to merge it with the main project is still pending.  It seems like active development has stopped and it is no longer really actively maintained.  I guess you could pull this code and do a build from it but by adding the Maven dependency (I tried for 1.4.9) it still buffers the whole stream

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
