### ISSUE TITLE
Avoid dumping debug response to console when running Junit tests

### ISSUE THREAD

**Issue by myrtleTree33** [Kong/unirest-java#134]
Hello,

I am running Unirest with a Gradle project, in IDEA.

Is there any way I can change the debug runlevel, such that output is not dumped to console?

Thank you!

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
