### ISSUE TITLE
Error~ java.lang.NoClassDefFoundError - Unirest POST response

### ISSUE THREAD

**Issue by Oraclesports** [Kong/unirest-java#135]
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;

import org.json.JSONException;

public class CheckInFacial extends AppCompatActivity {

```
ProgressBar progressBar;
TextView responseView;


@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_check_in_facial);


    progressBar = (ProgressBar) findViewById(R.id.progressBar);
    responseView = (TextView) findViewById(R.id.responseView);

    progressBar.setVisibility(View.VISIBLE);
    responseView.setText("Hi there");

    Button queryButton = (Button) findViewById(R.id.queryButton);
    queryButton.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {

            CheckInFacial cl2 = new CheckInFacial();
            cl2.post1();

        }
    });

}

public void post1(){

    try {
        HttpResponse httpResponse = Unirest.post("post website")
                .header("X-Mashape-Key", the key)
                .header("Content-Type", "application/x-www-form-urlencoded")
                .header("Accept", "application/json")
                .field("attributes", "all")
                .field("detector", "Aggressive")
                .field("limit", 64)
                .field("namespace", "Ben")
                .field("uids", "all")
                .field("urls", "http://www.url.com")
                .asString();

        System.out.println(httpResponse.getBody());

    } catch (UnirestException e) {
        e.printStackTrace();
    }

}
```

}

**Comment by Oraclesports** [comment]
I receive an error during run time. 

FATAL EXCEPTION: main
                                                   Process: benchinpteltd.benapp, PID: 10664
                                                   java.lang.NoClassDefFoundError: com.mashape.unirest.http.HttpMethod
                                                       at com.mashape.unirest.http.Unirest.post(Unirest.java:171)
                                                       at benchinpteltd.benapp.CheckInFacial.post1(CheckInFacial.java:59)
                                                       at benchinpteltd.benapp.CheckInFacial$1.onClick(CheckInFacial.java:43)
                                                       at android.view.View.performClick(View.java:4640)
                                                       at android.view.View$PerformClick.run(View.java:19421)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:146)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5487)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by Oraclesports** [comment]
How do I solve this? thank you!!

**Comment by Oraclesports** [comment]
<dependencies>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.3.6</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpasyncclient</artifactId>
			<version>4.0.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpmime</artifactId>
			<version>4.3.6</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20140107</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.4</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>${jackson.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

**Comment by shashiranjan84** [comment]
I am confused, is it pom for android project? Where is Unirest dependency?

**Comment by Oraclesports** [comment]
Hi Shashiranjan! 
Sorry for the late reply and thanks for getting back.
I am new to this (android development) and I might not have explained it clearly in technical terms. My apology if that is so.

So I actually followed the link (http://blog.mashape.com/using-unirest-java-for-your-android-projects/)
to create a unirest.jar file. I'm having problems as mentioned on my thread title above. 

Regarding your latest reply, that is an extract of the dependencies in pom.xml from the unirest file that I presumed that you might me looking for. Please correct me if you're looking for something else and the location to look for it. 

Thank you so much.

**Comment by Oraclesports** [comment]
@shashiranjan84 Sorry. Do you mind replying me please :(.. Or is it off working hours.

**Comment by shashiranjan84** [comment]
I have done very little development on Android so cant help you here much, it seems like you android project not able to find the Unirest jar. Its very difficult for me to tell what exactly doing wrong without seeing your code. Just try to create new Unirest jar with shaded HttpClient as described in blog and place it right place in android project. Searching further on google always helps

**Comment by Oraclesports** [comment]
Hey @shashiranjan84 . Appreciate your reply! 
Meantime I'll keep working on it! :)

**Comment by Oraclesports** [comment]
Hi @shashiranjan84, Sorry to keep troubling you. But do you have the jar file for android that I can use for?

**Comment by ryber** [comment]
I agree this is a project problem, not something with Unirest specifically, You should make sure all the jars and classes are getting packaged together.
