### ISSUE TITLE
Why on earth are you implementing URLParamEncoder?

### ISSUE THREAD

**Issue by malkusch** [Kong/unirest-java#137]
What is wrong with java's [`URLEncoder`](https://docs.oracle.com/javase/8/docs/api/java/net/URLEncoder.html)? Try to encode 公益 with [your encoder](https://github.com/Mashape/unirest-java/blob/unirest-java-1.4.8/src/main/java/com/mashape/unirest/http/utils/URLParamEncoder.java) and then build an `URI`.

**Comment by froginvasion** [comment]
I agree... I bumped into this issue myself when having `route parameters` that could possibly contain non ASCI characters.

Example:

**diëtist**
was encoded to: di%EBtist
while I expected it to be: di%C3%ABtist

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.

**Comment by malkusch** [comment]
Thanks for the timely fix.
