### ISSUE TITLE
Object oriented interface for Unirest (e.g. new UnirestClient()...)

### ISSUE THREAD

**Issue by c-riddell** [Kong/unirest-java#138]
It would be useful if Unirest could provide an object oriented interface for those who wish to use it e.g. new UnirestClient() or similar. 

Then one could create this object and shut it down, in isolation from other or future Unirest clients. 

Unirest.XX static methods could still exist for those wishing to use them, using a UnirestClient a singleton. The Options class would also need to be pulled out of static-land.

My use case is a long-running application, and does not use Unirest all the time, so it's threads can be shut down in between.

This would also solve #127 

Side-Note: If this feature is implemented, I also think that the async methods should not be able to be accessed via Unirest's static classes - they should use this via an Object, so it is more obvious that they are also responsible to shut the object down. This however would break backward compatibility, so IMHO the feature should be deprecated and removed in a future version.

**Comment by cj74** [comment]
Another thought: If this feature is implemented, it would be useful to have the option to create a Unirest instance using a builder pattern, to configure the various options.

I could work on a PR for this if there is interest. The changes will be moderately extensive.

**Comment by MiErnst** [comment]
I think this is similar to issue [#145](https://github.com/Mashape/unirest-java/issues/145). I would also be interested in such a feature.

**Comment by smijar** [comment]
Yes. please.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
