### ISSUE TITLE
Leaking Two FD and one thread every time Options.refresh() is called

### ISSUE THREAD

**Issue by billyy** [Kong/unirest-java#148]
There are no clean up code for the following so it is leaking a thread and two FD every time it is called.

syncIdleConnectionMonitorThread.start();

asyncConnectionManager = new PoolingNHttpClientConnectionManager(ioreactor);

**Comment by billyy** [comment]
One more thing.  The following thread is never started for async.

setOption(Option.ASYNC_MONITOR, new AsyncIdleConnectionMonitorThread(asyncConnectionManager));

**Comment by MiErnst** [comment]
Hi, I'm also running in this, not with thousands of threads like reported in #140 but at least two. This can be reproduced by simply configuring an custom Object Mapper without invoking any further code
`Unirest.setObjectMapper(new MyObjectMapper());`
The static block inside `Options` with the `refresh()` causes an initial thread creation before `setObjectMapper` invokes refresh again. The previously created thread will not be removed. 

I also think this whole static stuff is a design flaw (see #140) which should be replaced with a more object oriented interface like suggested by #145 and #138.

**Comment by billyy** [comment]
If you only call setProxy() or setTimeout() only once, you won't see this issue as much.   

This is definitely a design issue.   Since both setProxy() and setTimeout() are static, those settings can affect any running Thread calling Unirest.   I believe the correct design would be having a factory method to create a specific Unirest instance per dependency.    With the current design, the only way to avoid race condition is to load Unirest with custom classloader per dependency and encapsulate the custom class loader.

**Comment by sebaswir** [comment]
you see this issue when you call setTimeout/setProxy once. Refresh method is called in static block of Options. So every call of this create new thread.

**Comment by MiErnst** [comment]
Yep, and it leaves thread leak.

**Comment by brandonweeks** [comment]
I'm just going to leave this here: https://github.com/square/okhttp

**Comment by JoshuaCWebDeveloper** [comment]
I believe #112 is also relevant (if it isn't actually describing the same issue as this).

**Comment by lovasoa** [comment]
I ran into this problem too. Very simple class that demonstrates the problem:

```
public class Bug {
    public static void main(String[] args) throws InterruptedException {
        while(true) {
            Unirest.setTimeouts(1000, 1000);
        }
    }
}
```

**Comment by lord-i-will** [comment]
me too......man, thats monster.......
my app crashes for: java.lang.OutOfMemoryError: unable to create new native thread
![image](https://user-images.githubusercontent.com/14847104/42152490-d3e33a8e-7e12-11e8-8ebd-a33c77153955.png)

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.

**Comment by javase** [comment]
> me too......man, thats monster.......
> my app crashes for: java.lang.OutOfMemoryError: unable to create new native thread
> ![image](https://user-images.githubusercontent.com/14847104/42152490-d3e33a8e-7e12-11e8-8ebd-a33c77153955.png)

hi，you can invoke 
`unirestInstance.shutDown();`  
`org.apache.http.pool.AbstractConnPool`source code is 
`public void shutdown() {
    for (final Future<E> future: this.pending) {
        future.cancel(true);
    }
    this.pending.clear();
    for (final E entry: this.available) {
        entry.close();
    }
    this.available.clear();
    for (final E entry: this.leased) {
        entry.close();
    }
    this.leased.clear();
}`
