### ISSUE TITLE
Disable log4j logging for unirest?

### ISSUE THREAD

**Issue by stodge** [Kong/unirest-java#152]
I realise this isn't specifically about Unirest, but how do I configure log4j to prevent debug output from the library?

Thanks

**Comment by jacek99** [comment]
Yes, please, it is VERY noise and flooding the logs during all of our test runs

**Comment by manishpatelUK** [comment]
There are various ways to do this depending on what logging it ends up using. For me it was logback, so I just added this logback.xml:

<configuration debug="false">
    
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%-4relative [%thread] %-5level %logger{35} - %msg %n</pattern>
        </encoder>
    </appender>

    <root level="ERROR">
        
        <appender-ref ref="STDOUT"/>
    </root>
</configuration>

**Comment by lighkLife** [comment]
https://stackoverflow.com/questions/2621701/setting-log-level-of-message-at-runtime-in-slf4j
