### ISSUE TITLE
Unirest throws org.json.JSONException for valid JSON body

### ISSUE THREAD

**Issue by MrGraversen** [Kong/unirest-java#153]
Hello,

I'm trying to HTTP POST with a JSON body. It appeared to work fine until I added some extra data to the payload. 

The entire payload can be found here: https://gist.github.com/MrGraversen/a87e7119d6a0f7904a18ebf085127501

The problem disappears if I remove the last object – the `errorExtraList`. I checked the JSON payload with www.jsonlint.com and it appears to be valid, but Unirest throws this exception either way, and I have no idea why.

The entire stacktrace can be found here: https://gist.github.com/MrGraversen/ea87954e4c9947c773d887305fb937e1

I'm using Google's GSON library to convert the object in question to JSON before adding it to the body of the content. I must stress that it works fine _without_ the `errorExtraList` object, even though there are multiple arrays in the object no matter what.

Snippet of the Java code:

```
Gson gson = new Gson();
String url = "http://" + ... + ":8080/monitor/error/submit";
String json = "";
HttpResponse<JsonNode> errorSubmissionHttpResponse = Unirest.post(url)
    .header("Content-Type", "application/json")
    .body(json = gson.toJson(errorSubmissionDTO))
    .asJson();
```

**Comment by MiErnst** [comment]
Just had a look in the provided stack. 

> com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)

This implies that the response of the server is not valid, not your request object. Please execute the request with Curl and verify that valid JSON is returned.
