### ISSUE TITLE
Incorrectly URL encoding of the path

### ISSUE THREAD

**Issue by travismcchesney** [Kong/unirest-java#158]
When attempting to retrieve `GET /some/url/jack+4@email.com`, the URL is incorrectly URL encoded to be `/some/url/jack%204@email.com`.  In this case, the `+` is interpreted as a space and encoded as such.

While this is perfectly fine in the query parameter section of a URL, it is not correct to do this within the path itself. The plus character in the path is literally a plus, and should not be url encoded.

The offending line can be seen [here](https://github.com/Mashape/unirest-java/blob/3b461599ad021d0a3f14213c0dbb85bab7244f66/src/main/java/com/mashape/unirest/http/HttpClientHelper.java#L172)

For some reason it's decoding the path as if it's an `application/x-www-form-urlencoded` MIME format. From the [`URLDecoder` documentation](http://download.java.net/jdk7/archive/b123/docs/api/java/net/URLDecoder.html), right at the top:

> Utility class for HTML form decoding. This class contains static methods for decoding a String from the application/x-www-form-urlencoded MIME format.

Seems to me that the path should _not_ be treated as being in `application/x-www-form-urlencoded` MIME format.  After that erroneous decoding (which replaces the `+` with a space), it gets encoded with the `%20`

References:
http://stackoverflow.com/a/1006074
http://www.ietf.org/rfc/rfc2396.txt (in the RFC, `+` is not given special character status, and therefore should remain untouched.)
http://download.java.net/jdk7/archive/b123/docs/api/java/net/URLDecoder.html

**Comment by hquan** [comment]
Yes same here. I spent hours to debug but finally found it's unirest's bug.

**Comment by mlippens** [comment]
There's multiple issues of this already reported unfortunately.

**Comment by bogp** [comment]
Given that no one will ever fix this.... Here's a workaround (ugly, using reflection):
```java
    // workaround for https://github.com/Kong/unirest-java/issues/158
    private void applyWorkaroundForUnirestBug(HttpRequestWithBody request) {
        if (request.getUrl().contains("+")) {
            String fixedUrl = request.getUrl().replace("+", "%20");
            log.info("[FIX] URL override:\n" + request.getUrl() + "\n" + fixedUrl);
            try {
                Field protectedUrl = HttpRequestWithBody.class.getSuperclass().getDeclaredField("url");
                protectedUrl.setAccessible(true);
                protectedUrl.set(request, fixedUrl);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
```
The bug is [here](https://github.com/Kong/unirest-java/blob/72a53ff8535fdb89f07c2982dbdaacb1302093da/src/main/java/com/mashape/unirest/request/HttpRequest.java#L113):
```java
 public HttpRequest queryString(String name, Object value) {
        StringBuilder queryString = new StringBuilder();
        if (this.url.contains("?")) {
            queryString.append("&");
        } else {
            queryString.append("?");
        }

        try {
            // HERE ->         System.out.println(URLEncoder.encode("test test", "UTF-8")); = test+test
            queryString.append(URLEncoder.encode(name)).append("=").append(URLEncoder.encode(value == null ? "" : value.toString(), "UTF-8"));
        } catch (UnsupportedEncodingException var5) {
            throw new RuntimeException(var5);
        }

        this.url = this.url + queryString.toString();
        return this;
    }
```

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
