### ISSUE TITLE
Setting post cookie with header does not work on unirest

### ISSUE THREAD

**Issue by darilldrems** [Kong/unirest-java#159]
When I make a request to my server the first time, I need to save the cookie from the first request's response and pass it to the second request.
This is how I attempted to solve the problem. Any help?

HttpResponse<String> response = Unirest.post("xyz.com").asString();

String cookie = response.getHeaders().getFirst("Set-Cookie");

In the next request the I try to do

HttpRequest req = Unirest.post("amy.xy");
req.header("Set-Cookie", cookie);
req.asString();

This request sets the set-cookie header but when I check my log but my server does not recognize it. Any advice?

**Comment by MiErnst** [comment]
"Set-Cookie" is a response header which should result that a "Browser" should handle the returned cookie. If you want to submit this cookie it should be contained in the "Cookie" header not the "Set-Cookie" header. See also: https://en.wikipedia.org/wiki/HTTP_cookie#Setting_a_cookie

**Comment by ryber** [comment]
Unirest does now support managing cookie state in Apache, in fact that is the default behavior
