### ISSUE TITLE
Unirest PUT Request - Fails to format a multipart request body correctly

### ISSUE THREAD

**Issue by apoorvakatta** [Kong/unirest-java#165]
**Multipart Request Body from PostMan and Unirest PHP**
![multipart request body from postman and unirest php](https://cloud.githubusercontent.com/assets/20812836/17922252/a9c51b5e-6a10-11e6-9472-0e3a91a7eee2.PNG)

**Multipart Request Body from Unirest Java**
![multipart request body from unirest java](https://cloud.githubusercontent.com/assets/20812836/17922155/2e5b92ea-6a10-11e6-871c-d9cca2cfcbac.png)

**Comment by mlippens** [comment]
I've seen a lot of encoding issues in Unirest, and tbh I don't have high hopes that those get fixed anytime soon. I'd recommend you to use Apache's HttpClient or Jersey client (based of HttpClient). Even though this project is also based upon it, we moved away from Unirest.

**Comment by neilyoung** [comment]
Wow, same here, more than a year later... And still not fixed. Congratulation!!!

**Comment by ArielYanarico** [comment]
@neilyoung do you have any code example?

**Comment by ryber** [comment]
Can you please post a code sample of how you are using Unirest?

**Comment by neilyoung** [comment]
@ArielYanarico Sorry, got no notification regarding your comment
@ryber This works for me. You see the work around. Replace "MyUserAgent" by something else.

```
void sendMultipartRequest(final String method, final String url,
                              final String stringRequest,
                              final String filePath,
                              final String username, final String password,
                              final BooleanCallback callback) {

        HttpRequestWithBody req = (method == "POST" ? Unirest.post(url) : Unirest.put(url));
        req.header("User-Agent", "MyUserAgent");
        req.header("Accept", "application/json");
        req.basicAuth(username, password);

        HashMap<String, Object> fields = new HashMap<>();

        // Work around https://github.com/Kong/unirest-java/issues/165
        if (stringRequest != null) {
            try {
                File tempFile = File.createTempFile("info-", "-temp");
                BufferedWriter bw = new BufferedWriter(new FileWriter(tempFile));
                bw.write(stringRequest);
                bw.close();
                tempFile.deleteOnExit();
                fields.put("INFO", tempFile);
            } catch (IOException e) {
                callback.onFalse("Could not create temp file.");
            }
        }

        if (filePath != null)
            fields.put("MAP", new File(filePath));

        // All fields must be set with one request
        if (fields.size() > 0)
            req.fields(fields);

        req.asStringAsync(new Callback<String>() {

            @Override
            public void completed(HttpResponse<String> httpResponse) {
                if (httpResponse.getStatus() == 200) {
                    callback.onTrue();
                    return;
                }
                // Either error or HTTP error
                try {
                    callback.onFalse(httpResponse.getBody());
                }
                catch (Exception e) {
                    callback.onFalse(httpResponse.getStatusText());
                }
            }

            @Override
            public void failed(UnirestException e) {
                callback.onFalse(e.getMessage());
            }

            @Override
            public void cancelled() {
                callback.onFalse("Upload cancelled");
            }
        });
    }

```

**Comment by ryber** [comment]
So, starting to work on this. The reason it's like this is because Unirest basically deals with two possibilities for a multipart form: 

1. A file, 
2. ulr-encoded params

It's basically just dealing with what a traditional old school HTML form could do.

So we can certainly deal with other types of parts, there are some edge cases in fact where what it's attempting to do is not what I think anyone would expect. What I'm aiming for are some methods like:

```java
Unirest.post("http://somwhere")
             .field("name", "bob") // <- this continues to go into the url-encoded-param section
             .field("mp3", new File("/tmp/file.mp3") // <- this clearly goes into a octet-stream part
             .part("{some json}", "application/json") // <- this would go into it's own part
```

Open for some other ideas and suggestions on name. "Part" matches what javax calls it. Keep in mind we need to maintain existing functionality. for people using it as basically a HTML form submission.

**Comment by ryber** [comment]
actually, it looks like, somewhere along the lines in the OpenUnirest fork I sort of fixed this, it's formatting it right I believe, so a request like this:

```java
Unirest.post(MockServer.ECHO_RAW)
                .field("marky","mark")
                .field("funky","bunch")
                .field("file", new File("/test"))
                .asString();
```

will end up submitting a body like this:

```
--wKUYQjzmmkD14RddBYO_ZOn3i9RTc_
Content-Disposition: form-data; name="file"; filename="test"
Content-Type: application/octet-stream

This is a test file
--wKUYQjzmmkD14RddBYO_ZOn3i9RTc_
Content-Disposition: form-data; name="funky"

bunch
--wKUYQjzmmkD14RddBYO_ZOn3i9RTc_
Content-Disposition: form-data; name="marky"

mark
--wKUYQjzmmkD14RddBYO_ZOn3i9RTc_--
```

There are still some other things I want to add before closing this issue including forcing a request into multipart mode even without a file

**Comment by ryber** [comment]
added a method to force the request into multipart even when you don't have a file
