### ISSUE TITLE
Project dead, new maintainer needed?

### ISSUE THREAD

**Issue by mlippens** [Kong/unirest-java#166]
I've been following up on this project and nothing seems to happen.
Many people report bugs with path parameters, query parameters etc, but nothing is done about them.

Maybe this project should seek a new maintainer?

**Comment by navopw** [comment]
This project definetly needs a new maintainer, there are open pull requests from 2014.

**Comment by josueeduardo** [comment]
I've been maintaining a [fork of this project](https://github.com/josueeduardo/rest-client), I'm currently migrating all these issues in order to get them fixed.

**Comment by bitsal** [comment]
Nice! @josueeduardo Good job!

**Comment by jdbevan** [comment]
Looks like there's two competing forks https://github.com/OpenUnirest/unirest-java

**Comment by ryber** [comment]
Yep, Hi there, I'll be one of the maintainers going forward. Should have a new version out soon
