### ISSUE TITLE
Rename asXXX methods in BaseRequest

### ISSUE THREAD

**Issue by JMVM** [Kong/unirest-java#168]
Hi there,

Please could you rename asXXX methods in BaseRequest related to send request? For example, asString()

It's confusing, looking like returning request as string, instead of response as string as having a look method code.

Thanks

**Comment by josueeduardo** [comment]
The BaseRequest asXXX is intended to be the termination method call of the API and it represents the response, not the request.

**Comment by ryber** [comment]
This would be a massive breaking change to everyone using this library. As you know the 2 hardest things in computer science are naming things, cache invalidation, and off by one errors
