### ISSUE TITLE
field + asJson() formates request as "key=value"

### ISSUE THREAD

**Issue by pozhidaevak** [Kong/unirest-java#169]
I'm using this code:
`HttpResponse<JsonNode> response = Unirest.post("http://example.com/endpoint")
                .header("Accept", "application/json").header("Content-type", "application/json")
                .field("productVersionId",7309).asJson();`
It generates next request body:
`productVersionId=7309`

Shouldn't it generate JSON object? `{"productVersionId":7309}`. 

However this is working:
`JSONObject object = new JSONObject();
        object.put("productVersionId", 7309);
        HttpResponse<JsonNode> response = Unirest.post("http://example.com/endpoint")
                .header("Accept", "application/json").header("Content-type", "application/json")
                .body(object).asJson()`

**Comment by ryber** [comment]
```asJson()``` refers to the parsing of the result, not of the request. Your second block is correct.
