### ISSUE TITLE
Subsequent calls to Unirest.delete(url) results in SocketTimeoutException

### ISSUE THREAD

**Issue by ppone** [Kong/unirest-java#171]
Subsequent calls after a call to Unirest.delete(url), results in a `java.net.SocketTimeoutException: Read timed out` exception.

For example

``` java
Unirest.delete(url)
Unirest.delete(url) 
```

will result in a socket timeout on the second call.

**Comment by ryber** [comment]
I don't think this is due to anything in Unirest but is related to the remote server
