### ISSUE TITLE
Duplicate releaseConnection code in HttpClientHelper.java 

### ISSUE THREAD

**Issue by maksutspahi** [Kong/unirest-java#172]
There is a duplicate releaseConnection code in HttpClientHelper.java:140.
Current code:

```
    try {
            response = client.execute(requestObj);
            HttpResponse<T> httpResponse = new HttpResponse<T>(response,        responseClass);
            requestObj.releaseConnection();
            return httpResponse;
        } catch (Exception e) {
            throw new UnirestException(e);
        } finally {
            requestObj.releaseConnection();
        }
    }
```

Since there is `requestObj.releaseConnection();` in finally block, there is no need for `requestObj.releaseConnection();` at the end of the try block.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
