### ISSUE TITLE
[question] Upload multiples files

### ISSUE THREAD

**Issue by gchauvet** [Kong/unirest-java#174]
Hi,

First, nice API ! Really easy to use !
However, I've a question about uploading multiple files in a single POST request : 

``` java
final MultipartEntityBuilder builder = MultipartEntityBuilder.create();
files.forEach(file -> {
     builder.addBinaryBody(file.getName(), file);
});
final InputStream content = builder.build().getContent();
```

How can I use my content InputStream with Unirest ? Like this : 

``` java
return Unirest.post(getResource().toExternalForm())
.fields(params)
.field("file", content, null);
```

**Comment by rwinscot** [comment]
Take a quick look at the different signatures on Unirest.post()... you should see this one.

```java
Unirest.post().field(String name, Collection<?> collection) : MultipartBody - MultipartBody
```

So... something like this (below) would give you multiple uploads in a single POST.

```java
ArrayList<File> filez = new ArrayList<File>();
filez.add(new File("./file_one.txt"));
filez.add(new File("./file_two.txt"));

HttpResponse<JsonNode> resp = Unirest.post("https://you_upload_end_point_here/")
  .field("files", filez)
  .asJson();
```
Note that the field name is now 'files' instead of just 'file.'

**Comment by waqasraz** [comment]
Is it possible to send a list of files as key-value?

`
Map<String, Object> filesToSend = new HashMap<>();
ArrayList<File> files = new ArrayList<>();
files.add(new File(f.get().toUri()));
filesToSend.put(fileInfo.getDescription(), files)

JsonNode finalOutput = Unirest.post("http://<ip>/upload/33/")
                .header("Authorization", "Bearer " + accessToken)
                .field("files", filesToSend)
                .field("scope_number", "Test")
                .asJson()
                .getBody();
`
When I send this request the files sent as a path only.

**Comment by ryber** [comment]
Sure @waqasraz, you can pass a ```Map<String, File>``` :

```
Unirest.post(MockServer.POST)
                .fields(ImmutableMap.of(
                        "file1", file1,
                        "file2", file2
                        ))
                . asJson();
```
