### ISSUE TITLE
Out of memory error when downloading big files 

### ISSUE THREAD

**Issue by samipetteri** [Kong/unirest-java#180]
Downloading big files fails because whole HTTP response is saved into bytearray.

https://github.com/Mashape/unirest-java/blob/e4b63d2f0dbc36b752c34c99f68deff30985ce83/src/main/java/com/mashape/unirest/http/HttpResponse.java#L81-L91

**Comment by T3rm1** [comment]
Encountered the same problem. This should be fixed asap. getRawBody returns an InputStream. This should be the InputStream of the response.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
