### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Applemann** [Kong/unirest-java#185]
Hello, when will be next release of Unirest?
I would like use Unirest with fixed some last bugs which are repaired but not released yet.

**Comment by ryber** [comment]
Soon

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
