### ISSUE TITLE
Your dependencies are far behind. 

### ISSUE THREAD

**Issue by ph-hs** [Kong/unirest-java#186]
Even if you have no code changes yourself, you should keep abreast of key components (like apache http client).

**Comment by shayneoAtNorwood** [comment]
I'm getting the feeling this projects been abandoned :(

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
