### ISSUE TITLE
Closable interface needed

### ISSUE THREAD

**Issue by ph-hs** [Kong/unirest-java#188]
```
public static void shutdown() throws IOException {
        CloseableHttpClient syncClient = (CloseableHttpClient)Options.getOption(Option.HTTPCLIENT);
        if(syncClient != null) {
            syncClient.close();
        }
...
```
`ClosableHttpClient` is a class not an interface. `ClosableHttpClient` should implement `Closable`, which should have a `close()` method. Implementors of `HttpClient` **may** implement `Closable` too.

This because I'm trying to make an instrumenting HttpClient that times every call, and I'm using `Unirest.setHttpClient(x)`

**Comment by StdVectorBool** [comment]
What's the issue or question here?

ClosableHttpClient implements both HttpClient and Closeable interfaces:
https://github.com/apache/httpclient/blob/4.5.x/httpclient/src/main/java/org/apache/http/impl/client/CloseableHttpClient.java#L57

**Comment by ryber** [comment]
Also, this is a Apache class not a Unirest one. However the new version of Unirest coming out soon does implement Closable on it's Client Wrapper

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
