### ISSUE TITLE
may cause memory leak when using gzip encoding.

### ISSUE THREAD

**Issue by hydrogen666** [Kong/unirest-java#190]
version:1.4.9
class: com.mashape.unirest.http.HttpResponse line:85
when content-encoding is gzip, new a GZIPInputStream, where to close this InputStream?
Will it cause memory leak?

**Comment by ymartin59** [comment]
Sure. With Java 8, GZIP support has moved from Java code to native zlib usage.
As a result, a non-closed GZIP stream will leak native memory (I really said "native" not "heap" memory) and it is far from easy to diagnose.
You will find full story details at http://www.evanjones.ca/java-native-leak-bug.html
