### ISSUE TITLE
PUT client command adds header and footer to uploaded file

### ISSUE THREAD

**Issue by 4shotespresso** [Kong/unirest-java#191]
I am seeing an issue when I use Unirest to “put” a file (upload). The length of the file changes from it’s original (206633 bytes), and performing a file diff shows a header and footer added to my file upon upload. This header/footer changes size (but ~230 bytes each time), and the file becomes unreadable by a downstream process. Unirest is adding this content to my file during the processing prior to calling the Rest endpoint, is there a way to turn it off?   Note that when I run this process manually in a Rest client (Postman), it does not add this header/footer.  I've also confirmed that uploads using Jersey REST client do not add the header/footer to my uploaded files.

My Unirest call is as follows, the file on cloud storage becomes ~206866 each time (size changes based on the header/footer values added).

HttpResponse<String> response = Unirest.put(url)
.header("Authorization", "Bearer " + _token + "")
.header("Content-Type", "application/octet-stream")
.field("file", new FileInputStream(file), ContentType.APPLICATION_OCTET_STREAM, file.getName())
.asString();

--f43zuGvyCxUMHYfAhe1k_jI9xGAKJnLvhfAuZ

Content-Disposition: form-data; name="file"; filename="Cylinder.stp"

Content-Type: application/octet-stream

Content-Transfer-Encoding: binary

[Original File Content]

--f43zuGvyCxUMHYfAhe1k_jI9xGAKJnLvhfAuZ--

**Comment by khuntias** [comment]
I am facing the same problem  when I am trying to upload a file to a storage bucket . 
This is my method . 
HttpResponse uploadFile(String uploadUrl, String file){
		return Unirest.put(uploadUrl)
				.header("Content-Type", null)
				.field("file", new File(file))
				.asString();
	}

**Output which I get is** : 

--lZG6vDKtkbpI75v1vUOLJky2-4C43z5o
Content-Disposition: form-data; name="file"; filename="happyPathFileUpload.csv"
Content-Type: application/octet-stream
Content-Transfer-Encoding: binary

[Original File Content]

--lZG6vDKtkbpI75v1vUOLJky2-4C43z5o--

 @4shotespresso -> Did you find any workaround or solution to this problem.

**Comment by 4shotespresso** [comment]
My workaround was to use another rest client library.

**Comment by reeislam** [comment]
which library you used

**Comment by ryber** [comment]
This was fixed somewhere along the way. see https://github.com/Kong/unirest-java/blob/master/unirest/src/test/java/BehaviorTests/MultiPartFormPostingTest.java

**Comment by ryber** [comment]
just realized, the headers and footers you are talking about are the multipart form section which are part of the standard. Is what you wanted to do was a single binary body?
