### ISSUE TITLE
QueryString null

### ISSUE THREAD

**Issue by kang-junyoung** [Kong/unirest-java#193]
Hello.

I used to use unirest very well.
Anyway, I have a problem with using queryString but I think I have a problem with it.

my code....
```java
        Map<String, Object> queryParams = new HashMap<>();
        queryParams.put("pattern", null);

       HttpResponse<String> response = null;
        try {
            response = Unirest.post(host)
                    .header("Content-Type", "application/json; charset=UTF-8")
                    .queryString(queryParams)
                    .body(body)
                    .asString();
        } catch (UnirestException e) {
            log.error(e.toString(), e);
        }
```

The above code produces NPE.
Because if you look at the code, you can see the following 

```java
public HttpRequest queryString(Map<String, Object> parameters) {
		if (parameters != null) {
			for (Entry<String, Object> param : parameters.entrySet()) {
				if (param.getValue() instanceof String || param.getValue() instanceof Number || param.getValue() instanceof Boolean) {
					queryString(param.getKey(), param.getValue());
				} else {
					throw new RuntimeException("Parameter \"" + param.getKey() + "\" can't be sent with a GET request because of type: " + param.getValue().getClass().getName());
				}
			}
		}
		return this;
	}

```

NPE was catched ```throw new RuntimeException("Parameter \"" + param.getKey() + "\" can't be sent with a GET request because of type: " + param.getValue().getClass().getName());```

So... I think you need to process when param.getValue() is null. What do you think ?..

Thank you.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
