### ISSUE TITLE
Ability to disable SSL checks

### ISSUE THREAD

**Issue by ochompsky** [Kong/unirest-java#197]
It's 2017.  Why isn't there the option to disable SSL checks without writing cumbersome code on top of it?

There's absolutely no excuse.

**Comment by laviua** [comment]
```
        Unirest.setHttpClient(HttpClients.custom()
                .setSSLContext(SSLContextBuilder().loadTrustMaterial(null) { _, _ -> true }.build())
                .setSSLHostnameVerifier(NoopHostnameVerifier())
                .build())
```
I'm not sure that this is a big cumbersome construction (kotlin)
So this is a rather controversial issue.
Do you want to use something like Unirest.disableSSLVerification() ?

**Comment by MrGraversen** [comment]
I experienced the same issue with a Let's Encrypt certificate (on https://api.mjml.io/v1/render).

This was my solution (same as @laviua but in plain Java):

```
HttpClients.custom()
                    .setSSLContext(new SSLContextBuilder().loadTrustMaterial(null, (x509Certificates, s) -> true).build())
                    .setSSLHostnameVerifier(NoopHostnameVerifier.INSTANCE)
                    .build();
```

Simply replace `HttpClients` with `HttpAsyncClients` and set it using the `Unirest#setAsyncHttpClient` method for async usage.

**Comment by kingb** [comment]
Just for comparison, this is how easy it is to do in one line of Python with the `requests` package:

`response = requests.get('https://kennethreitz.org', verify=False)`

Hence @ochompsky's "cumbersome code" comment.

**Comment by ramiko12** [comment]
Agreed, the workarounds to get this to work in a development environment arent worth the time and effort.

**Comment by ryber** [comment]
I'm interested in adding this, because I've run into it may times myself. But I'd also like to test it. Does anyone know of a way to generate, on the fly, a self signed cert  and add it to a keystore? I've done it in C# and I'm having a hard time figuring it out in Java without shelling out. It could need to work in CI as well.

**Comment by ryber** [comment]
I found this lovely site. It will do: https://badssl.com/

**Comment by ryber** [comment]
Done in 2.0.04 Unirest.config().verifySsl(false)
Note that once set you must rest the config to change it back as Apache client construction is quite expensive.
