### ISSUE TITLE
JRE Version 8 Update 121 HTTPS ssl exception 

### ISSUE THREAD

**Issue by distributev** [Kong/unirest-java#199]
Background - there is an existing software which is using unirest to access an https website endpoint. The SSL certificate of the website (endpoint) is issued by GoDaddy.

This software was used for a long time by users without issues - However, using the latest JRE Version 8 Update 121, today one user got this SSL certificate exception. It's the same software and the same website which used to work without issues. Initially I thought it's an issue with the user's java installation so I un-installed java and installed back but I got the same error. 

Do you have any idea what is happening and why (suddenly) it started to fail? What are my options?

Here is the screen-shot with the exception

![ssl-exception](https://cloud.githubusercontent.com/assets/19224635/24020479/99cc76e8-0a9c-11e7-9f45-8faae585ab99.png)

**Comment by distributev** [comment]
Do you have any idea why this is happening?

**Comment by jordaoesa** [comment]
Same error here :/

`com.mashape.unirest.http.exceptions.UnirestException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)`

**Comment by ryber** [comment]
Unirest simply uses the given Java keystore so I don't think this would have anything to do with Unirest itself. I've upgraded all the dependencies so 🤷‍♀️ best I can do. I'd try updating to the newest patch of Java 8
