### ISSUE TITLE
Unable to use generic class as 'asObject' parameters

### ISSUE THREAD

**Issue by petrdvorak** [Kong/unirest-java#200]
When I work with Spring `RestTemplate` class, I can use `ParametrizedTypeReference` instance to provide generic class to deserialization, like so:

```java
ResponseEntity<ApiResponse<Payment>> response = template.exchange(request, new ParameterizedTypeReference<ApiResponse<Payment>>() {});
```

This is really nicely integrated in the overall code.

It would be nice to include a chapter on how to achieve this with Unirest. For example:

```java
// Generic response type

HttpResponse response = Unirest.post(uri)
    .header("Accept", "application/json")
    .header("Content-Type", "application/json")
    .body(body)
    .asString();

ObjectMapper mapper = new ObjectMapper();
TypeReference<ApiResponse<Payment>> type = new TypeReference<ApiResponse<Payment>>() {};
ApiResponse<Payment> responseWrapper = mapper.readValue(response.getRawBody(), type);
```

Ideally, it would be nice to be able to provide some API where I can actually use type reference as a parameter, for example:

```java
HttpResponse response = Unirest.post(uri)
    .header("Accept", "application/json")
    .header("Content-Type", "application/json")
    .body(body)
    .asObject(new TypeReference<ApiResponse<Payment>>() {});
```

**Comment by xperjon** [comment]
Looking for this feature too.

**Comment by andrekat** [comment]
I am using Unirest with generic class calls. Is this what are you looking for?

```
public <T> T doGet(String path, Class<T> className) throws UnirestException {

        String url = (path.startsWith("http") || path.startsWith("www")) ? path : base_url + path;

        Main.log.debug("doGet: " + url);

        if (!path.startsWith("/")) {
            path = StringUtils.overlay(path, "/", 0, 0);
        }

        return Unirest.get(this.base_url + path).header("accept", "application/json").asObject(className).getBody();
    }
```

Example of calling this method:

`
 ResponseMusicContent response = OneClient.getInstance().doGet(url, ResponseMusicContent.class);
`

**Comment by petrdvorak** [comment]
@andrekat No, please read my original post. I have a generic `ApiRequest<T>` and `ApiResponse<T>` classes and I need to serialize these using Unirest. However, there is no such thing as `ApiResponse<SomeClass>.class`, hence you need to use `TypeReferece` as I demonstrated in my workaround. It would be nice to have `.asObject(t)` accepting `TypeReference` as parameter and using `ObjectMapper` instance associated with Unirest...

**Comment by Fl317** [comment]
@petrdvorak I don't know if this is helpfull but I used a little workaround. I handled the ApiResponse in the ObjectMapper. In my case all Api Responses are just wrapped in a **data** Object and all I wanted to do is to unwrap it. If your Response class is more complex it won't help much I think.

```
Unirest.setObjectMapper(new ObjectMapper()
{
    private com.fasterxml.jackson.databind.ObjectMapper jacksonObjectMapper = new com.fasterxml.jackson.databind.ObjectMapper();

    public <T> T readValue(String value, Class<T> aClass)
    {
        try
        {
            Response<T> response = jacksonObjectMapper.readValue(value, new TypeReference<Response<T>>() {});
            return jacksonObjectMapper.convertValue(response.data, aClass);
        }
        catch(IOException e)
        {
            throw new RuntimeException(e);
        }
    }

    public String writeValue(Object value)
    {
        try
        {
            return jacksonObjectMapper.writeValueAsString(value);
        }
        catch(JsonProcessingException e)
        {
            throw new RuntimeException(e);
        }
    }
});
```

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
