### ISSUE TITLE
Add Session Management Mechanism (Cookies, etc.)

### ISSUE THREAD

**Issue by jcantu-usgs** [Kong/unirest-java#202]
It appears that the PHP version of Unirest added session support in the way of cookies at version 2.4.0.  However, the Java Unirest client does not have this capability.  I'd like to request that this feature be added to the Java library as well.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
