### ISSUE TITLE
Add charset to MultipartBody

### ISSUE THREAD

**Issue by pherklotz** [Kong/unirest-java#206]
affected version: 1.4.9

Problem: The default multipart charset from Apache Http Client is 'US-ASCII' which destroys UTF-8 chars.

Solution: Please add the possibility to set a charset in `com.mashape.unirest.request.body.MultipartBody`.
A builder-style set method like `mode(String)` for the HttpEntity charset would be great. 

Changes in com.mashape.unirest.request.body.MultipartBody:

- add a new method 'charset(Charset)'

```java
	public MultipartBody charset(Charset charset) {
		this.charset = charset;
		return this;
	}
```

- set the charset in the getEntity-Method

```java
...
builder.setCharset(this.charset);
...
```

**Comment by Catscratch** [comment]
+1

But as default behaviour UTF-8 should be set by Unirest if nothing else is specicified. According RFC 7578 it should be UTF-8 anyway...I guess.

**Comment by spance** [comment]
Many unicode language users have been affected by this issue.
Unirest MultipartBody needs to support `setCharset(x)` method or use UTF-8 as the default charset.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
