### ISSUE TITLE
Error when URL has a hyphen during Unirest.post

### ISSUE THREAD

**Issue by vivekreddy** [Kong/unirest-java#210]
When I am running the following code, it works fine when the URL does not have any hyphen. But when the URL has a hyphen I am getting the below error. Please help.

Code:
  HttpResponse<JsonNode> authTokenResp = Unirest.post(url)
                .header("Content-Type",APPLICATION_JSON)
                .body(new JsonNode(authTokenReq.toString()))
                .asJson();

Error:
Exception in thread "main" com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)

**Comment by ks228** [comment]
Did you sort it out?

**Comment by ryber** [comment]
```asJson``` will throw a parsing error like that whenever the returned body is not valid JSON. Most services do not return valid JSON for non-200 errors like ... 404.  do the same call with ```asString``` and check the status code and body, I bet you are not getting back a valid 200. This parsing error has been made more clear in the OpenUnirest fork https://github.com/OpenUnirest/unirest-java

**Comment by ryber** [comment]
I'll be merging OpenUnirest back in shortly. Taging this for now

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
