### ISSUE TITLE
ContentTooLongException

### ISSUE THREAD

**Issue by andrekat** [Kong/unirest-java#211]
I am getting an exception when downloading an file which is bigger than Integer.MAX_VALUE: Entity content is too long: 3272008971

Is there a workaround without overriding the HttpClient?

Regards,

**Comment by ryber** [comment]
This is fixed in an upcoming version. Ill tag this and close it when it's out.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
