### ISSUE TITLE
Support for Java 8 CompletableFuture

### ISSUE THREAD

**Issue by gabfssilva** [Kong/unirest-java#213]
Not sure if this lib is built on JDK 8, but, if it is, it'd be nice to use CompletableFuture instead of the old Future class:

```java
CompletableFuture<HttpResponse<String>> eventualResponse = Unirest.get("http://").asStringFuture();

eventualResponse.thenAccept(response -> {
    //code over here
});
```

Since Unirest has already a Callback interface, it'd be easy to convert it into a CompletableFuture:

```java
public class CallbackPromise<T> extends CompletableFuture<HttpResponse<T>> implements Callback<T> {
    @Override
    public void completed(HttpResponse<T> response) {
        complete(response);
    }

    @Override
    public void failed(Exception e) {
        completeExceptionally(e);
    }

    @Override
    public void cancelled() {
        completeExceptionally(new UnirestException("cancelled"));
    }
}
```

**Comment by yannxia** [comment]
+1

**Comment by jenshimmelreich** [comment]
+1

**Comment by himanshujaju** [comment]
+1

**Comment by michaleczky** [comment]
+1

**Comment by ryber** [comment]
I was playing around with this on a fork, I was actually just going to convert all of the existing async methods to return a CompletableFuture rather than a plain old Future. It was sort of working, one thing I ran into was this issue https://issues.apache.org/jira/browse/HTTPCLIENT-1805

I'm a little unsure of exposing this functionality if people will end up shooting themselves in the foot with it. It sounds like HttpClient 5 works but that is still beta and would be a major overhaul for the library.

**Comment by ds-perfit** [comment]
+1

**Comment by gabfssilva** [comment]
@ryber that's curious, I didn't get this issue, even running on a single thread (since it was a small microservice that used only 1 vCPU).

Anyway, I wouldn't recommend to use this library anymore. It is kind of abandoned.

If you use JDK 7/8, use this: https://github.com/timboudreau/netty-http-client
If you use JDK 9+, use this: https://developer.oracle.com/java/jdk-http-client

**Comment by ryber** [comment]
@gabfssilva thanks. I'm actually now maintaining an updated fork of this project where I've addressed this issue: https://github.com/OpenUnirest/unirest-java

**Comment by ryber** [comment]
I'll be merging OpenUnirest back into this. Taging for now

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
