### ISSUE TITLE
Unable to set time outs ...

### ISSUE THREAD

**Issue by CSBaum** [Kong/unirest-java#216]
Hello,

I am trying to use the `Unirest.setTimeouts(connectionTimeout, socketTimeout);` method on a plain vanilla Unirest object, meaning, I am not setting a custom client or anything else and I get the following exception:

```java.lang.RuntimeException: You can't set custom timeouts when providing custom client implementations. Set the timeouts directly in your custom client configuration instead.```

The `setTimeouts()` is the very 1st call I make on the Unirest object. 

I have taken a look at the code and it looks like there are only 2 places where the `customClientSet()` method is called and I am not calling either (Unirest.java lines 50 & 58).

Thanks in advance for any insight on what I am missing.   

Sean

**Comment by ryber** [comment]
This is fixed in an upcoming version. Ill tag this and close it when it's out.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
