### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.http.ssl.SSLContexts

### ISSUE THREAD

**Issue by ebuildy** [Kong/unirest-java#221]
Version 1.4.9

It's fixed by adding right dependencies, but I dont understand why a SSL error whereas I dont use https ?

A simple

```
 final HttpResponse<JsonNode> response = Unirest.get(String.format("http://%s/%s/_count?q=%s", host, esIndex, URLEncoder.encode(esCleanQuery, "UTF-8"))).asJson();
```

Gives me an execption about SSL whereas I ask http:

> Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/ssl/SSLContexts
> 	at org.apache.http.nio.conn.ssl.SSLIOSessionStrategy.getDefaultStrategy(SSLIOSessionStrategy.java:93)
> 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.getDefaultRegistry(PoolingNHttpClientConnectionManager.java:105)
> 	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.<init>(PoolingNHttpClientConnectionManager.java:112)
> 	at com.mashape.unirest.http.options.Options.refresh(Options.java:86)
> 	at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
> 	at com.mashape.unirest.http.HttpClientHelper.prepareRequest(HttpClientHelper.java:151)
> 	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:131)
> 	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)

**Comment by freakynit** [comment]
I have started to face the same issue. Seems wasn't there in previous versions. Can't comment for sure. 
Stacktrace:
`Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/http/ssl/SSLContexts
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.getSocketFactory(SSLConnectionSocketFactory.java:172)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.getDefaultRegistry(PoolingHttpClientConnectionManager.java:109)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:116)
	at com.mashape.unirest.http.options.Options.refresh(Options.java:72)
	at com.mashape.unirest.http.options.Options.<clinit>(Options.java:46)
	at com.mashape.unirest.http.Unirest.setObjectMapper(Unirest.java:77)`

**Comment by ryber** [comment]
You most likely have a different version of Apache HttpClient on your classpath that is getting picked up before the one Unirest expects. We will have a new version of Unirest out shortly that has a updated Apache Client but that may not fix your issue. Take a look at mvn dependency:tree (or similar if not using maven) to see where you may have conflicts

**Comment by dpalic** [comment]
having the same issue with a very simplistic setup

**Comment by StanZha** [comment]
Follower @ryber advise and removed org.apache.httpcomponents:httpclient:4.3.4 from pom file to fix problem. I am using unirest-java 1.4.9
