### ISSUE TITLE
testCaseInsensitiveHeaders fails

### ISSUE THREAD

**Issue by javabrett** [Kong/unirest-java#227]
```
Results :

Failed tests:   testCaseInsensitiveHeaders(com.mashape.unirest.test.http.UnirestTest): expected:<[Marco,]John> but was:<[]John>

```

Looks like httpbin returns de-duplicated Name header and only the second value survives.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
