### ISSUE TITLE
fix param value is not instance of String but is instance of CharSequence

### ISSUE THREAD

**Issue by phingocchi** [Kong/unirest-java#230]
Please replace this code bellow by
`param.getValue() instanceof CharSequence`

https://github.com/Kong/unirest-java/blob/3b461599ad021d0a3f14213c0dbb85bab7244f66/src/main/java/com/mashape/unirest/request/HttpRequest.java#L124

**Comment by ryber** [comment]
This is fine in the OpenUnirest project. Feel free to open a issue if you are finding a different result from this test:
https://github.com/OpenUnirest/unirest-java/commit/f3590d61509d369279940290dbf8340163e3ff42

https://github.com/OpenUnirest/unirest-java

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
