### ISSUE TITLE
Honor useSystemProperties() when setting up HttpClients

### ISSUE THREAD

**Issue by rogoman** [Kong/unirest-java#231]
The current implementation doesn't account for any networking system settings (i.e. proxy settings). It's easy to fix by using the .useSystemProperties() method on an HttpClientBuilder. There's actually a fix already in one of the PRs: https://github.com/Kong/unirest-java/pull/220

**Comment by ryber** [comment]
This is now available in OpenUnirest 3.0.03 (should be in maven central in a few minutes) https://github.com/OpenUnirest/unirest-java/issues/14

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
