### ISSUE TITLE
Memory leak in: Options.java

### ISSUE THREAD

**Issue by Alcuin-van-Zijl** [Kong/unirest-java#233]
The static function refresh is called every time the Options are invoked statically.

On line 72 you create a new PoolingHttpClientConnectionManager.
Online 77 you set a new option with the new PoolingHttpClientConnectionManager.

The previous one (in the options map) if there was one is now not linked to anything.
As the PoolingHttpClientConnectionManager is a thread the garbage collector will not be removing the old manager.
Also this setup provides a performance hit. The PoolingHttpClientConnectionManager is build around the idea that you can reuse connections. Creating a new one for every call is not very efficient.

Note that this issue is not very noticeable unless you do a lot of calls or have very little memory available.
As the leak are threads they are not stored in the reserved memory so setting the max heap will not prevent this leak. I noticed this leak when my server got more virtual memory used than there was real memory. The server then started swapping the memory. As they are threads the swapping continued endlessly as the server needed to check the status of the thread every now and then.
Using the memory analyzer of eclipse its pretty apparent what the issue is. Do some 100 calls and you will end up with 100 PoolingHttpClientConnectionManager threads.

The same issue exists for the async manager but as I do not use this one I have not investigated this any further.

Maybe should introduce the term: Thread leak for this instead of memory leak  :)

**Comment by anonymouscodeholic** [comment]
I wrote a small application using Unirest. The application makes around 10 HTTP requests every 5 minutes. This causes severe memory lead that in a day leads to heap get full.

Here's a screenshot of leak analysis in Eclipse.

<img width="771" alt="screen shot 2018-03-24 at 8 48 53" src="https://user-images.githubusercontent.com/2356059/37861724-37fe1754-2f40-11e8-9751-0adbbfa1e16e.png">

I'm trying whether calling `Unirest.shutdown()` after each HTTP request fixes the problem.

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
