### ISSUE TITLE
Minor, but confusing, issue

### ISSUE THREAD

**Issue by hethcox** [Kong/unirest-java#234]
I was building out my REST call to mailgun and I used "apiKey" instead of "api" (started with a different example) thus:
                    .basicAuth("api", apiKey)
Instead of complaining about a missing key I got:
Caused by: org.json.JSONException: A JSONArray text must start with '[' at 1 [character 2 line 1]

It took a while to sort-out what was wrong. I'm posting this in hopes of saving future headaches.

**Comment by ryber** [comment]
This is because the library fails to parse the error message that returned from the service to json. It expects everything, including the errors to be JSON. I'm currently working on fixing this in a fork as this project is dead https://github.com/OpenUnirest/unirest-java/issues/10

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
