### ISSUE TITLE
Unirest does not seem to be exposing connection request timeout(org.apache.http.client.config.connectionRequestTimeout of RequestConfig)

### ISSUE THREAD

**Issue by satheeshakkinepally** [Kong/unirest-java#235]
It appears Unirest does not expose the connectionRequestTimeout when asking for connection from a pool and defaults to socket timeout . This is confusing as the potential timeout issues that are caused because of connectionRequestTimeout are solved by increasing the socketTimeout.

Further, if there are a many requests in the queue, they start timing out even if the client wants to throttle the messages and process them at a controlled rate by increasing connectionRequestTimeout while keeping the connectionTimeOut and socketTimeout the default

**Comment by ryber** [comment]
Fixed in upcoming v2

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
