### ISSUE TITLE
cannot find symbol setObjectMapper in class Unirest

### ISSUE THREAD

**Issue by i-mighty** [Kong/unirest-java#239]
while trying to set the object mapper for Unirest using
`
Unirest.setObjectMapper(new ObjectMapper() {
            private com.fasterxml.jackson.databind.ObjectMapper jacksonObjectMapper 
                    = new com.fasterxml.jackson.databind.ObjectMapper();
            
            public <T> T readValue(String value, Class<T> valueType) {
                try {
                    return jacksonObjectMapper.readValue(value, valueType);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
            
            public String writeValue(Object value) {
                try {
                    return jacksonObjectMapper.writeValueAsString(value);
                } catch (JsonProcessingException e) {
                    throw new RuntimeException(e);
                }
            }
        });
`

**Comment by ryber** [comment]
You possibly have a conflict in versions between this project and OpenUnirest. check that you do not have two different versions on the classpath

**Comment by peter-snr** [comment]
I am getting the same in a Spring Boot project using gradle deps.
        // https://mvnrepository.com/artifact/com.mashape.unirest/unirest-java
	compile group: 'com.mashape.unirest', name: 'unirest-java', version: '1.4.5'
	compile 'com.fasterxml.jackson.core:jackson-databind:2.10.1'



`import com.mashape.unirest.http.Unirest;

Unirest.setObjectMapper(new ObjectMapper() {
    com.fasterxml.jackson.databind.ObjectMapper mapper 
      = new com.fasterxml.jackson.databind.ObjectMapper();
 
    public String writeValue(Object value) {
        return mapper.writeValueAsString(value);
    }
 
    public <T> T readValue(String value, Class<T> valueType) {
        return mapper.readValue(value, valueType);
    }
});`

Error is 'cannot resolve method setObjectMapper'

About 4 hours googling reading docs, nothing?  I have checked the classpath, not sure why OpenUnirest would be in the classpath I have never heard of it or added to any of my classpaths.

Wanted to do a post with an Object, looks like I am going to have to create a JSON string with quotes backslashed, very ugly.

Is there anything I can check.

BTW I am initializing Unirest in my Application classes main method as I cannot find where in a spring boot project to insert the above code.

Thank you for any help.

Kind Regards
Peter

**Comment by ryber** [comment]
@peter-snr you are using a super ancient version of Unirest.

**Comment by ryber** [comment]
try using a modern version. Note that we changed groupId and everything

```
<!-- Pull in as a traditional dependency -->
<dependency>
    <groupId>com.konghq</groupId>
    <artifactId>unirest-java</artifactId>
    <version>3.1.02</version>
</dependency>

<!-- OR as a snazzy new standalone jar with shaded dependencies -->
<dependency>
    <groupId>com.konghq</groupId>
    <artifactId>unirest-java</artifactId>
    <version>3.1.02</version>
    <classifier>standalone</classifier>
</dependency>
```

**Comment by peter-snr** [comment]
@ryber thank you very much for your feedback, I finally have a solution, yes you were right the version I was using was well out of date.

My gradle dependencies are now: -

        // https://mvnrepository.com/artifact/com.konghq/unirest-java
	compile 'com.konghq:unirest-java:3.1.04'
        compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.4'

My configuration class does this....
    
    	@Configuration
	public class UnirestConfig {

		@Autowired
		private com.fasterxml.jackson.databind.ObjectMapper mapper;

		@PostConstruct
		public void postConstruct() {
			Unirest.config().setObjectMapper(new ObjectMapper() {

				public String writeValue(Object value) {
					try {
						return mapper.writeValueAsString(value);
					} catch (JsonProcessingException e) {
						throw new RuntimeException(e);
					}
				}

				public <T> T readValue(String value, Class<T> valueType) {
					try {
						return mapper.readValue(value, valueType);
					} catch (Exception e) {
						throw new RuntimeException(e);
					}
				}
			});
		}
	}

My controller class can now use Unirest with Java Classes

             HttpResponse<JsonNode> createUserResponse = Unirest.post(auth0UserCreateEndpoint)
                            .header("content-type", "application/json")
                            .header("authorization", "Bearer " + token)
                            .body(newUser)     // <== this is a User class instance
                            .asJson();
    
Works a treat, very happy with the results.
