### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by sic2** [Kong/unirest-java#241]
Unirest is a great library, but it looks like there is little development happening since 2016. 

It would be great to know the status of the project.

**Comment by jdbevan** [comment]
Looks like this fork https://github.com/OpenUnirest/unirest-java has had more attention recently

**Comment by mlippens** [comment]
Seems pretty dead to me, hence why I switched more than a year ago actually.

**Comment by MrGraversen** [comment]
@mlippens What did you switch to?

**Comment by ryber** [comment]
Good news, we will be merging OpenUnirest back into this project. Stay tuned!

![its-alive](https://user-images.githubusercontent.com/145359/53022838-a2b75600-3421-11e9-8816-e6ee290ca1a6.jpg)

**Comment by rnc** [comment]
@ryber  Great news!
