### ISSUE TITLE
No such Module 'ParseFacebookUtilsV4'

### ISSUE THREAD

**Issue by jonesgreg** [Kong/unirest-java#243]
I'm trying to convert this app from swift 3 to swift 4; however, I can't convert it unless I can fix this error message. When I click build, it says No such Module 'ParseFacebookUtilsV4' in my onBoardViewController class when I try to import it.  I updated the pods and changed the ParseFacebookUtilsV4 to    pod 'Parse/FacebookUtils'

Here is a copy of my pod file

platform :ios, '11.0'

target 'CueMe' do
    use_frameworks!
    
    
    pod 'Parse'
    pod 'FBSDKCoreKit','~> 4.28.0'
    pod 'FBSDKLoginKit','~> 4.28.0'
    pod 'FBSDKShareKit','~> 4.28.0'
    
    pod 'Parse/FacebookUtils'
    pod 'GoogleMaps', '~> 2.7.0'
    pod 'Alamofire', '~> 4.7.3'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'Onboard'
    pod 'SWRevealViewController'
    pod 'XLForm', '~> 4.0.0'
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end

I knew that ParseFacebookUitlsv4 is the old version,so I try to change it to import FacebookUtils

Does anyone know how to import Parse FacebookUtils ?

**Comment by ryber** [comment]
I think you posted this to the wrong project
