### ISSUE TITLE
Unirest use HttpClient of HttpAsyncClient

### ISSUE THREAD

**Issue by gaocan1992** [Kong/unirest-java#244]
I found in Unirest documentation said you can set 
```
Unirest.setHttpClient(httpClient);
Unirest.setAsyncHttpClient(asyncHttpClient);
```
Do we know which http client is used when we make http call.
Or the Unirest automatically chooses one of them?

**Comment by ryber** [comment]
the async client is used with the async named methods at the end of the chain (e.g. ```asStringAsync()```)
