### ISSUE TITLE
can i use Unirest(java) by creating a instance instead of using Class static method

### ISSUE THREAD

**Issue by xushunke** [Kong/unirest-java#245]
I do not want other developers sharing the same classLoader with me have access 2 change my Unirest config

**Comment by ryber** [comment]
OpenUnirest has this feature

https://github.com/OpenUnirest/unirest-java/

You can either new up a "UnirestInstance" or get one from a factory method off of Unirest to get one. Also the entire chain is now made of interfaces so it's easier to mock and test with

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
