### ISSUE TITLE
PUT request as binary data

### ISSUE THREAD

**Issue by bbehling-trimble** [Kong/unirest-java#248]
Is it possible using this library to make a PUT request using binary data as the body?

The server accepting the request does not accept a multi-part upload, not does it accept form-data params.

**Comment by ryber** [comment]
There is a method to post the body as a byte array. That's about as close as it gets:

```
Unirest.put("http://somewhere")
                .body("abc".getBytes())
```

So you could dump a while file in that way as long as you have enough memory to do that.

It would be possible to add a method for the body being an InputStream which would be better. ir even taking a file, but you should note that without the header parts of the MultiPart you would probably need to transmit that as part of the Content-Type.

In any case it's not happening in this project as it's abandoned. Feel free to open a issue at OpenUnirest if you still need this feature https://github.com/OpenUnirest/unirest-java/
