### ISSUE TITLE
Error : javax.net.ssl.SSLHandshakeException after adding amazon WAF(firewall)

### ISSUE THREAD

**Issue by ashwingm66** [Kong/unirest-java#251]
In one of the services in my code, I am calling a 3rd party server to fetch the details (I am using Unirest to connect to the server and get the response). This process used to work fine till they added WAF(firewall) in the server. After enabling WAF in server, I am getting handshake failure exception error.

javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I did some research and was able to fix the issue by adding CA certificate into truststore of server by using below command.

sudo keytool -importcert -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass changeit -file <filepath in instance> -alias “<Required name>”

Just to verify , I asked them to remove the firewall and tested with same certificate it worked.

Question : Why did it fail when WAF(firewall) was added in server which was not failing before?

Note : Before and after adding WAF(firewall), certificates were same.

Unirest version : 1.4.9 ; Java version : 1.8

Thanks in advance.

**Comment by ryber** [comment]
It's possible that the firewall  has a intermediate cert that is sniffing packets for security reasons. Doesn't really have anything to do with unirest specifically. You would have had the same issue with literally any Java (and possibly other languages) network clients.
