### ISSUE TITLE
Call for maintainers !

### ISSUE THREAD

**Issue by subnetmarco** [Kong/unirest-java#252]
Hello,

This is Marco. We have a renewed interest to keep building and supporting Unirest-Java moving forward, but we are looking for contributors that would want to become official maintainers and:

* Create a framework/process to submit and accept contributions
* Groom issues and pull requests
* Bring the project back to 2019! 🌟

Please feel free to comment below if you are interested in being part of this project.

-- Marco

**Comment by rnc** [comment]
I believe @ryber is already maintaining a new fork at https://github.com/OpenUnirest/unirest-java

**Comment by subnetmarco** [comment]
Thanks @rnc - Hi @ryber, would you be interested?

**Comment by ryber** [comment]
OpenUnirest has diverted quite a lot from original unirest-java but it's still a fork (though not officially) and could be merged back.

I'd be quite open to doing so if you would like to discuss. Just take a look at the repo, it's history and the issues history. (https://github.com/OpenUnirest/unirest-java/blob/master/CHANGELOG.md) Some of the highlights (IMO) include:

1. Multiple configs possible 
1. Lots of functional interfaces for lambdas
1. Full native support for JSON-Patch
1. the project is moving towards a modular system where Apache will be one option for the backend processor in addition to others (primarily the Java-9 native client)

If you like we could get together on a call or something to discuss (I'm also @ryber on twitter)

**Comment by subnetmarco** [comment]
Happy to announce @ryber as a new official maintainer for Unirest-Java! 💥
