### ISSUE TITLE
Does unirest support other request methods like PROPFIND, VIEW, LINK ?

### ISSUE THREAD

**Issue by ShreyShah70966** [Kong/unirest-java#253]
Hello
I added Unirest.customMethod() in the code for VIEW request but it doesn't seem to be working. Is there any workaround in unirest to support methods other than the six listed in the docs ?

**Comment by ryber** [comment]
We are preparing a new version which does support this. Stay tuned it should be soon. If you need it today the OpenUnirest project which will be merged into this one supports it https://github.com/OpenUnirest/unirest-java

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
