### ISSUE TITLE
Is it ok to copy the contents of the README.md for an unofficial implementation of unirest?

### ISSUE THREAD

**Issue by palash25** [Kong/unirest-java#254]
Hi :wave: I have implemented the unirest protocol in Golang. I just wanted to know whether I can copy the contents of this README that describe the features of the protocol (I don't know much about licences so I wanted to make sure not to violate any such licences)

Also can the logo be used by unofficial implementations of the protocol?

**Comment by ryber** [comment]
I believe the readme, like the rest of the code, is MIT licensed, so you can do with it what you will under the responsibilities of that license. That includes the graphic with the name if that is you are referring to as a logo. If you mean the Gorilla logo of Kong, then no, that is not part of this library and is the logo of a private company
