### ISSUE TITLE
Merge OpenUnirest/unirest-java into Kong/unirest-java

### ISSUE THREAD

**Issue by ryber** [Kong/unirest-java#255]
This is a issue for the merge.

Some prework to do:

- [x] Change copyright/license headers to Kong
- [x] Move Namespace back to Kong
- [x] Figure out releasing
- [x] Modularize the repo and move the official object mappers into it. All official mappers will relaese lock-step with unirest-java
- [x] Remove deprecated methods
- [x] Hide remaining places where Apache Http Client leaks out
- [x] Add a Apache module as the default

I'll take care of most of this in the Kong branch https://github.com/OpenUnirest/unirest-java/tree/kong

OpenUnirest will continue to get security patched for 1 year after the merge and then will be archived.

**Comment by ryber** [comment]
@subnetmarco do you have a preference on package namespace? OpenUnirest took a page from the Java Spark project and used just "unirest". There are enough differences I going forward I think we should go a little different than that to avoid conflict. "kong.unirest" might be fine. "com.kong.unirest" if you want to keep it old school.

**Comment by subnetmarco** [comment]
‘kong.unirest’ works for me

**Comment by ryber** [comment]
PR now in place https://github.com/Kong/unirest-java/pull/256

@subnetmarco If you want to use the Sonatype OSSRH process for releasing to maven central the guide is here: https://central.sonatype.org/pages/ossrh-guide.html 

In order release to the com.kong package it will need to be done by someone with a kong.com (actually should it be konghq?) As part of that process you can specify other sonatype users to be able to release. My sonatype username is "ryber".

**Comment by ryber** [comment]
@subnetmarco if you want to hook me up with a tmp konghq email address I could get it all set up

**Comment by subnetmarco** [comment]
@ryber what's your Jira username?

**Comment by ryber** [comment]
@subnetmarco it's ryber

**Comment by subnetmarco** [comment]
Opened up a ticket to start new project under the new group ID: https://issues.sonatype.org/browse/OSSRH-46684

**Comment by subnetmarco** [comment]
As per https://central.sonatype.org/pages/choosing-your-coordinates.html I had to change the groupId to `com.konghq`

**Comment by subnetmarco** [comment]
@ryber as per [last comment](https://issues.sonatype.org/browse/OSSRH-46684) on JIRA, we need to promote the first release. It's unclear to me if you can also do it, since you are listed as a Contributor. Want to give it a try?

**Comment by ryber** [comment]
I'll give it a shot

**Comment by ryber** [comment]
No, it failed with:

```
INFO] [INFO]  * Remote staging into staging profile ID "9f6fc3011e5cde"
[INFO] [ERROR] Remote staging finished with a failure: 403 - Forbidden
[INFO] [ERROR] 
[INFO] [ERROR] Possible causes of 403 Forbidden:
[INFO] [ERROR]  * you have no permissions to stage against profile with ID "9f6fc3011e5cde"? Get to Nexus admin...
```

You could ask them if I'm supposed to be able to do it. You could also possibly do it. Everything on the "kong" branch is ready to go. I figured we would release from the branch and wait to merge it for everything to be showing up in maven alright (takes about a day for the UI to update)

**Comment by subnetmarco** [comment]
`mvn test` currently generates an error:

```shell
Running BehaviorTests.CallbackFutureTest
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec <<< FAILURE!
onFailure(BehaviorTests.CallbackFutureTest)  Time elapsed: 0.008 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[java.net.ConnectException: Connection refu]sed> but was:<[org.apache.http.ConnectionClosedException: Connection clo]sed>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at BehaviorTests.BddTest.assertFailed(BddTest.java:70)
	at BehaviorTests.CallbackFutureTest.onFailure(CallbackFutureTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)

Running BehaviorTests.TimeoutTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 sec
Running BehaviorTests.InterceptorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
[Thread-372] INFO spark.embeddedserver.jetty.EmbeddedJettyServer - >>> Spark shutting down ...

Results :

Failed tests:   onFailure(BehaviorTests.CallbackFutureTest): expected:<[java.net.ConnectException: Connection refu]sed> but was:<[org.apache.http.ConnectionClosedException: Connection clo]sed>

Tests run: 212, Failures: 1, Errors: 0, Skipped: 4
```

**Comment by ryber** [comment]
hrm, looking at that test. It's always been a bit weird. you might be able to return a connection to localhost:0000 (which you would think wouldn't work but 🤷‍♂️ 

I disabled the test for now

**Comment by ryber** [comment]
@subnetmarco I pushed in a @Ignore for that test for now.

**Comment by subnetmarco** [comment]
I have uploaded the snapshot - @ryber can you verify that now you have permissions to move forward?

**Comment by ryber** [comment]
I don't seem to. I think you need to comment on the issue and let them know the snapshot is up. I've done this several times recently for real-job and found that I was always able to do a full deploy (which is what that "./deploy" script in the root does.) in any case I commented on the issue

**Comment by ryber** [comment]
We have liftoff https://repo.maven.apache.org/maven2/com/konghq/unirest-java/
