### ISSUE TITLE
java.lang.NoClassDefFoundError only when running compiled JAR

### ISSUE THREAD

**Issue by callitkarma67** [Kong/unirest-java#257]
After building with Maven to a JAR, I am receiving:
Exception in thread "main" java.lang.NoClassDefFoundError: com/mashape/unirest/http/Unirest Caused by: java.lang.ClassNotFoundException: com.mashape.unirest.http.Unirest.

The program only does a GET via `Unirest.get(url).asJson();`

I imported all required dependencies (Maven method) as installation section showed. The program runs fine when run in IntelliJ, but if I run the .jar, I get the above error. Here is my full pom.xml dependencies. Are any of the other dependencies known to be conflicting in any way?
```
<dependencies>
    <dependency>
        <groupId>com.mashape.unirest</groupId>
        <artifactId>unirest-java</artifactId>
        <version>1.4.9</version>
    </dependency>
    <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpclient</artifactId>
        <version>4.3.6</version>
    </dependency>
    <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpasyncclient</artifactId>
        <version>4.0.2</version>
    </dependency>
    <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpmime</artifactId>
        <version>4.3.6</version>
    </dependency>
    <dependency>
        <groupId>org.json</groupId>
        <artifactId>json</artifactId>
        <version>20140107</version>
    </dependency>
    <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpcore</artifactId>
        <version>4.4.11</version>
    </dependency>
    <dependency>
        <groupId>commons-logging</groupId>
        <artifactId>commons-logging</artifactId>
        <version>1.2</version>
    </dependency>
    <dependency>
        <groupId>org.apache.httpcomponents</groupId>
        <artifactId>httpcore-nio</artifactId>
        <version>4.4.11</version>
    </dependency>
    <dependency>
        <groupId>org.hibernate</groupId>
        <artifactId>hibernate-agroal</artifactId>
        <version>5.3.8.Final</version>
        <type>pom</type>
    </dependency>
    <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>5.1.6</version>
    </dependency>
    <dependency>
        <groupId>javax.mail</groupId>
        <artifactId>mail</artifactId>
        <version>1.4</version>
    </dependency>
    <dependency>
        <groupId>log4j</groupId>
        <artifactId>log4j</artifactId>
        <version>1.2.17</version>
    </dependency>
</dependencies>
```

**Comment by ryber** [comment]
What do you mean by "when I run the jar". Are you importing the classpath when you do that? dependencies are not, by default, built into a jar like they are for a war.

You could make a shaded jar that includes them all inside the jar. or execute defining the classpath with your maven repo,

Also you don't need to include all the sub-dependencies as direct dependencies because maven will do that for you

**Comment by callitkarma67** [comment]
I was importing the classpath, using a shaded jar was causing issues with log4j, even when explicitly excluding it from the shaded jar. I decided to use Spring Boot for my project and it worked instantly. I'm moving to close this issue as it very likely is not actually related to Unirest. Thanks a ton for your response and Unirest itself.
