### ISSUE TITLE
JSONResponse.getRawBody() method

### ISSUE THREAD

**Issue by melloware** [Kong/unirest-java#258]
I was using the other project Open Unirest because it fixed a lot of issues with this project.  I see now that this has all been updated and merged back into this project.  GREAT!

However one thing I am missing is if JSONResponse gets a parse failure I use to be able to do response.getRawBody() to get the raw contents of the response so I could debug problems or why the JSON payload was invalid.  

Any chance of adding this feature back into JSONResponse?

**Comment by ryber** [comment]
Let me take a look, there were some serious problems with any of the "getRaw***" but I think there is an opportunity to retain the body as a string

**Comment by melloware** [comment]
I can live with a string just something so we can debug.  Maybe only populate that string IF the JSON parsing fails to save memory.

**Comment by ryber** [comment]
I was thinking of keeping it on that exception object with the parse error. Would that work?

**Comment by melloware** [comment]
That would be awesome.  Exactly what I want.

**Comment by ryber** [comment]
Apparently I already put it there. lol. Check it out:

https://github.com/Kong/unirest-java/blob/master/unirest/src/test/java/BehaviorTests/AsObjectTest.java#L101

**Comment by melloware** [comment]
Excellent did not see that!
