### ISSUE TITLE
Make all background threads daemons so the JVM can shut down without an explicit shutdown call

### ISSUE THREAD

**Issue by PapaCharlie** [Kong/unirest-java#259]
Depending on the environment, it may not be straightforward to know when to shut down the `Unirest` instance, which makes this API very difficult to use effectively.

If we made all of the background threads created by `Unirest` daemons (`setDaemon(true)`), it should have no effect at runtime, but should allow the JVM to shut down without explicitly calling the `.shutdown()` method.

I would be ok with this feature being off by default and exposing something like `Unirest.setDaemon()` so that it can be called at application startup

**Comment by ryber** [comment]
I'm open to this but I'm not sure what the advantage of it is. When the JVM exists, unless you have registered a shutdown hook for Unirest it will 

1. shut down all worker threads, which will in turn shut down any user threads spawned by them that are not daemons.
1. Shut down the daemon threads only after all users are down.

In both cases finally blocks are excluded, and so something that is I/O heavy (like Unirest) has the potential to cause a problem.

You can easily register Unirest with the JVM for an explicit shutdown with something like this:

```
Runtime.getRuntime().addShutdownHook(new Thread(() -> Unirest.shutDown(true)));
```

I think a better solution would be to allow Unirest to auto register itself with the hooks? May like:

```
Unirest.config().registerShutdownHook()
```


Another problem is that Unirest is not itself responsible for all the threads. Many come from Apache Http Client and I do not believe we neccessarily have the ability to make it's threads daemons.

**Comment by ryber** [comment]
added the shutdown hook registry in 2.1.00.
