### ISSUE TITLE
Consider adding a progress listener for Callback

### ISSUE THREAD

**Issue by vincentjames501** [Kong/unirest-java#26]
One thing that would make this library even better is to add a simple progress callback that updates as a request is made.  For POST/PUT/PATCH etc it would be great for this to monitor upload progress, and for GET/DELETE etc it would be great for download progress.  Thoughts?  This is another side note, but it would be nice to include a default callback class that provides stubbed implementations of the callback interface for those who don't wish to provide functionality for some of the methods.

``` java
Future<HttpResponse<JsonNode>> future = Unirest.post("http://httpbin.org/post")
  .header("accept", "application/json")
  .field("param1", "value1")
  .field("param2", "value2")
  .asJsonAsync(new Callback<JsonNode>() {

    public void failed(UnirestException e) {
        System.out.println("The request has failed");
    }

    public void completed(HttpResponse<JsonNode> response) {
         int code = response.getCode();
         Map<String, String> headers = response.getHeaders();
         JsonNode body = response.getBody();
         InputStream rawBody = response.getRawBody();
    }

    public void cancelled() {
        System.out.println("The request has been cancelled");
    }

    public void progress(long current, long total) {
        System.out.println("Progress: " + ((float)current / (float)total));
    }

});
```

**Comment by dewos** [comment]
Hello there. Any news about this?

**Comment by CrushedPixel** [comment]
Such a feature would be incredibly useful right now.

**Comment by NAAVOO** [comment]
Still need this, waitin' 2 years for this feature :smile:

**Comment by pierr3** [comment]
Would be nice to have this.

**Comment by eternia16** [comment]
Would be nice to have this, even still in 2017. 😄

**Comment by ryber** [comment]
Complete in the release which should be in mvn central shortly:

The monitor gets invokes separately for each file and field (inputstreams lack a file name unless explicitly given one. Also on inputstreams the total bytes is a guestimate.

```
Unirest.post("http://someplace")
           .field("myFile", new File("/file/somthing.tar")
           .uploadMonitor((fieldName, fileName, bytesWritten, totalBytes) -> {
                // draw a upload progress bar or something
           })
```
