### ISSUE TITLE
Add basicAuth to the Unirest.config()  

### ISSUE THREAD

**Issue by nek4life** [Kong/unirest-java#260]
I need to set the authentication parameters on every request. It seems this feature is missing from the configuration options. It would be great to not have to retype this for every request to the same service.

**Comment by ryber** [comment]
Done. 2.1.01 will me in mvn central in about 20 minutes. I realized after I deployed it that it has a small bug where you could set 2 default basic auth headers. So I have that patched but I'm looking for something else to throw in a 2.1.02 release. So just don't set it twice or you'll get 2.

Note that setting a basicAuth on a request will override the default config (as is the case with most things in the request).

**Comment by nek4life** [comment]
Holy crap that was fast! Just tried it out and works perfectly! Thanks!
