### ISSUE TITLE
Add asErrorObject() functionality

### ISSUE THREAD

**Issue by Risto-Stevcev** [Kong/unirest-java#262]
**Is your feature request related to a problem? Please describe.**
I like `asObject` as lot but it doesn't provide any way to define the object for an error state. API requests often have a different response shape for errors. I want to be able to serialize both responses and error responses.

**Describe the solution you'd like**
Something like `.asErrorObject`, or alternatively:
```java
.asObject(Class<? extends T> responseClass, Class<? extends E> errorClass)
```
And then HttpResponse would have a second generic for the error class: `HttpResponse<T, E>` which would default to the same type if unspecified (T = E)

**Describe alternatives you've considered**
The functional version of `.asObject` with a custom sum type is a doable workaround but it's verbose

**Comment by ryber** [comment]
Hi, thanks for the issues.

this kind of assumes that the response format for an error will be the same format as a success (so, for example JSON).

My personal experience is that this doesn't happen a lot. Often errors, particularly 500's, are just strings. 

We also need to deal with the fact that Java doesn't have a good implementation of Either (there are ones, they just aren't good)

What if we, leveraging #261 added a overload to the ifFailture method to take a type for the mapper so:

```
HttpResponse<T> ifFailure(Class<E> errorClass, Consumer<HttpResponse<E>> consumer);
```

WIth an implementation like:

```
Unirest.get("http://someplace")
                .asObject(MainThing.class)
                .ifFailure(ErrorClass.class, c -> {
                    // do something with a HttpResponse<ErrorClass>
                });
```

?

**Comment by ryber** [comment]
originally I didn't think this would fit well within the internal generics of Unirest (which is kind of complicated), but in fact I did get it to work as you asked. Need to still add a async version and some more tests and docs before a release

**Comment by ryber** [comment]
Well, it worked ok for the simplest use case but for async and further chaining it just wasn't working well. Instead I added a couple of post-request methods on the response. These seem to work a lot better and I think achieve the goal:

```java
ErrorThing error = Unirest.get("http://someplace")
                .asObject(Thing.class)
                .mapError(ErrorThing.class); // will be null if the request had been successful

Unirest.get("http://someplace")
                .asObject(Thing.class)
                .ifFailure(ErrorThing.class, f -> {
                    // f is a HttpResponse<ErrorThing> 
                    // this function is not called if the request was succesful
                }); 

```
 2.2.02 should be in mvn central in about 20 minutes

**Comment by Risto-Stevcev** [comment]
Yeah I think you're right, the `mapError` solution is simpler and not really any less safer. Using an either-like thing would've worked better if java had some kind of pattern matching, but it doesn't so the caller is still forced to handle the cases

**Comment by ryber** [comment]
They're thinking about it (https://cr.openjdk.java.net/~briangoetz/amber/pattern-match.html) Once/if that ever becomes real maybe it will be possible.
