### ISSUE TITLE
Where should Unirest.shutdown() be called in a webapp?

### ISSUE THREAD

**Issue by theyuv** [Kong/unirest-java#267]
I am using Unirest to make some REST API calls in a Java webapp.

Should I call `Unirest.shutdown()` once I'm done with the `HttpResponse`?
For example:
```
HttpResponse<String> response;
try {
            response = Unirest.post(url)
                    .header(...)
                    .body(requestBody)
                    .asString();
        } catch (UnirestException e) {
            ...
        } finally {
            try {
                Unirest.shutdown();
            } catch (IOException e) {
                ...
            }
        }
```

Or upon undeploying the application?

Or somewhere else?

Where should I call `Unirest.shutdown()`?

Version: 1.4.9

Thank you.

**Comment by ryber** [comment]
You would typically wire that into a shutdown hook in your webapp. You definitely would NOT want to do it after each request.

You can add something like this to your init (you should only do this once):
```
 Runtime.getRuntime().addShutdownHook(new Thread(Unirest::shutDown));
```

Alternatively in your init you can call this config option and Unirest will add itself to the hooks 
``` 
Unirest.config().addShutdownHook(true);
```

**Comment by theyuv** [comment]
Thanks!

Rather than adding the hook upon init of the webapp, I can just call `Unirest.shutdown()` explicitly upon shutting down (ie: `contextDestroyed`).

Is that ok?

(I can also hook into init like you suggested and call `Unirest.config().addShutdownHook(true);`

**Comment by ryber** [comment]
yea you can do that there as well

If you can't find the config() method it might be because you are using the old mashape Unirest and you need to upgrade. I highly recommend you do because the mashape version has some thread leaking https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md

**Comment by theyuv** [comment]
Hey, thanks again.

Yes, I noticed that now too. A google search took me to the old mashape Unirest. I see now that the new one is under group: konghq.

**Comment by theyuv** [comment]
I upgraded and upon initializing (in the `contextInitialized` method), I called:
`Unirest.config().addShutdownHook(true);` 

I still got the warning of possible memory leak.

When I hooked into `contextDestroyed `and called `Unirest.shutdown()` explicitly, it worked (ie: I didn't get a warning about memory leaks).

**Comment by ryber** [comment]
The timing of the shutdown hook is a little funky and any interaction before could make it not take. I'm going to turn this into an issue to address that, but in any case it sounds like you got it working

**Comment by theyuv** [comment]
Ok, thanks.
I'm don't quite understand what you mean by "any interaction before could make it not take". Do you mean any use of Unirest before `.addShutdownHook()` is called? I didn't make any use of Unirest before this hook was called to the best of my knowledge.

**Comment by ryber** [comment]
Init of the actual client engine is lazy and some of the configs only apply at the time of construction, so if you did something that might cause the construction before you called the config, it might not take. IDK if this happened in your case or if perhaps your framework did something to the hook or what.
