### ISSUE TITLE
Create better docs

### ISSUE THREAD

**Issue by ryber** [Kong/unirest-java#269]
Add more comprehensive documentation by generating it using git pages. 

Inspiration: Java Sparks docs: http://sparkjava.com/documentation

**Comment by viragumathe5** [comment]
Will you please elaborate the issue

**Comment by ryber** [comment]
It's just a reminder for me. I've been updating the new docs here: http://kong.github.io/unirest-java/

**Comment by rnc** [comment]
@ryber I think the links in https://kong.github.io/unirest-java/ to upgrade guide and changelog are broken.

**Comment by ryber** [comment]
thanks @rnc, fixed

**Comment by ryber** [comment]
It's much better now, also pointed old Unirest website to new docs. http://kong.github.io/unirest-java/
