### ISSUE TITLE
Support HTTP/2

### ISSUE THREAD

**Issue by ryber** [Kong/unirest-java#271]
**Is your feature request related to a problem? Please describe.**
I need to call a service in HTTP/2

**Describe the solution you'd like**
Support HTTP/2

**Describe alternatives you've considered**
Other libraries that support HTTP/2

**Comment by ryber** [comment]
This will require moving to Apache HttpClient 5

**Comment by ryber** [comment]
this is complete in 4.0.0-RC1 and will be finally released with 4.0.0

**Comment by suchorski** [comment]
how to use that?
`The method httpClient(Client) in the type Config is not applicable for the arguments (CloseableHttpAsyncClient)Java(67108979)`

**Comment by ryber** [comment]
correct, the RF version does not support Apache

**Comment by suchorski** [comment]
So, how to? Can you give a help? Thanks
