### ISSUE TITLE
Multiple Proxies

### ISSUE THREAD

**Issue by Chazza** [Kong/unirest-java#274]
Hi there,

There doesn't seem to be a way to have multiple proxies, I've tried to use multiple configs and then switch but doesn't seem to be what I'm looking for.

Thanks

**Comment by ryber** [comment]
Hi! 
   In addition to multiple configs you can pass in proxies on a per-request basis: 
https://github.com/Kong/unirest-java/blob/master/unirest/src/test/java/BehaviorTests/ProxyTest.java#L75-L85

Would that work for you? If not what would?

**Comment by Chazza** [comment]
Hi there,

I did see Unirest.request(method, url).proxy() however this only supports non proxy authentication.

Is it possible such could be implemented?

Thank you.

**Comment by ryber** [comment]
yea, so Unirest is simply a wrapper for Apache Http Client and this is an area where Apache doesn't have a simple solution. Authentication for proxies is on a per-route basis and must be configured in the client and not on the request (this is expensive).

It gets complicated fast, and that complexity would leak out to the Unirest users. I can poke around some more and give it some thought but I think your fastest solution would be to configure your own Http Client. Unfortunately this is a very painful area to work with in Apache.

One question I have is, how are you using multiple proxies? are these proxies chained? Or are they different per route? or something else?

**Comment by Chazza** [comment]
Thanks for the quick reply!

Basically I’m building an application where users enter a bunch of proxies into a text file, and then the tool calls a bunch of endpoints (these are IP tied, hence proxies).

I’d also like to support a username and password for these, as some providers require this.

Hopefully that makes sense! I’m working on porting this tool from another language in hopes I can compact it, and have better proxy support.

**Comment by ryber** [comment]
So is this some kind of dev or qa tool? If so, and you don't have a high volume of requests in a production environment then I don't think there is anything wrong with creating an entire new config for each one like 

```
       UnirestInstance i = Unirest.spawnInstance()
        i.config().proxy(url, port, username, password);
        i.get(endpoint).asString();
        i.shutDown();
```

I wouldn't recommend this in a production web or thick client application due to the number of resources each request eats up, but you are simply testing a bunch of proxies and routes to see if they are reachable it would be fine. The unit tests for Unirest actually do client creation and teardown constantly.

**Comment by Chazza** [comment]
I'm not sure if it's considered a 'production' tool, however it's a program which checks a string against an API, these APIs are rate limited by IP. Would the above method be fine to use, if we are talking thousands of requests?

Sorry for being a pain, thanks again.

**Comment by ryber** [comment]
NP,
   It's really up to you. Here is the trade-off: A client instance is fairly expensive to create, they have a couple of threads that get spawned (more for the async client). So I tend to recommend you don't do a ton of them but depending on use case it might be fine. As long as you are shutting them down when complete you should be able to manage it fairly well. You can do the above with a try-with-resource like

```
   try(UnirestInstance i = Unirest.spawnInstance()){
        i.config().proxy(url, port, username, password);
        i.get(endpoint).asString();
   }

**Comment by ryber** [comment]
Note that the point I would not recommend this is if you are planning on making a ton of requests to any one particular endpoint. For example if you are using a REST API. creating new clients for each request would perform horribly. Testing routes though is ok.

**Comment by Chazza** [comment]
Appreciate the lengthy reply, yeah I completely understand that. The end user enters a service into their config file, then the tool uses a set of words and calls one endpoint (depending on what they choose).

Would the above still be viable for this? Would this also be fast enough? Speed is also a concern.

On a slightly off topic area, do you have Discord or Skype to talk on? May be easier than through an issue.

Appreciate your time Ryber :)

**Comment by ryber** [comment]
@Chazza we have a Gitter: https://gitter.im/Kong/unirest-java

**Comment by ryber** [comment]
As long as you are using the same instance to make those calls to the same endpoint with the same proxy config before closing it would be quite performant.

**Comment by Chazza** [comment]
So I wouldn’t be able to use a unique config / proxy per call? The endpoint is the same but using different data if that makes sense.

I’ll join the website now also :)

**Comment by ryber** [comment]
Going to close this as I don't think Unirest/Apache are a good fit for this use case. Multiple configs would probably work for most people, this is special. Recommended checking out Feign (https://github.com/OpenFeign) or okhttp (https://github.com/square/okhttp)
