### ISSUE TITLE
Upgrade to Http Java Client and Java 11

### ISSUE THREAD

**Issue by ryber** [Kong/unirest-java#275]
**Is your feature request related to a problem? Please describe.**
Java Http Client will introduce several things we are looking forward to including Http/2 and Websockets. 
This will be a major breaking change

**Comment by FireMasterK** [comment]
Any progress on this? According to https://hc.apache.org/news.html, a GA release of 5.0 was released on 24th February this year. I believe this also means that it is no longer in beta.

**Comment by ryber** [comment]
yea, the problem is, they completely rewrote the async stuff and it is significantly more complicated than it was before. I'm slowly working through it but it's pretty massive and they've made some of the things very very difficult that were easy in 4. I recently started to dedicate some time to it. I hope to have something by thanksgiving, but it's possible we may have to drop some features in async mode.

There a branch https://github.com/Kong/unirest-java/commit/82c906a4dc9cdb00908c56db4122ee322e8fb1dd

**Comment by ryber** [comment]
I'm changing the direction of this issue. I have attempted, several times, to upgrade to 5. the regular client works fine and upgrading was quite easy, but the Async client has gone in a radically different direction and it's patterns do not match up with Unirest. 

There is no effective way to keep Unirest's interfaces the same AND support all use cases, AND use the Apache Http Async Client.

However, there is another way. We can get almost everything we need with the new Java HTTP client build into Java itself. I have a spike going and I believe it should be a much better fit and it allows us to drop the entire Apache dependency chain which should leave Unirest with very few dependencies at all. The one downside is that users would need to be on Java 11. I will continue to maintain the 8 branch with Apache for security and minor enhancements for a while.

**Comment by FireMasterK** [comment]
I'm all in for the idea! I've had pleasant experiences with the Java 11 HTTP client so far 👍.

**Comment by aner-perez** [comment]
I haven't found a way to log the data that is sent/received over the wire for the native Java 11 HTTP client.  With the Apache HTTP client I could turn on DEBUG for "org.apache.http.wire" and see the actual communications.  For some poorly documented REST APIs this logging can be invaluable.  I tried 4.0.0-RC1 but had to move back to 3.11.11 just for this reason.

**Comment by ryber** [comment]
This is compete and we are now in the final release candidates for Unirest4 https://github.com/Kong/unirest-java/discussions/429
