### ISSUE TITLE
ConnectionManager is not created nor updated according to provided configuration

### ISSUE THREAD

**Issue by federicojakimowicz** [Kong/unirest-java#280]
**Describe the bug**
Connection manager does not take into account configuration.

**To Reproduce**
Set up unirest config:
Unirest.config()
.connectTimeout(Integer.parseInt(environment.getProperty(UNIREST_CONNECTION_TIMEOUT)))
.socketTimeout(Integer.parseInt(environment.getProperty(UNIREST_SOCKET_TIMEOUT)))
.concurrency(Integer.parseInt(environment.getProperty(UNIREST_CONNECTION_MAX_TOTAL)),
		Integer.parseInt(environment.getProperty(UNIREST_CONNECTION_MAX_PER_ROUTE)))
.setDefaultHeader(ACCEPT, APPLICATION_JSON_VALUE)
.setDefaultHeader(CONTENT_TYPE, APPLICATION_JSON_VALUE)
.automaticRetries(false)
.reset();

// do something so clients are re generated
HttpResponse<String> response = Unirest.get(URL).asString();

// you can check the connection manager status as
HttpClient httpClient = ((ApacheClient) Unirest.config().getClient()).getClient();
        Field f = httpClient.getClass().getDeclaredField(FIELD_NAME_HTTP_CLIENT);
        f.setAccessible(true);
        PoolingHttpClientConnectionManager poolingHttpClientConnectionManager = (PoolingHttpClientConnectionManager) f.get(httpClient);

**Expected behavior**
Connection manager DOES take into account configuration max connections per route and total.

**Screenshots**
none

**Environmental Data:**
 - Java Version 1.8
 - Version irrelevant

**Additional context**
this is a snippet of your current code:
public ApacheClient(Config config) {
        this.config = config;
        security = new SecurityConfig(config);
        manager = security.createManager();
        syncMonitor = new SyncIdleConnectionMonitorThread(manager);
        syncMonitor.start();

        HttpClientBuilder cb = HttpClients.custom()
                .setDefaultRequestConfig(RequestOptions.toRequestConfig(config))
                .setDefaultCredentialsProvider(toApacheCreds(config.getProxy()))
                .setConnectionManager(manager)
                .useSystemProperties();

        setOptions(cb);
        client = cb.build();
    }
-----
// there is no usage of the provided config in the manager creation
kong.unirest.apache.SecurityConfig

public PoolingHttpClientConnectionManager createManager() {
        return buildSocketFactory()
                .map(PoolingHttpClientConnectionManager::new)
                .orElseGet(PoolingHttpClientConnectionManager::new);
    }

**Comment by ryber** [comment]
Ug, thanks, patch coming in a few minutes

**Comment by ryber** [comment]
2.3.07 should be in maven central in about 20 minutes +/- 20 minutes
