### ISSUE TITLE
Problem version httpclient library

### ISSUE THREAD

**Issue by xabe** [Kong/unirest-java#282]
Describe the bug
Problem with version library httpclient

To Reproduce
Simple, invoke http request

Screenshots
<img width="583" alt="Captura de pantalla 2019-06-24 a las 13 16 52" src="https://user-images.githubusercontent.com/1532559/60017372-e4366700-9688-11e9-8ee6-05c7aa652273.png">
<img width="583" alt="Captura de pantalla 2019-06-24 a las 13 19 08" src="https://user-images.githubusercontent.com/1532559/60017378-e698c100-9688-11e9-8563-c5d7700d3255.png">

Environmental Data:

Java Version 11

Additional context

Fix problem exclude library

<img width="419" alt="Captura de pantalla 2019-06-24 a las 13 27 09" src="https://user-images.githubusercontent.com/1532559/60017394-eac4de80-9688-11e9-9a83-1d52a19d2414.png">

**Comment by xabe** [comment]
Describe the bug
Problem with version library httpclient

To Reproduce
Steps to reproduce the behavior:
Simple, invoke http request

Screenshots
<img width="583" alt="Captura de pantalla 2019-06-24 a las 13 16 52" src="https://user-images.githubusercontent.com/1532559/60015609-345efa80-9684-11e9-9c0c-ce0474eacd6e.png">
<img width="583" alt="Captura de pantalla 2019-06-24 a las 13 19 08" src="https://user-images.githubusercontent.com/1532559/60015632-3c1e9f00-9684-11e9-9a60-bb28495ba6c4.png">




Environmental Data:

    Java Version 11

Additional context

Fix problem exclude library

<img width="419" alt="Captura de pantalla 2019-06-24 a las 13 27 09" src="https://user-images.githubusercontent.com/1532559/60015661-4b9de800-9684-11e9-865d-260b427c0450.png">

**Comment by ryber** [comment]
Apache HttpClient is a popular library and in this case, I think if you looked at your full tree 4.5.5 is being pulled in by some dependency BEFORE and overriding the one Unirest wants. You can see from the official maven analysis that 4.5.9 is the required version https://mvnrepository.com/artifact/com.konghq/unirest-java/2.3.07

Also here:
<img width="871" alt="unirest" src="https://user-images.githubusercontent.com/145359/60018185-458e1400-9650-11e9-84ec-4102c5ffd855.png">

You can probably see more details on what maven is doing by doing a verbose tree (mvn dependency:tree -Dverbose)

In any case your fix is the correct one. You can also use the standalone jar that shades it's version of Apache Http Client:

```xml
<dependency>
    <groupId>com.konghq</groupId>
    <artifactId>unirest-java</artifactId>
    <version>2.3.07</version>
    <classifier>standalone</classifier>
</dependency>
```

**Comment by xabe** [comment]
Hi @ryber 

To have no problem with the versions apache httpclient, It is remove dependency httpclient and core from httpasyncclient, eliminate problems duplicate and conflict

<img width="914" alt="Captura de pantalla 2019-06-24 a las 14 34 36" src="https://user-images.githubusercontent.com/1532559/60019212-a6880d00-968d-11e9-905b-e733bc898585.png">

Regards

**Comment by ryber** [comment]
thats...weird, maven should be picking the version of httpclient that is closer to the left. I'm going to cut a version excluding client and core from async which should force it

**Comment by ryber** [comment]
2.3.08 should be in mvn central in about 10-20 minutes. If you could, try it out and let me know if that fixed it for you.

Also, what version of maven are you running?

**Comment by xabe** [comment]
Hi @ryber 

I use maven 3.5.4

<img width="914" alt="Captura de pantalla 2019-06-24 a las 15 24 25" src="https://user-images.githubusercontent.com/1532559/60022495-3df05e80-9694-11e9-8d9c-a210ce34ce0a.png">

**Comment by xabe** [comment]
Work it
