### ISSUE TITLE
Custom Apache HttpClient configuration is overridden (v2.0.05+)

### ISSUE THREAD

**Issue by elusiveeagle** [Kong/unirest-java#284]
**Describe the bug**
After configuring a custom Apache HttpClient for use with Unirest, the request configuration, `User-Agent` request header, and `Accept-Encoding` request header are set to default values. In other words, parts of the custom client's configuration are overridden by Unirest. There isn't an easy way to workaround this issue because it's not possible to configure Unirest timeouts after setting a custom client.

There are some other minor bugs. Most of these can be seen in the debug log output below and are located in [`RequestPrep`](https://github.com/Kong/unirest-java/blob/master/unirest/src/main/java/kong/unirest/apache/RequestPrep.java).
- The `Content-Type` request header is [not capitalized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type)
- The `User-Agent` request header is [not capitalized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent)
- The `User-Agent` request header value is hard-coded to Unirest version `3.0.00` (`unirest-java/3.0.00`)
- The `Accept-Encoding` request header is [not capitalized](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding)

**To Reproduce**

1. **Configure Unirest to use a custom, initialized Apache HttpClient.** In our code below, we have a custom `HttpClientBuilder` class that returns a `CloseableHttpClient` that we pass to `Unirest.config().httpClient()`. As you can see, this custom client has our desired user agent string, SSL configuration, and connect/socket timeout configuration.

```java
    Unirest.config().httpClient(HttpClientBuilder.create(userAgent, this.trusting)
                                  .connectTimeout(this.connectTimeout)
                                  .socketTimeout(this.socketTimeout)
                                  .build());
```

2. **Make a request with Unirest and observe it using default timeouts.** Here you can see that a custom socket timeout of 15 seconds is being set back to the default of 60 seconds in the [Apache HttpClient debug logs](https://hc.apache.org/httpcomponents-client-4.5.x/logging.html):

```
2019/06/26 12:14:40:998 PDT [DEBUG] RequestAddCookies - Cookie [version: 0][name: JSESSIONID][value: <session-id>][domain: <hostname>][path: /api][expiry: null] match [(secure)<hostname>:443/api/v1/status]
2019/06/26 12:14:40:998 PDT [DEBUG] RequestAddCookies - Cookie [version: 0][name: localeId][value: en][domain: <hostname>][path: /][expiry: Tue Jun 21 12:14:40 PDT 2039] match [(secure)<hostname>:443/api/v1/status]
2019/06/26 12:14:40:998 PDT [DEBUG] RequestAuthCache - Auth cache not set in the context
2019/06/26 12:14:40:998 PDT [DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://<hostname>:443][total kept alive: 1; route allocated: 1 of 10; total allocated: 1 of 50]
2019/06/26 12:14:40:998 PDT [DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://<hostname>:443][total kept alive: 0; route allocated: 1 of 10; total allocated: 1 of 50]
2019/06/26 12:14:41:013 PDT [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 15000
2019/06/26 12:14:41:013 PDT [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 60000
2019/06/26 12:14:41:013 PDT [DEBUG] MainClientExec - Executing request GET /api/v1/status HTTP/1.1
2019/06/26 12:14:41:013 PDT [DEBUG] MainClientExec - Target auth state: UNCHALLENGED
2019/06/26 12:14:41:013 PDT [DEBUG] MainClientExec - Proxy auth state: UNCHALLENGED
2019/06/26 12:14:41:013 PDT [DEBUG] headers - http-outgoing-0 >> GET /api/v1/status HTTP/1.1
2019/06/26 12:14:41:013 PDT [DEBUG] headers - http-outgoing-0 >> Accept: application/json
2019/06/26 12:14:41:013 PDT [DEBUG] headers - http-outgoing-0 >> user-agent: unirest-java/3.0.00
2019/06/26 12:14:41:013 PDT [DEBUG] headers - http-outgoing-0 >> accept-encoding: gzip
2019/06/26 12:14:41:013 PDT [DEBUG] headers - http-outgoing-0 >> Host: <hostname>:443
2019/06/26 12:14:41:013 PDT [DEBUG] headers - http-outgoing-0 >> Connection: Keep-Alive
2019/06/26 12:14:41:013 PDT [DEBUG] headers - http-outgoing-0 >> Cookie: JSESSIONID=<session-id>; localeId=en
2019/06/26 12:14:41:123 PDT [DEBUG] headers - http-outgoing-0 << HTTP/1.1 200 OK
2019/06/26 12:14:41:123 PDT [DEBUG] headers - http-outgoing-0 << Strict-Transport-Security: max-age=31622400; includeSubDomains
2019/06/26 12:14:41:123 PDT [DEBUG] headers - http-outgoing-0 << Content-Type: application/json
2019/06/26 12:14:41:123 PDT [DEBUG] headers - http-outgoing-0 << Transfer-Encoding: chunked
2019/06/26 12:14:41:123 PDT [DEBUG] headers - http-outgoing-0 << Date: Wed, 26 Jun 2019 19:14:40 GMT
2019/06/26 12:14:41:123 PDT [DEBUG] headers - http-outgoing-0 << Server: <server>
2019/06/26 12:14:41:123 PDT [DEBUG] MainClientExec - Connection can be kept alive indefinitely
2019/06/26 12:14:41:123 PDT [DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://<hostname>:443] can be kept alive indefinitely
2019/06/26 12:14:41:123 PDT [DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 0
2019/06/26 12:14:41:123 PDT [DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://<hostname>:443][total kept alive: 1; route allocated: 1 of 10; total allocated: 1 of 50]
2019/06/26 12:14:41:123 PDT [DEBUG] MainClientExec - Cancelling request execution
```

After diving into the Unirest code, I can see that the cause is the logic in the [`RequestPrep.getHttpRequestBase()`](https://github.com/Kong/unirest-java/blob/master/unirest/src/main/java/kong/unirest/apache/RequestPrep.java#L77) method. The `User-Agent` and `Accept-Encoding` request headers are overridden on lines 78-83 because they don't first check for any existing custom client values.
```java
        if (!request.getHeaders().containsKey(USER_AGENT_HEADER)) {
            request.header(USER_AGENT_HEADER, USER_AGENT);
        }
        if (!request.getHeaders().containsKey(ACCEPT_ENCODING_HEADER) && config.isRequestCompressionOn()) {
            request.header(ACCEPT_ENCODING_HEADER, "gzip");
        }
```

The client's `RequestConfig` is overridden in this same method on line 89. I looked at this history, and this line was added as part of #118 and the `overrideConfig()` method has been enhanced since. It would seem that a possible resolution would be to make this line conditional based on the lack of a custom client. Alternatively you'd have to check the custom client's value for each `RequestConfig` field set in `overrideConfig()`.
```java
reqObj.setConfig(overrideConfig());
```
Here's a stack trace excerpt, if helpful:
```
overrideConfig:99, RequestPrep (kong.unirest.apache)
getHttpRequestBase:89, RequestPrep (kong.unirest.apache)
prepare:70, RequestPrep (kong.unirest.apache)
request:101, ApacheClient (kong.unirest.apache)
asJson:194, BaseRequest (kong.unirest)
get:465, RestClient (<redacted>)    <-- Our custom REST client that uses Unirest to make requests
```

This overridden `RequestConfig` object from the `overrideConfig()` method is the passed along as requests are executed, which causes the Apache HttpClient to use those values instead of the client's default request configuration.

NOTE: It's possible that there are other places in the Unirest codebase that should be updated to check/account for a custom client.

**Expected behavior**
After configuring a custom Apache HttpClient for use with Unirest, its configuration should be used for Unirest requests.

**Screenshots**
N/A

**Environmental Data:**
 - Java 8
   - Below are my specific dev environment details, but this issue has been reproduced in different Java 8 environments as well.
   ```
   openjdk version "1.8.0_192"
   OpenJDK Runtime Environment (Zulu 8.33.0.1-win64) (build 1.8.0_192-b01)
   OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-win64) (build 25.192-b01, mixed mode)
   ```
 - We are currently using `2.2.02`, but these issues have been around since at least `2.0.05` based on the commit history (https://github.com/Kong/unirest-java/commit/4d21d0c0b00cfea43a7561ff340ea982136b3b48)

Let me know if you have any other questions! Thanks.

**Comment by ryber** [comment]
So, yea, totally OK with fixing this, however, the intent of Unirest is to abstract Apache as much as possible. Why not just configure Unirest itself to do these things and avoid a custom Http Client?

**Comment by elusiveeagle** [comment]
Thanks for the quick reply! And ha, I figured you'd ask! We definitely want to use the 'native' options in Unirest over a custom client if we can. As far as I can recall, when we last looked at doing this, there were several options that Unirest didn't support. Below I've done my best to recall the options we need and look up their current support status, but there may be one or two I'm missing. Feel free to correct me on the support status as needed.

- User agent string: Supported via `setDefaultHeader()` or `addDefaultHeader()`
- Connect timeout: Supported via `connectTimeout()`
- Socket timeout: Supported via `socketTimeout()`
- Max connections: Supported via `concurrency()`
- Max connections per route: Supported via `concurrency()`
- Disable redirect handling: Supported via `followRedirects()`
- Redirect strategy: Unsupported (although this may not be needed)
- Allow use of Java system properties: Supported via `useSystemProperties()`
- Disable TLS validation: Supported via `verifySsl()` (looks like the Unirest implementation *may* work, but we'll need to test)

We also explicitly define a default `SocketConfig` with the socket timeout we want (in addition to the default `RequestConfig`) due to some historical bugs in the HTTP client library. I suppose we could reassess if this is needed, but I know it was an issue in the past.

**Comment by ryber** [comment]
So, I'm mulling over the best way to do this, It's tricky because neither the client, nor the request config, are all encompassing of settings (in true Apache Http Client fashion).  some also come with defaults, so detecting, "is that the default or did someone set it" is tricky. My preference is to provide a way for you to override the request config in addition to the client. Do you think this would work for you?

One other note on your original issue. You noted that several of the headers are not capitalized. This was, per the original Unirest on purpose. The RFC for HTTP states that 
> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive. 
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

While this is the spec, many different systems are somewhat notorious for not following this rule. For example a major identity provider I work with requires the "accept" header to be lowercase. I would have gone with the capitalized version myself but at this point changing it could be a problem (and it's not technically wrong). I have noticed that Jetty will standardize the headers to the cased versions.

**Comment by elusiveeagle** [comment]
I'm currently testing things out on our end using the Unirest options instead of a custom client. If that works, I would be okay you resolving this with 'use as is'.

If you would like to address the main issue (configuration override) or the above attempt fails for some reason, I think your approach would work assuming I understand it correctly. Is it similar to the below?

1. If a custom client is configured for use with Unirest, use its configuration (in my experience, if the custom client doesn't have something set, the library will use its defaults/standard behavior)
1. If Unirest has been configured to override a setting (such as the request socket timeout), use that
1. If a Unirest request has been configured to override a setting, use that (see use of `socketTimeout()` below)
```java
      Unirest.get(baseUrl + "csrf-token")
        .basicAuth(username, password)
        .accept("application/json")
        .socketTimeout(15000)
        .asJson()
```
As for the request header capitalization issue, understood. I noted these were minor because the servers we've used seem to handle lowercase just fine. I was just pointing it out for standardization and consistency.

You may, however, want to adjust the hard-coded value for the `User-Agent` request header to update it with each release of Unirest (unless there was some reason to use `3.0.00`).

**Comment by elusiveeagle** [comment]
Alright, my quick/initial testing using the available Unirest options is somewhat promising, but there are some discrepancies from our custom synchronous client approach:

1. Unirest sets the connection request timeout to the value of the socket timeout versus the library default of `-1`
   * I'm not sure if this will have any real impact...likely not
1. Unirest always uses the `DefaultRedirectStrategy`
   * In other words, the strategy is not configurable
   * Again, probably not an issue
1. Unirest initializes a pooling connection manager for the synchronous client that has no default `SocketConfig` defined
   * As I mentioned above, we have used this to account for some historical bug(s) in the library which may or may not be needed anymore
   * I noticed in the client debug logs that the socket timeout was first set to `0` before being set to the configured value, so it *seems* like a defined `SocketConfig` may not be needed since the correct value gets set before the request is made...
1. Unirest **ignores** the configured concurrency settings (the total and per route maximum connections for its synchronous client's connection manager) which results in the library's default of 20 total connections with 2 max per route being used
   * Is this intentional?
   * I can provide more detail here if needed, but I held off in case you wanted me to open a new issue for this

As always, let me know if you have any questions. Thanks!

**Comment by ryber** [comment]
@elusiveeagle I believe the concurrency settings bug was fixed 2.3.07 see #280
If you are still seeing that it's not taking for some reason I can reopen that

**Comment by elusiveeagle** [comment]
@ryber Ah, yes. Thanks. That should do it. I'll try after using the latest version (had been testing with `2.2.02` still).

**Comment by elusiveeagle** [comment]
@ryber Just to circle back: Using Unirest `3.3.08` and the available `Config` options has been successful so far.

It would probably still be good to fix this issue for any others that may be impacted. At this time, however, we feel pretty confident in this alternative approach. Thanks!

**Comment by ryber** [comment]
In 2.3.09 I've added the ability to override the RequestConfig factory (see http://kong.github.io/unirest-java/#configuration)

This would in theory give those who want it full control over the Apache config.
