### ISSUE TITLE
Docs and Jackson Mapper

### ISSUE THREAD

**Issue by abdulwahabO** [Kong/unirest-java#290]
The docs don't mention that the Jackson object mapper is in a separate artifact which needs to be included as a dependency before that mapper can be used. Same for Gson.

**Comment by ryber** [comment]
Hi, question, which part of the doc were you looking at because the extra dependencies are listed here: http://kong.github.io/unirest-java/#configuration

**Comment by abdulwahabO** [comment]
I was here http://kong.github.io/unirest-java/#requests. I missed the 'Object Mappers' link, my bad. Will close this.

**Comment by ryber** [comment]
Oh, no  problem, I'll include a link in the request to the more detailed Object Mapper part.
