### ISSUE TITLE
Unirest fails downloading correct sitemap.xml.gz

### ISSUE THREAD

**Issue by Chaiavi** [Kong/unirest-java#296]
**Describe the bug**
Scenario:
Attempting to download a [gz sitemap from google](https://play.google.com/sitemaps/play_sitemaps_2019-07-30_1564545704-00000-of-64582.xml.gz)

**To Reproduce**
Here is my simple code
`Unirest.config().followRedirects(true).verifySsl(false);`
`HttpResponse<String> response = Unirest.get(urlStr).asString();`

    `byte[] content = response.getBody().getBytes();
    Map<String, List<String>> metaData = Maps.newHashMap();
    Headers headers = response.getHeaders();
    for (Header header: headers.all()) {
      metaData.put(header.getName(), headers.get(header.getName()));
    }

    return new FetchResult(response.getStatus(), headers.getFirst("content-type"), content, metaData);`

**Expected behavior**
Should download a parsable compressed file (by 7zip for example)

**Additional context**
From looking at the code, I assume there is a problem there when getting the response as a string then converting it back to bytes ?

**Comment by ryber** [comment]
hi @Chaiavi I would not expect this to work. A binary file is not a string and would never convert properly.

Unirest has methods for downloading binary files. I just tested it with the file you linked to and it worked fine:

```
Unirest.get("https://play.google.com/sitemaps/play_sitemaps_2019-07-30_1564545704-00000-of-64582.xml.gz")
                .asFile("/some/path/play_sitemaps_2019-07-30_1564545704-00000-of-64582.xml.gz");
```

http://kong.github.io/unirest-java/#file-responses

**Comment by Chaiavi** [comment]
Thanks @ryber , but just to make sure I understand

I must save the response to disk in order to download binary ?
Is there a way just to get the bytes without passing through disk?

**Comment by ryber** [comment]
Ah, I was just about to update about that. Yes, but you need to use the consumer methods to directly access the InputStream:

https://github.com/Kong/unirest-java/blob/master/unirest/src/test/java/BehaviorTests/ConsumerTest.java#L93-L107

**Comment by Chaiavi** [comment]
Thank you very much @ryber - This is what I needed (I thought there was asBinary() )
