### ISSUE TITLE
Upgrade guide improvements 

### ISSUE THREAD

**Issue by rnc** [Kong/unirest-java#304]
**Describe the bug**
I think it would very useful if the upgrade guide talked about the old -> new API migration e.g.

```
Unirest.setTimeouts(long connectionTimeout, long socketTimeout);
-->
  Unirest.config()
           .socketTimeout(500)
           .connectTimeout(1000)
```

The same for e.g. `Unirest.setObjectMapper( objectMapper )`

**Comment by ryber** [comment]
Good catch, I'll get it updated

**Comment by ryber** [comment]
@rnc the guide does talk pretty extensively about how configuration is done here: https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md#unirestconfig

Is that not clear?

**Comment by rnc** [comment]
@ryber  What I meant was prior Unirest (i.e. prior to your great updates :-) ) had a different API. So it could say - "previous API was xxxx, and the new API is" ..... i.e. make it clearer on the upgrade path.
