### ISSUE TITLE
Documentation Improvements

### ISSUE THREAD

**Issue by rnc** [Kong/unirest-java#306]
When working on the upgrade to the latest Unirest I noticed a few small things that would be helpful if they were documented in the user guide. Some of these were talked about in issues, but not added to the guide.

* Missing mapError
* Missing mapBody
* GenericType - while the example shows it being used ( https://kong.github.io/unirest-java/#responses ) it is missing javadoc and a description within the guide.
* Metrics section:
   * Spelling : `Context inforation`
   * Grammar: `In it’s simplest form it might like this` --> `In it’s simplest form an example may be:`

</br>
</br>
Excellent upgrade, the client code is now much simpler! Thanks!

**Comment by ryber** [comment]
should be better. the config in the old system was all over the place, so I made it clear that everything is now in config()
