### ISSUE TITLE
Please provide a rebuild of version 3.1.02

### ISSUE THREAD

**Issue by JoHaHu** [Kong/unirest-java#311]
The org.apache.httpcomponents:httpasyncclient:4.1.4 library that unirest depends on has fixed a bug in httpcore-nio where automatic module name resolution in java 9 and above fails, because they uses an invalid module identifier.
Please provide a rebuild of this library. There is no need to change any version number of any library because httpasyncclient fixed it with same version number. 
Otherwise a new version with fixed libray is appreciated aswell.

Thank you!

**Comment by JoHaHu** [comment]
Sorry they didnt fixed. it my bad.

**Comment by ryber** [comment]
Do you have a link to the issue in their issue tracker (I think it's Jira?)

**Comment by JoHaHu** [comment]
https://issues.apache.org/jira/browse/HTTPCORE-533

**Comment by ryber** [comment]
It's possible we can simply declare our own dependency on httpcore-nio and override 4.4.10

**Comment by JoHaHu** [comment]
That would be nice. It's my current workaround at the moment.
