### ISSUE TITLE
Could not initialize class kong.unirest.Unirest

### ISSUE THREAD

**Issue by CodeAndChoke** [Kong/unirest-java#323]
**Describe the bug**
I am developing a Spring boot microservice with Unirest. The service works well on local but in the staging phase, we have a very strange bug:

```json
{
"timestamp": 1576073804660,
"status": 500,
"error": "Internal Server Error",
"message": "Could not initialize class kong.unirest.Unirest",
"path": "/api/v1/user/"
}
```

**To Reproduce**
Following code line is being used:

```Java
Unirest.get(url);
```

**Environmental Data:**
 - Java 1.8
 - Unirest 3.1.02
 - Spring boot 2.1.2.RELEASE

**Comment by ryber** [comment]
The Unirest jar isn't in your package. How are you deploying? With a WAR or shaded jar? also make sure you haven't listed the Unirest dependency as "provided" in maven/gradle
