### ISSUE TITLE
Observing unnecessary logs

### ISSUE THREAD

**Issue by Sourabh25** [Kong/unirest-java#340]
**Describe the bug**
I am observing unnecessary logs in my application when I am executing the following:
Unirest.post(baseUrl).basicAuth(authUserName, authPassword).headers(headerContent).body(requestBody).asString();

**To Reproduce**
When I am executing the line of code:
Unirest.post(baseUrl).basicAuth(authUserName, authPassword).headers(headerContent)
						.body(requestBody).asString();

I am observing the below logs in my application console
[DEBUG] 2020-02-28 15:25:47.778 [main] RequestAddCookies - CookieSpec selected: default
[DEBUG] 2020-02-28 15:25:47.778 [main] RequestAuthCache - Auth cache not set in the context
[DEBUG] 2020-02-28 15:25:47.779 [main] PoolingHttpClientConnectionManager - Connection request: [route: {}->http://10.124.4.252:9201][total kept alive: 2; route allocated: 1 of 2; total allocated: 2 of 20]
[DEBUG] 2020-02-28 15:25:47.779 [main] PoolingHttpClientConnectionManager - Connection leased: [id: 1][route: {}->http://10.124.4.252:9201][total kept alive: 1; route allocated: 1 of 2; total allocated: 2 of 20]
[DEBUG] 2020-02-28 15:25:47.779 [main] DefaultManagedHttpClientConnection - http-outgoing-1: set socket timeout to 120000
[DEBUG] 2020-02-28 15:25:47.779 [main] MainClientExec - Executing request POST /frictionless/report HTTP/1.1
[DEBUG] 2020-02-28 15:25:47.779 [main] MainClientExec - Proxy auth state: UNCHALLENGED
[DEBUG] 2020-02-28 15:25:47.779 [main] headers - http-outgoing-1 >> POST /frictionless/report HTTP/1.1
[DEBUG] 2020-02-28 15:25:47.779 [main] headers - http-outgoing-1 >> Authorization: Basic ZWxhc3RpYzpjaGFuZ2VtZQ==
[DEBUG] 2020-02-28 15:25:47.779 [main] headers - http-outgoing-1 >> Content-Type: application/json
[DEBUG] 2020-02-28 15:25:47.779 [main] headers - http-outgoing-1 >> user-agent: unirest-java/3.1.00
[DEBUG] 2020-02-28 15:25:47.779 [main] headers - http-outgoing-1 >> accept-encoding: gzip
[DEBUG] 2020-02-28 15:25:47.779 [main] headers - http-outgoing-1 >> Content-Length: 782
[DEBUG] 2020-02-28 15:25:47.779 [main] headers - http-outgoing-1 >> Host: 10.124.4.252:9201
[DEBUG] 2020-02-28 15:25:47.779 [main] headers - http-outgoing-1 >> Connection: Keep-Alive
[DEBUG] 2020-02-28 15:25:47.779 [main] wire - http-outgoing-1 >> "POST /frictionless/report HTTP/1.1[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.779 [main] wire - http-outgoing-1 >> "Authorization: Basic ZWxhc3RpYzpjaGFuZ2VtZQ==[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.779 [main] wire - http-outgoing-1 >> "Content-Type: application/json[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.779 [main] wire - http-outgoing-1 >> "user-agent: unirest-java/3.1.00[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.779 [main] wire - http-outgoing-1 >> "accept-encoding: gzip[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.779 [main] wire - http-outgoing-1 >> "Content-Length: 782[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.779 [main] wire - http-outgoing-1 >> "Host: 10.124.4.252:9201[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.779 [main] wire - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.779 [main] wire - http-outgoing-1 >> "[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.779 [main] wire - http-outgoing-1 >> "{"REPORT_DESCRIPTION":"Test method passed","TRANSACTION_NAME":"Summary_Report","APPLICATION":"FRICTIONLESS","MASTER_JOB":"LocalJob_HQSML-152086_2020_Feb_28_15_25_15","REPORT_SCENARIO_NAME":"processOffersInCart","TRANSACTION_TYPE":"REPORT","END_TIME":"02-28-2020 15:25:40:347","REPORT_SCREENSHOTS_PATH":"validateProcessOffersInCart_28-Feb-2020_03-25-38_PM.png","REPORT_TIMESTAMP":"02-28-2020 15:25:40:347","START_TIME":"02-28-2020 15:25:40:347","BROWSER":"chrome","REPORT_STEP_NAME":"ApiTestIterationStep","METHOD_NAME":"ApiTestIterationStep","REPORT_TEST_NAME":"validateProcessOffersInCart","TESTNG_XML_NAME":"APIs","HOST":"HQSML-152086","REPORT_API_STEP_NAME":"validate_processOffersInCart","APP_ENV":"INT","RUN_ID":"RunId_HQSML-152086_2020_Feb_28_15_25_15","REPORT_STATUS":"PASS"}"
[DEBUG] 2020-02-28 15:25:47.849 [main] wire - http-outgoing-1 << "HTTP/1.1 201 Created[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.849 [main] wire - http-outgoing-1 << "Location: /frictionless_index_q1_2020/report/AXCNegBcplrCpOhzpV7i[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.849 [main] wire - http-outgoing-1 << "content-type: application/json; charset=UTF-8[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.849 [main] wire - http-outgoing-1 << "content-encoding: gzip[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] wire - http-outgoing-1 << "transfer-encoding: chunked[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] wire - http-outgoing-1 << "[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] wire - http-outgoing-1 << "9a[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] wire - http-outgoing-1 << "[0x1f][0x8b][0x8][0x0][0x0][0x0][0x0][0x0][0x0][0x0]<[0x8d][0xb1][0xe][0xc2]0[0xc]D[0xff][0xc5]s[0x86][0xb6][0xb]R6[0xe8][0xe][0x1b]b[0x8b][0xa2][0xc4][0xa5][0x91][0xa2]6[0xd8]N[0x5]T[0xfd]w\Ub[0xbc][0xbb]ww+[0xb8]4E|[0x83][0x85][0x81]R[0x90]4O[0x19][0x99][0xf][0xd3][0xbd]Z[0xd7]5][0x3][0x6][0x9c]|[\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] wire - http-outgoing-1 << "*DXf[0x92][0xdd]HQ[0xe5][0xf9][0xd1]_[0xf1]y[0x9]%S_n[0xe3][0xb7][0xdc]Oi[0xf][0x17]$[0xd6])[0xb0][0xad][0xd1][\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] wire - http-outgoing-1 << "[0xd7],[\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] wire - http-outgoing-1 << "[0x7]B/[0x18][0xf7][0x9c]GO[0x91][0xc1][0xae] [0xb3][0xf8][0xc][0xb6]3[0xc0]5[0x4][0xbd][0x1e][0xea]![0x7][0x9f][0xb2][0xc2][0xb6][0xd9][0xcc][0xbf]i[0x85]*n?[0x0][0x0][0x0][0xff][0xff][\r][\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] wire - http-outgoing-1 << "a[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] wire - http-outgoing-1 << "[0x3][0x0][0xf9][0xb5][0x96][0x1a][0xb4][0x0][0x0][0x0][\r][\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] wire - http-outgoing-1 << "0[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] wire - http-outgoing-1 << "[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.850 [main] headers - http-outgoing-1 << HTTP/1.1 201 Created
[DEBUG] 2020-02-28 15:25:47.850 [main] headers - http-outgoing-1 << Location: /frictionless_index_q1_2020/report/AXCNegBcplrCpOhzpV7i
[DEBUG] 2020-02-28 15:25:47.850 [main] headers - http-outgoing-1 << content-type: application/json; charset=UTF-8
[DEBUG] 2020-02-28 15:25:47.850 [main] headers - http-outgoing-1 << content-encoding: gzip
[DEBUG] 2020-02-28 15:25:47.850 [main] headers - http-outgoing-1 << transfer-encoding: chunked
[DEBUG] 2020-02-28 15:25:47.850 [main] MainClientExec - Connection can be kept alive indefinitely
[DEBUG] 2020-02-28 15:25:47.851 [main] PoolingHttpClientConnectionManager - Connection [id: 1][route: {}->http://10.124.4.252:9201] can be kept alive indefinitely
[DEBUG] 2020-02-28 15:25:47.851 [main] PoolingHttpClientConnectionManager - Connection released: [id: 1][route: {}->http://10.124.4.252:9201][total kept alive: 2; route allocated: 1 of 2; total allocated: 2 of 20]
[DEBUG] 2020-02-28 15:25:47.851 [main] MainClientExec - Cancelling request execution
[DEBUG] 2020-02-28 15:25:47.851 [main] HttpUtils - Response Body{"_index":"frictionless_index_q1_2020","_type":"report","_id":"AXCNegBcplrCpOhzpV7i","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"created":true}
[DEBUG] 2020-02-28 15:25:47.852 [main] HttpUtils - HTTP URL provided. No need to for TrustManager
[DEBUG] 2020-02-28 15:25:47.852 [main] RequestAddCookies - CookieSpec selected: default
[DEBUG] 2020-02-28 15:25:47.852 [main] RequestAuthCache - Auth cache not set in the context
[DEBUG] 2020-02-28 15:25:47.852 [main] PoolingHttpClientConnectionManager - Connection request: [route: {}->http://10.124.4.252:9201][total kept alive: 2; route allocated: 1 of 2; total allocated: 2 of 20]
[DEBUG] 2020-02-28 15:25:47.853 [main] PoolingHttpClientConnectionManager - Connection leased: [id: 1][route: {}->http://10.124.4.252:9201][total kept alive: 1; route allocated: 1 of 2; total allocated: 2 of 20]
[DEBUG] 2020-02-28 15:25:47.853 [main] DefaultManagedHttpClientConnection - http-outgoing-1: set socket timeout to 120000
[DEBUG] 2020-02-28 15:25:47.853 [main] MainClientExec - Executing request POST /frictionless/report HTTP/1.1
[DEBUG] 2020-02-28 15:25:47.853 [main] MainClientExec - Proxy auth state: UNCHALLENGED
[DEBUG] 2020-02-28 15:25:47.853 [main] headers - http-outgoing-1 >> POST /frictionless/report HTTP/1.1
[DEBUG] 2020-02-28 15:25:47.853 [main] headers - http-outgoing-1 >> Authorization: Basic ZWxhc3RpYzpjaGFuZ2VtZQ==
[DEBUG] 2020-02-28 15:25:47.853 [main] headers - http-outgoing-1 >> Content-Type: application/json
[DEBUG] 2020-02-28 15:25:47.853 [main] headers - http-outgoing-1 >> user-agent: unirest-java/3.1.00
[DEBUG] 2020-02-28 15:25:47.853 [main] headers - http-outgoing-1 >> accept-encoding: gzip
[DEBUG] 2020-02-28 15:25:47.853 [main] headers - http-outgoing-1 >> Content-Length: 732
[DEBUG] 2020-02-28 15:25:47.853 [main] headers - http-outgoing-1 >> Host: 10.124.4.252:9201
[DEBUG] 2020-02-28 15:25:47.853 [main] headers - http-outgoing-1 >> Connection: Keep-Alive
[DEBUG] 2020-02-28 15:25:47.853 [main] wire - http-outgoing-1 >> "POST /frictionless/report HTTP/1.1[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.853 [main] wire - http-outgoing-1 >> "Authorization: Basic ZWxhc3RpYzpjaGFuZ2VtZQ==[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.853 [main] wire - http-outgoing-1 >> "Content-Type: application/json[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.853 [main] wire - http-outgoing-1 >> "user-agent: unirest-java/3.1.00[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.853 [main] wire - http-outgoing-1 >> "accept-encoding: gzip[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.853 [main] wire - http-outgoing-1 >> "Content-Length: 732[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.853 [main] wire - http-outgoing-1 >> "Host: 10.124.4.252:9201[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.853 [main] wire - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.853 [main] wire - http-outgoing-1 >> "[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.853 [main] wire - http-outgoing-1 >> "{"REPORT_DESCRIPTION":"Test  passed","TRANSACTION_NAME":"Summary_Report","APPLICATION":"FRICTIONLESS","MASTER_JOB":"LocalJob_HQSML-152086_2020_Feb_28_15_25_15","REPORT_SCENARIO_NAME":"processOffersInCart","TRANSACTION_TYPE":"REPORT","END_TIME":"02-28-2020 15:25:40:354","REPORT_SCREENSHOTS_PATH":"null","REPORT_TIMESTAMP":"02-28-2020 15:25:40:354","START_TIME":"02-28-2020 15:25:40:354","BROWSER":"chrome","REPORT_STEP_NAME":"validateProcessOffersInCart","METHOD_NAME":"ApiTestIterationStep","REPORT_TEST_NAME":"validateProcessOffersInCart","TESTNG_XML_NAME":"APIs","HOST":"HQSML-152086","REPORT_API_STEP_NAME":"validate_processOffersInCart","APP_ENV":"INT","RUN_ID":"RunId_HQSML-152086_2020_Feb_28_15_25_15","REPORT_STATUS":"PASS"}"
[DEBUG] 2020-02-28 15:25:47.890 [main] wire - http-outgoing-1 << "HTTP/1.1 201 Created[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.890 [main] wire - http-outgoing-1 << "Location: /frictionless_index_q1_2020/report/AXCNegCJplrCpOhzpV7j[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.890 [main] wire - http-outgoing-1 << "content-type: application/json; charset=UTF-8[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.890 [main] wire - http-outgoing-1 << "content-encoding: gzip[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.890 [main] wire - http-outgoing-1 << "transfer-encoding: chunked[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.890 [main] wire - http-outgoing-1 << "[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.890 [main] wire - http-outgoing-1 << "9b[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.890 [main] wire - http-outgoing-1 << "[0x1f][0x8b][0x8][0x0][0x0][0x0][0x0][0x0][0x0][0x0]<[0x8d][0xb1][0xe][0xc2]0[0xc]D[0xff][0xc5]s[0x86][0xb6][0xb]R6[0xd4][0x8d][0x1]6[0xc4][0x16]E[0x89]K[0x83][0xa2]6[0xd8][0xe][0x2][0xaa][0xfe];[0xae]*1[0xde][0xdd][0xbb][0xbb][0x5]\[0x9a]"[0xbe][0xc1][0xc2]@)H[0x9a][0xa7][0x8c][0xcc][0xbb][0xe9][0x9e][0xad][0xeb][0x9a][0xae][0x1][0x3]N>[0x5][0x15]",3[0xc9]f[0xa4][0xa8][0xf2]x[0xeb][0xcf]x[0xef]O%S_.[0xe3][0xb7]\[0xf][0x8f]-|![0xb1]N[0x81]m[0x8d]V[0xb8]fQ8[0x10]z[0xc1][0xb8][0xe5]<z[0x8a][0xc]v[0x1][0x99][0xc5]g[0xb0][0x9d][0x1][0xae]![0xe8][0xf5]Pw9[0xf8][0x94][0x15][0xb6][0xcd]j[0xfe]M+Tq[0xfd][0x1][0x0][0x0][0xff][0xff][\r][\n]"
[DEBUG] 2020-02-28 15:25:47.891 [main] wire - http-outgoing-1 << "a[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.891 [main] wire - http-outgoing-1 << "[0x3][0x0][0xec][0xa7]C[0xbc][0xb4][0x0][0x0][0x0][\r][\n]"
[DEBUG] 2020-02-28 15:25:47.891 [main] wire - http-outgoing-1 << "0[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.891 [main] wire - http-outgoing-1 << "[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.891 [main] headers - http-outgoing-1 << HTTP/1.1 201 Created
[DEBUG] 2020-02-28 15:25:47.891 [main] headers - http-outgoing-1 << Location: /frictionless_index_q1_2020/report/AXCNegCJplrCpOhzpV7j
[DEBUG] 2020-02-28 15:25:47.891 [main] headers - http-outgoing-1 << content-type: application/json; charset=UTF-8
[DEBUG] 2020-02-28 15:25:47.891 [main] headers - http-outgoing-1 << content-encoding: gzip
[DEBUG] 2020-02-28 15:25:47.891 [main] headers - http-outgoing-1 << transfer-encoding: chunked
[DEBUG] 2020-02-28 15:25:47.891 [main] MainClientExec - Connection can be kept alive indefinitely
[DEBUG] 2020-02-28 15:25:47.891 [main] PoolingHttpClientConnectionManager - Connection [id: 1][route: {}->http://10.124.4.252:9201] can be kept alive indefinitely
[DEBUG] 2020-02-28 15:25:47.891 [main] PoolingHttpClientConnectionManager - Connection released: [id: 1][route: {}->http://10.124.4.252:9201][total kept alive: 2; route allocated: 1 of 2; total allocated: 2 of 20]
[DEBUG] 2020-02-28 15:25:47.891 [main] MainClientExec - Cancelling request execution
[DEBUG] 2020-02-28 15:25:47.891 [main] HttpUtils - Response Body{"_index":"frictionless_index_q1_2020","_type":"report","_id":"AXCNegCJplrCpOhzpV7j","_version":1,"result":"created","_shards":{"total":2,"successful":2,"failed":0},"created":true}
[DEBUG] 2020-02-28 15:25:47.892 [main] HttpUtils - HTTP URL provided. No need to for TrustManager
[DEBUG] 2020-02-28 15:25:47.892 [main] RequestAddCookies - CookieSpec selected: default
[DEBUG] 2020-02-28 15:25:47.892 [main] RequestAuthCache - Auth cache not set in the context
[DEBUG] 2020-02-28 15:25:47.893 [main] PoolingHttpClientConnectionManager - Connection request: [route: {}->http://10.124.4.252:9201][total kept alive: 2; route allocated: 1 of 2; total allocated: 2 of 20]
[DEBUG] 2020-02-28 15:25:47.893 [main] PoolingHttpClientConnectionManager - Connection leased: [id: 1][route: {}->http://10.124.4.252:9201][total kept alive: 1; route allocated: 1 of 2; total allocated: 2 of 20]
[DEBUG] 2020-02-28 15:25:47.893 [main] DefaultManagedHttpClientConnection - http-outgoing-1: set socket timeout to 120000
[DEBUG] 2020-02-28 15:25:47.893 [main] MainClientExec - Executing request POST /frictionless/report HTTP/1.1
[DEBUG] 2020-02-28 15:25:47.893 [main] MainClientExec - Proxy auth state: UNCHALLENGED
[DEBUG] 2020-02-28 15:25:47.893 [main] headers - http-outgoing-1 >> POST /frictionless/report HTTP/1.1
[DEBUG] 2020-02-28 15:25:47.893 [main] headers - http-outgoing-1 >> Authorization: Basic ZWxhc3RpYzpjaGFuZ2VtZQ==
[DEBUG] 2020-02-28 15:25:47.893 [main] headers - http-outgoing-1 >> Content-Type: application/json
[DEBUG] 2020-02-28 15:25:47.893 [main] headers - http-outgoing-1 >> user-agent: unirest-java/3.1.00
[DEBUG] 2020-02-28 15:25:47.893 [main] headers - http-outgoing-1 >> accept-encoding: gzip
[DEBUG] 2020-02-28 15:25:47.893 [main] headers - http-outgoing-1 >> Content-Length: 821
[DEBUG] 2020-02-28 15:25:47.893 [main] headers - http-outgoing-1 >> Host: 10.124.4.252:9201
[DEBUG] 2020-02-28 15:25:47.893 [main] headers - http-outgoing-1 >> Connection: Keep-Alive
[DEBUG] 2020-02-28 15:25:47.893 [main] wire - http-outgoing-1 >> "POST /frictionless/report HTTP/1.1[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.893 [main] wire - http-outgoing-1 >> "Authorization: Basic ZWxhc3RpYzpjaGFuZ2VtZQ==[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.893 [main] wire - http-outgoing-1 >> "Content-Type: application/json[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.893 [main] wire - http-outgoing-1 >> "user-agent: unirest-java/3.1.00[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.893 [main] wire - http-outgoing-1 >> "accept-encoding: gzip[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.893 [main] wire - http-outgoing-1 >> "Content-Length: 821[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.893 [main] wire - http-outgoing-1 >> "Host: 10.124.4.252:9201[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.893 [main] wire - http-outgoing-1 >> "Connection: Keep-Alive[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.893 [main] wire - http-outgoing-1 >> "[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.893 [main] wire - http-outgoing-1 >> "{"REPORT_DESCRIPTION":"Access file using the link in next column - \u003e\u003e","TRANSACTION_NAME":"Summary_Report","APPLICATION":"FRICTIONLESS","MASTER_JOB":"LocalJob_HQSML-152086_2020_Feb_28_15_25_15","REPORT_SCENARIO_NAME":"processOffersInCart","TRANSACTION_TYPE":"REPORT","END_TIME":"02-28-2020 15:25:22:793","REPORT_SCREENSHOTS_PATH":"0228_152522_773_validate_processOffersInCart.txt","REPORT_TIMESTAMP":"02-28-2020 15:25:22:793","START_TIME":"02-28-2020 15:25:22:793","BROWSER":"chrome","REPORT_STEP_NAME":"validate_processOffersInCart","METHOD_NAME":"ApiTestIterationStep","REPORT_TEST_NAME":"validateProcessOffersInCart","TESTNG_XML_NAME":"APIs","HOST":"HQSML-152086","REPORT_API_STEP_NAME":"validate_processOffersInCart","APP_ENV":"INT","RUN_ID":"RunId_HQSML-152086_2020_Feb_28_15_25_15","REPORT_STATUS":"FILE"}"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "HTTP/1.1 201 Created[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "Location: /frictionless_index_q1_2020/report/AXCNegCwplrCpOhzpV7k[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "content-type: application/json; charset=UTF-8[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "content-encoding: gzip[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "transfer-encoding: chunked[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "9a[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "[0x1f][0x8b][0x8][0x0][0x0][0x0][0x0][0x0][0x0][0x0]<[0x8d][0xbd][0xe][0x83]0[0xc][0x84][0xdf][0xc5]s[0x6]`[0xa9][0x94][0xad]bo[0xb7][0xaa][[0x14]%[0xa6]D[0x8d] [0xb5][0x9d][0xfe]![0xde][0xbd]FH[0x1d][0xef][0xee][0xbb][0xbb][0x5]\[0x9a]"[0xbe][0xc1][0xc2]@)H[0x9a][0xa7][0x8c][0xcc][0xbb][0xe9][0x1e][0xad][0xeb][0x9a][0xae][0x1][0x3]N>[0x5][0x15]",3[0xc9]f[0xa4][0xa8][0xf2]x[0xed]Ox[0xeb]_%S_[0xce][0xe3][0xb7]\[0xe][0xf7]-|"[0xb1]N[0x81]m[0x8d]V[0xb8]fQ8[0x10]z[0xc1][0xb8][0xe5]<z[0x8a][0xc]v[0x1][0x99][0xc5]g[0xb0][0x9d][0x1][0xae]![0xe8][0xf5]Pw9[0xf8][0x94][0x15][0xb6][0xcd]j[0xfe]M+Tq[0xfd][0x1][0x0][0x0][0xff][0xff][\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "a[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "[0x3][0x0]}[0xe1][0x8d]E[0xb4][0x0][0x0][0x0][\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "0[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] wire - http-outgoing-1 << "[\r][\n]"
[DEBUG] 2020-02-28 15:25:47.931 [main] headers - http-outgoing-1 << HTTP/1.1 201 Created
[DEBUG] 2020-02-28 15:25:47.931 [main] headers - http-outgoing-1 << Location: /frictionless_index_q1_2020/report/AXCNegCwplrCpOhzpV7k
[DEBUG] 2020-02-28 15:25:47.931 [main] headers - http-outgoing-1 << content-type: application/json; charset=UTF-8
[DEBUG] 2020-02-28 15:25:47.931 [main] headers - http-outgoing-1 << content-encoding: gzip
[DEBUG] 2020-02-28 15:25:47.932 [main] headers - http-outgoing-1 << transfer-encoding: chunked
[DEBUG] 2020-02-28 15:25:47.932 [main] MainClientExec - Connection can be kept alive indefinitely
[DEBUG] 2020-02-28 15:25:47.932 [main] PoolingHttpClientConnectionManager - Connection [id: 1][route: {}->http://10.124.4.252:9201] can be kept alive indefinitely
[DEBUG] 2020-02-28 15:25:47.932 [main] PoolingHttpClientConnectionManager - Connection released: [id: 1][route: {}->http://10.124.4.252:9201][total kept alive: 2; route allocated: 1 of 2; total allocated: 2 of 20]
[DEBUG] 2020-02-28 15:25:47.932 [main] MainClientExec - Cancelling request execution

**Expected behavior**
I should not see these logs.

**Environmental Data:**
 - Java Version - 1.8
 - Version [e.g. 3.6.00]

**Comment by ryber** [comment]
You have enabled debug logging for like everything, if you don't want to see them then you should configure your logging to not have debug logging for all classes. 

These logs also are not Unirest log lines, they are from Apache Http Client but if you ask them they will tell you the same thing. Don't configure your logging for debug level on all classes.

Unirest cannot configure your logger to turn them off, because there are times when people do want to see them, plus Unirest doesn't even come with any logging configuration at all itself.

**Comment by Sourabh25** [comment]
@ryber Yes I can see it is set to debug. But I am not sure how it is set to debug. From my logj.properties file, I am passing info only. I am not viewing these logs in my log files which i am generating but why these are coming up in the console. Not sure what I am doing wrong?
