### ISSUE TITLE
Official jar release download

### ISSUE THREAD

**Issue by luecking** [Kong/unirest-java#343]
Hi,
is it possible that you upload also the final jar (release page)?

I tried to get it compiling, but it failed totally with OpenJDK 11.
It always wants to have the JDK, not the JRE. But I only have the JDK?!?

There are problems with test which are failing (online?), there are problems with mvn.bat, which is officially already renamed to mvn.cmd, etc.

I really only need the jar and there are only possible, let's say, very unsafe pages in the web which offer maybe a "safe" download.

**Comment by ryber** [comment]
The jars are in maven central. The most recent release is here: https://repo.maven.apache.org/maven2/com/konghq/unirest-java/3.7.00/

**Comment by luecking** [comment]
I really searched for it. Now with the link I'm absolutely fine! Thank you.
