### ISSUE TITLE
No response when sending large file

### ISSUE THREAD

**Issue by 799452017** [Kong/unirest-java#353]
**Describe the bug**
Sending files larger than 100m stuck.

**To Reproduce**

`Unirest.post("xxx").field("file",new file("XXX")).asJson();`
**Expected behavior**

**Screenshots**
Is a zip file larger than 100m.

**Environmental Data:**
 - Java Version
 - Version [e.g. 3.3.03]

**Additional context**

**Comment by ryber** [comment]
I think your problem may be on the receiving side, I can successfully upload files larger than 100m. You might add a progress monitor so see where it stops.

```
 HttpResponse<JsonNode> node = Unirest.post(xxx)
                .field("other", new File("/file.txt"))
                .uploadMonitor(new ProgressMonitor() {
                    @Override
                    public void accept(String field, String fileName, Long bytesWritten, Long totalBytes) {
                        System.out.println("bytesWritten = " + (totalBytes - bytesWritten));
                    }
                })
                .asJson();
```

**Comment by 799452017** [comment]
Thank you for your reply,After observing the progress, I found that the log output of org.apache.http.wire debug caused the file to be sent very slowly, just like it was stuck. When I closed the log, the file sending was very smooth. Thank you.

**Comment by 799452017** [comment]
> 我认为您的问题可能在接收方，我可以成功上传大于100m的文件。您可能会添加一个进度监视器，以便查看它的停止位置。
> 
> ```java
>  HttpResponse < JsonNode > node =  Unirest 。后（XXX）
>                 点域（“其他”，新的 文件（“ /file.txt ”））
>                 .uploadMonitor（新 ProgressMonitor（）{
>                      @覆盖
>                     公共 无效 接受（字符串 场，字符串 文件名，龙 bytesWritten，龙 totalBytes）{
>                          系统。出来。println（“ bytesWritten = ”  +（totalBytes - bytesWritten））; 
>                     } 
>                 ）. 
>                 asJson（）;
> ```

Thank you for your reply,After observing the progress, I found that the log output of org.apache.http.wire debug caused the file to be sent very slowly, just like it was stuck. When I closed the log, the file sending was very smooth. Thank you.
