### ISSUE TITLE
NoHttpResponseException gets logged outside UnirestException

### ISSUE THREAD

**Issue by Tinkot** [Kong/unirest-java#354]
**Describe the bug**
When a server returns no response, a exception is thrown, you can catch UnirestException but it will still log a error outside of our catch block. 

**To Reproduce**
1. run a rest server (i used [SparkJava](http://sparkjava.com/))
2. make it so it can't return anything, (block the application with a interrupt/make it unresoponive).
3. do a request to the server. I used:
`Unirest.get(url).connectTimeout(1500).socketTimeout(3000).asString();
`

**Expected behavior**
The exception is not logged, the UnirestException already contains the exact same message.

**Screenshots**
The NoHttpResponseException error we don't want: [link](https://i.ibb.co/KbQ2n2X/Schermafbeelding-2020-04-17-om-22-16-45.png)
What can be catched using UnirestException: [link](https://i.ibb.co/D7BfLP4/Schermafbeelding-2020-04-17-om-22-43-58.png)

**Environmental Data:**
OpenJDK Runtime Environment 18.9 (build 11.0.6+10)

**Additional context**
I'm running my rest server inside of a [PaperSpigot](https://papermc.io/) minecraft server (with very low specs), it occurs while the server is initializing, so the address is reachable, but the server application unresponsive

**Comment by ryber** [comment]
It looks like you have logging enabled for the apache library, you would need to disable that logging. This has nothing to do with Unirest wrapping and throwing the exception. I cannot disable this log, only you can

**Comment by Tinkot** [comment]
Hmm, thats strange, i never enabled myself. anyways, the log got removed by doing `System.setProperty("org.apache.commons.logging.Log","org.apache.commons.logging.impl.NoOpLog");` so i should figure out whats enabling it.
