### ISSUE TITLE
add ability to set a collection of cookies

### ISSUE THREAD

**Issue by Nafanya123** [Kong/unirest-java#358]
hello, can you add in Unirest support Array Cookies?
kong.unirest.Cookies

`Unirest.get("https://www.site.com/").cookies(new kong.unirest.Cookies())`

Thanks,,

**Comment by ryber** [comment]
The Cookies object is mostly for reading the cookies. What would be the point of setting it? Unirest already has a cookie policy to send back the same cookies returned from the requesting server.

**Comment by Nafanya123** [comment]
Sometimes an HTTP request does not work without cookies, and there may be more than 5 such cookies, and each time a new HTTP request is needed, it looks rather cumbersome, and therefore it would be easier to do this by headers analogy

**Comment by ryber** [comment]
So you don’t want to set a Cookies object you want to set more than 1 cookie at once, as a collection. These are not cookies that the server returned and so would be part of the policy on the domain?

**Comment by ryber** [comment]
Complete is 3.8.00
