### ISSUE TITLE
get a Minimum unirest-java

### ISSUE THREAD

**Issue by JanYunkai** [Kong/unirest-java#359]
i want to remove dependency get a minimum library
<dependency>
            <groupId>com.konghq</groupId>
            <artifactId>unirest-java</artifactId>
            <version>3.8.00</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.code.gson</groupId>
                    <artifactId>gson</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.httpcomponents</groupId>
                    <artifactId>httpasyncclient</artifactId>
                </exclusion>
            </exclusions>
</dependency>

when i exclude gson replace my custom json lib(like jackson, fastjson....)  i get err

java.lang.NoClassDefFoundError: com/google/gson/Gson

now the library default and Strong binding gson

feature:
1. support interface for ObjectMapper?
2. support asObject(Type responseType)?

public interface ObjectMapper {
	<T> T readValue(String value, Class<T> valueType);
       //replace     readValue(String value, GenericType<T> genericType)
        <T> T readValue(String value, Type valueType);
	//default <T> T readValue(String value, GenericType<T> genericType){
	//	throw new UnirestException("Please implement me");
	//}
	String writeValue(Object value);
}

**Comment by ryber** [comment]
You have to implement an alternative ObjectMapper and add it to the configuration in order to use a different JSON implementation, I'll look into being able to exclude it although some things (like .asJson) is it's own implementation that leverages GSON and cannot be replaced. So excluding gson will break that

**Comment by ryber** [comment]
I've made the default object mapper lazy in 3.8.06, but you will still need gson on the path in order to work with the asJson methods as they do not use any other implementation
