### ISSUE TITLE
Parse json incorrectly

### ISSUE THREAD

**Issue by zjffdu** [Kong/unirest-java#366]
**Describe the bug**

Here's the code I write,
```
    JSONObject jsonObject = new JSONObject("{\"status\":\"OK\",\"message\":\"hive_1597818501335\"}");
    System.out.println(jsonObject);
```
But the output is unexpected
```
{"members":{}}
```

It is very weird, I don't know how does `members` come from.

**To Reproduce**
The the sample code above.

**Expected behavior**

**Screenshots**

**Environmental Data:**
 - Java Version
 - Version [e.g. 3.3.03]

**Additional context**

**Comment by ryber** [comment]
I added a test, it works just fine:
https://github.com/Kong/unirest-java/commit/4aa7c5be4e0d664e31e67f518bd576565784645b

Do you maybe have an old version of Gson on your claspath?

**Comment by zjffdu** [comment]
Thanks @ryber ,  you are right this is due to I have another gson on my classpath.

**Comment by ryber** [comment]
Can I ask, what version are you using? It's possible I could make Unirest more backwards compatible

**Comment by zjffdu** [comment]
I use gson 2.2

**Comment by ryber** [comment]
Oh, yea, that's way to old, I'm kind of surprised that you don't get a classnotfound exception
