### ISSUE TITLE
How to apply graphql with query variable in android?

### ISSUE THREAD

**Issue by AAIING** [Kong/unirest-java#377]
i need know how to apply query/mutation  to android 

example in playground:

mutation($usuarios: UsuariosInput!){
  modificarUsuario(id: 3 usuarios:$usuarios){
   	id_usuario
    email
    contrasena
  }
}

query variable

{
  "usuarios": {
  		"email": "testin123@testin.cl",
    	"contrasena": "123456",
    		"nombre":"testin1",
    		"apellido": "test"
  }
}

apply to android how?

ty!

**Comment by ryber** [comment]
Per the spec (YMMV) GraphQL can be called over HTTP as either a GET or a POST and it's a little different for each. https://graphql.org/learn/serving-over-http/

If it was GET it would probably look something like this:
```
Unirest.get("http://server/graphql-endpoint")
                .header("Accept", "application/graphql")
                .queryString("query", "{\n" +
                        "\"usuarios\": {\n" +
                        "\"email\": \"testin123@testin.cl\",\n" +
                        "\"contrasena\": \"123456\",\n" +
                        "\"nombre\":\"testin1\",\n" +
                        "\"apellido\": \"test\"\n" +
                        "}\n" +
                        "}")
                .asJson();
```

or a POST would look like this: 
```
Unirest.post("http://server/graphql-endpoint")
                .header("Accept", "application/graphql")
                .header("Content-Type", "application/json")
                .body(new JSONObject().put("query", "{\n" +
                        "\"usuarios\": {\n" +
                        "\"email\": \"testin123@testin.cl\",\n" +
                        "\"contrasena\": \"123456\",\n" +
                        "\"nombre\":\"testin1\",\n" +
                        "\"apellido\": \"test\"\n" +
                        "}\n" +
                        "}"))
                .asJson();
```

Note that GraphQL syntax is itself NOT json, it only looks JSON-ish.

**Comment by ryber** [comment]
@AAIING was your question answered?
