### ISSUE TITLE
trans body with get method

### ISSUE THREAD

**Issue by dtdyq** [Kong/unirest-java#388]
Unirest.get() can not trans body.is it correct？

**Comment by ryber** [comment]
No,

Because the HTTP spec is very specific that servers should not honor any body on a GET

https://tools.ietf.org/html/rfc7231#page-24
> A payload within a GET request message has no defined semantics; sending a payload body on a GET request might cause some existing implementations to reject the request.

**Comment by ryber** [comment]
I'm going to go ahead and close this, feel free to follow up in the new github discussions if you want to chat more. https://github.com/Kong/unirest-java/discussions
