### ISSUE TITLE
Latest Release version cited incorrectly

### ISSUE THREAD

**Issue by kirangeorgeb** [Kong/unirest-java#393]
The release version cited as latest is "unirest-java-1.4.8 release". It would be helpful if we could have the latest recommended version here as it gets tough to convey to non technical leadership in organizations?

Appreciate the support and hardwork in building the lightweight library.

Page: https://github.com/Kong/unirest-java

<img width="1425" alt="Screen Shot 2020-12-29 at 7 44 55 PM" src="https://user-images.githubusercontent.com/54578142/103326650-9d0ffb80-4a0e-11eb-8e4e-1bd9da44c108.png">

**Comment by ryber** [comment]
Sure, do you have any experience doing this in CI? I don't want to have to do this by hand. Also, our of morbid curiosity. Why is non-technical leadership interested in the specific version of a library?

**Comment by ryber** [comment]
I created a release flow with actions, we will see if it works next time: https://github.com/Kong/unirest-java/actions?query=workflow%3A%22Create+Release%22

**Comment by kirangeorgeb** [comment]
> Sure, do you have any experience doing this in CI? I don't want to have to do this by hand. Also, our of morbid curiosity. Why is non-technical leadership interested in the specific version of a library?

Have re-engineering effort ahead for legacy code and as we seek investment to address it with new solutions, we get into these potholes
