### ISSUE TITLE
Can't sense connection closed by server in some extreme circumstances

### ISSUE THREAD

**Issue by dlmu-lq** [Kong/unirest-java#403]
**Describe the bug**
Server slb idle connections will be closed in 15s，but the time in client is 30s. So in some extreme circumstance，unirest client will use connections closed by server and throw an exception like:
kong.unirest.UnirestException: org.apache.http.NoHttpResponseException: ** failed to respond

is there anyway to avoid this?

**Comment by ryber** [comment]
as the error implies the error is in Apache. You could create a custom Apache client for unirest that is configured with a NoConnectionReuseStrategy. that may have other negative performance consequences

**Comment by ryber** [comment]
I would note that using that strategy might help with a very flakey server but in the end this is a valid exception

**Comment by dlmu-lq** [comment]
@ryber Thank you for your reply, noticed that unirest have a thread `AsyncIdleConnectionMonitorThread`, do the work : close idle connections every 30s, any consideration to expose `30` as a config?

**Comment by dlmu-lq** [comment]
@ryber Or any consideration to allow users to custom set `ConnectionKeepAliveStrategy` for httpClient may solve this problem?

**Comment by ryber** [comment]
I'm going to close this. There is always the option to use the advanced features of Apache with a custom apache client. It's quite easy to set.
