### ISSUE TITLE
Wrong response body with PUT request

### ISSUE THREAD

**Issue by mike818148** [Kong/unirest-java#413]
**Describe the bug**
We are trying to sent PUT request, the response code is 404. But we don't receive the expected error message from the response body.

**To Reproduce**
1. We are running the below request: 
`HttpResponse<String>` response = unirestInstance.put($URL).body($BODY).asString();`
2. Then we call response.getBody() to check the error message

**Expected behavior**
The expected return error message should be: {"ErrorCode":"CAWS00001E","ErrorMessage":"Failed to update *****. Reason: ******"}
Instead, we get the response in pure html as below: 
&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;>&#xD;&#xA;&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;>&#xD;&#xA;&lt;head>&#xD;&#xA;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=iso-8859-1&quot;/>&#xD;&#xA;&lt;title>404 - File or directory not found.&lt;/title>&#xD;&#xA;&lt;style type=&quot;text/css&quot;>&#xD;&#xA;&lt;!--&#xD;&#xA;body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}&#xD;&#xA;fieldset{padding:0 15px 10px 15px;} &#xD;&#xA;h1{font-size:2.4em;margin:0;color:#FFF;}&#xD;&#xA;h2{font-size:1.7em;margin:0;color:#CC0000;} &#xD;&#xA;h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} &#xD;&#xA;#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:&quot;trebuchet MS&quot;, Verdana, sans-serif;color:#FFF;&#xD;&#xA;background-color:#555555;}&#xD;&#xA;#content{margin:0 0 0 2%;position:relative;}&#xD;&#xA;.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}&#xD;&#xA;-->&#xD;&#xA;&lt;/style>&#xD;&#xA;&lt;/head>&#xD;&#xA;&lt;body>&#xD;&#xA;&lt;div id=&quot;header&quot;>&lt;h1>Server Error&lt;/h1>&lt;/div>&#xD;&#xA;&lt;div id=&quot;content&quot;>&#xD;&#xA; &lt;div class=&quot;content-container&quot;>&lt;fieldset>&#xD;&#xA;  &lt;h2>404 - File or directory not found.&lt;/h2>&#xD;&#xA;  &lt;h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.&lt;/h3>&#xD;&#xA; &lt;/fieldset>&lt;/div>&#xD;&#xA;&lt;/div>&#xD;&#xA;&lt;/body>&#xD;&#xA;&lt;/html>&#xD;&#xA;

**Environmental Data:**
 - Java Version 1.8.0_77
 - Version 3.11.13, 3.13.0

**Additional context**
This problem seems only happens to PUT operation, I tried with POST and GET, no such behavior. 
We tried to use Post-Man to send the same request, the response body display as expected. 
We also tried to use old com.mashape.unirest.http 1.4.9 and no such behavior, the body message retrieved as expected. 
(Ps. we just recently upgrade from mashap 1.4.9 to Kong 3.11.13)

**Comment by ryber** [comment]
that is not an error with Unirest, that is the response you are getting from the remote server

**Comment by mike818148** [comment]
Hello @ryber, 

Thanks for your quick response. I am just wondering why I can get the same body message with same code while using com.mashape.unirest.http 1.4.9 and also with Post-Man. But while using Kong 3.11.13, the body will just display the 404 html response. But I am pretty sure we having another response body message. Do you have any idea on this?

**Comment by ryber** [comment]
IDK something is different, you are getting a 404, which is a not found, the body with the HTML is what the server is sending back. Without knowing what is different from the different setups I can't say, but you ARE getting back the response (it's the HTML)

**Comment by ryber** [comment]
I would check the following:
1. Is the URL the same
2. Is the Accepts and Content-Type headers the same ... you aren't setting them in the example, usually servers expect them
3. Is the body the same

**Comment by mike818148** [comment]
Hello @ryber,

Thanks a lot for the hint. I just checked that in our logic we also have the below code to encode the URL: 
```
String val = URLEncoder.encode(val, UTF_8_ENCODING);
The entire URL will be something like: https://abc.com/api/val
```
I think this is the root cause for the above error. After remove the URLEncoder, it works properly now. 
May I ask does Kong unirest automatically do the URL encoding for each operations (GET, POST, PUT, DELETE) or we need to do it separately. 

Thanks and Regards,
Mike

**Comment by ryber** [comment]
Yes, Unirest handles all the URL encoding. So if you had actual encoded things, then you are going to end up with them being double encoded.

**Comment by mike818148** [comment]
Okai. I see. Thanks a lot for your help. This turns to be a logical error in our code. Which leads to double encoding.
