### ISSUE TITLE
Multiple fields with the same parameter in a POST.

### ISSUE THREAD

**Issue by varunkm** [Kong/unirest-java#42]
I am interacting with an API that allows for multiple fields of the same name to be included in a post request. The app is still under development and not available publicly.

``` JAVA
HttpResponse<JsonNode> jsonResponse = Unirest.post(url)
                    .header("Authorization", "Token " + apikey)
                    .field("parameter", "value1")
                    .field("parameter", "value2")
                    .asJson();
```

The problem I am having is that when I have two fields with the same name, unirest only takes the second one and neglects the first one.

**Comment by sargue** [comment]
Sorry to reopen this old bug but I've stumbled upon it right now trying to use this library to access the [Mailgun](https://www.mailgun.com/) API service.

I disagree on this:

> I am not sure it is REST compliant to have multiple fields with the same name but holding different values, basically you need to rethink the API design

REST is strongly based on HTTP and multiple fields with the same value is a common scenario with HTTP. Be it query strings or form data (body of a POST). The latter is the scenario of the OP.

As an example of an API that requires this usage is the same Mailgun service. To send a mail with multiple attachments you need this funcionality as you can't send them as query parameters.

I've tested this with the Jersey 2 client library and it works fine.
