### ISSUE TITLE
Documentation is misleading for HttpRequestWithBody.body

### ISSUE THREAD

**Issue by derklaro** [Kong/unirest-java#421]
Version: 4.0.0-RC1

Just as the title describes i guess.. The JavaDoc states: `@return this request builder` which leads to the expectation that the method returns the current request instance. The implementation however (`return new HttpRequestUniBody(this).body(body);`) returns a new instance, leading to the fact that the given body is not present.

**Comment by ryber** [comment]
for which method?

**Comment by derklaro** [comment]
All of the `body` methods in `HttpRequestWithBody`

**Comment by derklaro** [comment]
Sorry, missed your commit. Thanks!
