### ISSUE TITLE
Version 3.13.5 has not shown up in Maven Central

### ISSUE THREAD

**Issue by andrei-ivanov** [Kong/unirest-java#423]
https://mvnrepository.com/artifact/com.konghq/unirest-java shows 3.13.4 as latest 3.x

**Comment by ryber** [comment]
5 was released in the middle of the log4j apocalypse and Maven central had a bunch of failures because everyone was releasing patches the same day. I kicked it and it's there now

**Comment by ryber** [comment]
BTW, the GUI of Maven Central is about a day behind the actual repo which is here: https://repo.maven.apache.org/maven2/com/konghq/unirest-java/

**Comment by andrei-ivanov** [comment]
Thanks... yeah, I checked there too  before creating the ticket :)
