### ISSUE TITLE
Unable to upload a file using Unirest

### ISSUE THREAD

**Issue by amuthansakthivel** [Kong/unirest-java#433]
**Describe the bug**
Unable to use form data in body to upload file. I am trying to use Unirest to add attachment to the test rail (test management tool). Curl code looks like this and if someone could help me with the corresponding unirest code, it will be helpful.

$ curl -H "Content-Type: multipart/form-data" \
-u "user@example.com:" \
-F "attachment=@C:\\image.jpg" \
"https://example.testrail.io/index.php?/api/v2/add_attachment_to_result/1

In postman, it looks something like this.

![Screenshot 2022-03-04 at 11 26 23 AM](https://user-images.githubusercontent.com/98022641/156707959-9a8f0899-4f52-4300-ace0-246d48d79f97.png)

I tried below ways in unirest and nothing worked.

```
Unirest.config()
                .setDefaultBasicAuth("username","password")
                .defaultBaseUrl("url")
                .interceptor(new UniRestListener());
```

```
Way 1 :
        File file = new File(System.getProperty("user.dir") + "/index.html");

        RequestBodyEntity request = Unirest.post("/add_attachment_to_run/201")
                .header("Content-Type","multipart/form-data")
                .body(new FileInputStream(file).readAllBytes());

Way 2 : 

Unirest.post("/add_attachment_to_run/"+testRunID)
                .multiPartContent()
                .contentType(ContentType.MULTIPART_FORM_DATA.toString())
                .field("file",new File(System.getProperty("user.dir")+"/index.xml"),"attachment");

Way 3:

Unirest.post("/add_attachment_to_run/"+testRunID)
.header("Content-Type", "multipart/form-data")
                .field("file",new File(System.getProperty("user.dir")+"/index.xml"));
```

All I could get was 400 bad request (POST request not formatted properly or invalid result ID)

**Expected behavior**
I should be able to to add attachment to test rail via unirest

**Screenshots**

**Environmental Data:**
 - Java Version - 1.11
 - Version unirest-java - 3.13.6

**Additional context**
https://www.gurock.com/testrail/docs/api/getting-started/accessing/#ExampleAttachmentUpload

**Comment by ryber** [comment]
stop setting the content type yourself, Unirest handles that and does the proper boundary part which you are missing.
