### ISSUE TITLE
HttpMethod does not expose static method to get all values

### ISSUE THREAD

**Issue by dzikoysk** [Kong/unirest-java#439]
In the past, the `HttpMethod` was an enum that offered `values()` method. Currently the only way to get those values goes through a given value, like e.g. `HttpMethod.GET.all()` and that's quite strange. It looks like `all()` method in `HttpMethod` misses `static` keyword:

```java
public Set<HttpMethod> all(){
    return new HashSet<>(REGISTRY.values());
}
```

Is it supposed to be like that?

**Comment by ryber** [comment]
Unirest only added a HttpMethod class recently, what you were using before was probably the Apache clsss. The Unirest class isn't even a enum.

**Comment by dzikoysk** [comment]
I'm migrating from mashape's Unirest 1.x and I've just noticed that `HttpMethod` misses such method, I don't expect `HttpMethod` to be an enum, just to expose a method that returns all values that are stored in `REGISTRY`. `all()` does this, but it's not static, so I've pretty much ended up using `HttpMethod.GET.all()` that does not really make sense 😅

**Comment by ryber** [comment]
I think that makes sense, and yes, the intent of the all is to be static, and it would't be a breaking change as both work:
   ```java     
   HttpMethod.all();
        HttpMethod.GET.all();
```

**Comment by ryber** [comment]
Do you want to open a PR for it? (Make sure to unit test it) or I can later
