### ISSUE TITLE
Is unirest-java threadsafe?

### ISSUE THREAD

**Issue by vaneyckt** [Kong/unirest-java#44]
Hi there,

just wondering if two threads calling `Unirest.get` at the same time is safe to do?

**Comment by malkusch** [comment]
Oh please put that into the documentation!

**Comment by CristianLlanos** [comment]
Yes, please, add this information in the docs.

**Comment by imhariprakash** [comment]
Is unirest response encrypted ?

**Comment by ryber** [comment]
@imhariprakash unirest performs SSL/TLS negotiation with the server and data will be encrypted in transit as a result of that, but by the time you get the data in a HttpResponse<?> it is no longer encrypted (unless of course the server is giving you encrypted content)
