### ISSUE TITLE
Only in kong unirest i can't submit form using post request

### ISSUE THREAD

**Issue by rzkrn20** [Kong/unirest-java#442]
I'm trying to submit a form using post request, i try this on postman, using unirest mashape & okhttp, and it works. But, not in kong unirest, the response i got is the html of the web itself. When i use postman/mashape/okhttp, I got the same response when i delete the submit field.

Is there something wrong with my code?

```
HttpResponse<String> response = Unirest.post(url)
  .field("number", "1")
  .field("type", "DATA")
  .field("comment", "Test")
  .field("submit", "Submit")
  .field("file", new File("/C:/Users/User/Documents/Test.pdf"))
  .asString();
```

**Expected behavior**
Get a success response

**Comment by rzkrn20** [comment]
I'm sorry, i can't write the url for some reasons. it's my fault i didn't write it clear, but it's actually a valid url

**Comment by ryber** [comment]
Without knowing the exact requirements of the "API" you are accessing it's impossible to know what aspect of this is different. It's not the goal of Unirest to behave exactly like Postman (or x) as all things may be "helpful" in different ways. But in this case Unirest is going to produce a properly segmented multipart/form-data request. You would have to ask the API owner what the requirements are
