### ISSUE TITLE
Thread leaking issue not getting away after upgrading from 1.4.9 to 3.13.6

### ISSUE THREAD

**Issue by jlarroque** [Kong/unirest-java#443]
**Describe the bug**
I have updated my code to use Unirest 3.13.6 version, but I still see that threads created by Unirest don't go away correctly. Should I do any specific configuration action for this to work? My understanding was that this was solved in Unirest 2. But I still see a bunch of threads related to it.

**To Reproduce**
String queryWithHost = instanceURL + query;
GetRequest request = Unirest.get(queryWithHost);

**Expected behavior**
Threads created by Unirest should go away sometime after that they were created.

**Screenshots**
![image](https://user-images.githubusercontent.com/291711/173124854-79226bd2-3f9b-4199-9c4c-e89f2178f9b0.png)
![image](https://user-images.githubusercontent.com/291711/173125611-3aaae5af-f4c3-4bf0-8f68-c7fd999d6d46.png)
![image](https://user-images.githubusercontent.com/291711/173125886-6b9bd434-0097-4479-8a0c-ac4a81f40ba2.png)

**Environmental Data:**
 - Java 11
 - Unirest version 3.13.6

**Additional context**

**Comment by ryber** [comment]
That class doesn't even exist in 3.13.6, not sure where you are getting it or where it would be started, but it's not Unirest 3.13.6

**Comment by ryber** [comment]
BTW, there are namespace changes from 1 to 3, so I'm guessing you are actually still using 1, which absolutely has thread leaks

**Comment by bcmyguest1** [comment]
Check the dependencies you are using in the project. If you are using maven, the command is
```
mvn dependency:tree
```

**Comment by jlarroque** [comment]
Thank you for your quick answers. After checking the code, I found out that there was another dependency that was using Unirest 1.4.9 under the hood.
