### ISSUE TITLE
Can unirest-mock capture request body

### ISSUE THREAD

**Issue by yhjhoo** [Kong/unirest-java#444]
Can unirest-mock capture request body?

**Comment by ryber** [comment]
unrest-mock primarily has a expectation on a body, so it doesn't capture it so much as takes a look and sees if it matches it's expectation. The problem with capturing it entirely is that the formatting of the body is something that is going to be done at a lower level that where the mock sits. Apache Http Client (or Java in the case of Unirest-4) will do a lot of the formatting, especially for multi-part bodies

**Comment by ryber** [comment]
this is complete in 3.14.0 / 4.0.0-RC6
