### ISSUE TITLE
Querystrings for POST?

### ISSUE THREAD

**Issue by CatarinaPBressan** [Kong/unirest-java#45]
I can create query strings via that  `.fields(Map<String, Object>)` method for GET requests, but I can't find anything for POST requests. I checked the source for HttpRequestsWithBody but I'm thinking I missed it.

This is useful for passing stuff like API keys or tokens.

**Comment by MHTaleb** [comment]
please would you provide a small explanation for use case of field and query string
you can answer for this question on stackoverflow please 
https://stackoverflow.com/questions/45739049/in-unirest-java-what-is-the-difference-between-querystring-and-field?rq=1
