### ISSUE TITLE
Jackson parser exceptions are not exposed through getParsingError()

### ISSUE THREAD

**Issue by tokarenko** [Kong/unirest-java#451]
**Describe the bug**
getParsingError() is null when Jackson parser fails at least for the following errors:
- com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `int` from String "2022-09-13T10:06:35.847+0300": not a valid `int` value
- com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59) Cannot deserialize value of type `java.util.ArrayList<Object>` from Object value (token `JsonToken.START_OBJECT`)

**To Reproduce**
In the below code failureMessage does not contain parsing error even if Jackson parser fails.
```
Unirest.config().setObjectMapper(new JacksonObjectMapper());

Book book = Unirest.get("https://...")
                      .asObject(Book.class)
                      .ifFailure(String.class, r -> 
                              {
                                failureMessage = "HTTP request failed."
                                + System.lineSeparator() + "Status code: " + r.getStatus()
                                + System.lineSeparator() + "Body: " + r.getBody().substring(0,50);
                                r.getParsingError().ifPresent(e -> {
                                  failureMessage += System.lineSeparator() + "Parsing error: " + e.getMessage();
                                });
                              }
                            )
                       .getBody();
```
I was able to retreive errors only via direct call to com.fasterxml.jackson.databind.ObjectMapper:

`Book book = mapper.readValue(Unirest.get("https://...").asString().getBody(), Book.class);` 

**Expected behavior**
getParsingError() returns UnirestParsingException when Jackson parser fails

**Screenshots**
N/A

**Environmental Data:**
 - Java Version 17
 - Version 3.13.11

**Additional context**

**Comment by ryber** [comment]
Ah, this is because you have performed another mapping operation with ```.ifFailure(String.class, r -> {})```, so the parsing to ```String``` worked fine, I totally get why you want the original error though. Let me think about that

If you had just used ```ifFailure(r -> {})``` without the extra mapping, then you would see the error and the original body is also on the parsingException

**Comment by ryber** [comment]
this is complete in 3.14.0 / 4.0.0-RC6.
Note that if the 2nd mapping operation fails due to a parsing error you will get THAT error and not the previous one.
