### ISSUE TITLE
kong.unirest.HttpRequest.asEmpty() returns raw type

### ISSUE THREAD

**Issue by Adrodoc** [Kong/unirest-java#461]
**Describe the bug**
The return type of method `kong.unirest.HttpRequest.asEmpty()` is `HttpResponse`, but it should be `HttpResponse<Empty>`, just like the return type of `kong.unirest.HttpRequest.asEmptyAsync()` is `CompletableFuture<HttpResponse<Empty>>` and the return type of `kong.unirest.HttpRequest.asString()` is `HttpResponse<String>`.

**To Reproduce**
The following code does not compile:
```java
String path = "...";
Object dto = new Object();
Unirest.post(path) //
    .body(dto) //
    .asEmpty() //
    .ifFailure(response -> {
      throw new RuntimeException(response.getStatusText());
    });
```
You get the compiler warning `Type safety: The method ifFailure(Consumer) belongs to the raw type HttpResponse. References to generic type HttpResponse<T> should be parameterized` and the error `The method getStatusText() is undefined for the type Object`.
The code can be rewritten to
```java
String path = "...";
Object dto = new Object();
HttpResponse<?> asEmpty = Unirest.post(path) //
    .body(dto) //
    .asEmpty();
asEmpty //
    .ifFailure(response -> {
      throw new RuntimeException(response.getStatusText());
    });
```
to make it work, but this prevents method chaining.
If you replace `asEmpty()` with `asString()` it also compiles as expected. It's odd that `asEmpty()` seems to be the only Method in `HttpRequest` that returns a raw type.

**Expected behavior**
The return type of method `kong.unirest.HttpRequest.asEmpty()` is `HttpResponse`, but it should be `HttpResponse<Empty>`.
If a response type of `HttpResponse<Empty>` does not work for some reason (like backwards compatibility) the return type should be at least `HttpResponse<?>` to allow method chaining.

**Environmental Data:**
 - JDK 1.8.0_301
 - com.konghq:unirest-java:3.13.13

**Comment by ryber** [comment]
this is complete in 3.14.0 / 4.0.0-RC6
