### ISSUE TITLE
Allow file download to be interrupted

### ISSUE THREAD

**Issue by gtaylor1981** [Kong/unirest-java#472]
I'm trying to download a large file (~2GB) using `get(...).asFile(path)` which runs on a separate thread and can take over 5 minutes to complete.

When my program exits, I try to interrupt the download thread then perform a join, but the download continues, my program does not exit and the join eventually times out.

The reason for this seems to be in [FileResponse](https://github.com/Kong/unirest-java/blob/975ea46b61fd8fc291dc7dc3998935d86da9c05b/unirest/src/main/java/kong/unirest/FileResponse.java#L44), where `Files.copy(...)` is used to transfer the contents of the stream to the file.
This runs in an uninterruptible loop.

One suggested option I saw is to use `.asFile(path, ExtendedCopyOption.INTERRUPTIBLE)` but this appears unsupported by `Files.copy()` (see [source](https://github.com/openjdk/jdk/blob/84d010a24bd59b80fa9e9158d41eab696a7292a9/src/java.base/share/classes/java/nio/file/Files.java#L3119)) and throws an exception.

Another option I tried was to use `.asFileAsync()` and then cancel the returned `Future`. However, this has a separate issue where the whole file is first downloaded to memory (see https://github.com/Kong/unirest-java/issues/130) which I must avoid.

Do you have any suggestion how to interrupt the copy cleanly?
Otherwise, is it something for which support could be added?

**Comment by ryber** [comment]
you can use ```void thenConsume(Consumer<RawResponse> consumer)``` to direct access to the raw InputStream

**Comment by gtaylor1981** [comment]
Thanks, I see what you mean... then I must re-implement the functionality of `FileResponse` myself.
That's no trouble, however I am also using a `DownloadMonitor` and cannot then create a `MonitoringInputStream` as it is package-private.

**Comment by gtaylor1981** [comment]
Wow, thanks for the speedy response.
As I mentioned, the files I'm downloading are large and can take 5-10 minutes to download. This is happening on a worker thread.
When the program closes, the worker thread is interrupted and joined. The join will time out because `Files.copy()` never stops copying.
Of course, eventually the connection closes and the download stops, so it's not so bad.
However losing a connection during a download will then appear in the logs as an exception.
I was hoping to exit more 'cleanly' using the interrupt.

I'm actually looking at another problem now, that if an exception is thrown in the `.thenConsume(...)` method, it will get caught in the [`BaseApacheClient.transformBody()`](https://github.com/Kong/unirest-java/blob/975ea46b61fd8fc291dc7dc3998935d86da9c05b/unirest/src/main/java/kong/unirest/apache/BaseApacheClient.java#L62) class. The exception handler calls [`recoverBody()`](https://github.com/Kong/unirest-java/blob/975ea46b61fd8fc291dc7dc3998935d86da9c05b/unirest/src/main/java/kong/unirest/apache/BaseApacheClient.java#L67) to return the body as a string.
However this then appears to then block while it tries to read the whole ~2GB file into a string (which is then used in [`setParsingException()`](https://github.com/Kong/unirest-java/blob/975ea46b61fd8fc291dc7dc3998935d86da9c05b/unirest/src/main/java/kong/unirest/BasicResponse.java#L48)).
Can this be avoided too somehow?

**Comment by ryber** [comment]
Oh jeesh, thats just a bug, I'll take a look

**Comment by ryber** [comment]
In [3.14.4](https://github.com/Kong/unirest-java/releases/tag/v3.14.4) I added two things to try and prevent the recovery part from getting the body:

1. If the Content-Type of the response is a known binary type (octet-stream, images, pdfs) it skips reading the body
2. If a UnrecoverableException is thrown it also skips it. This is what is thrown from the FileResponse class when it encounters an error. You could also throw this from the ```thenConsume``` method.

**Comment by gtaylor1981** [comment]
Fantastic, thanks a lot. I'll give it a try.

**Comment by gtaylor1981** [comment]
It works! However, I'm downloading from an AWS S3 Bucket and apparently that sets the `Content-Type` to `binary/octet-stream`. This is not in the official [list of MIME types](https://www.iana.org/assignments/media-types/media-types.xhtml).

Unfortunately it therefore also not in the list of pre-defined types in [ContentType](https://github.com/Kong/unirest-java/blob/9cb1004721178641396101bef6793a2ae8d6ab99/unirest/src/main/java/kong/unirest/ContentType.java).

I was able to define it myself (once-off, in a static block) as `ContentType.create("binary/octet-type", true)`.
Maybe this info might help others in the same situation.

**Comment by ryber** [comment]
I'm of the opinion that if AWS is using it its official enough for me :), we can add it, actually I'll add a little logic that if the MIME type contains "binary" then its binary

**Comment by gtaylor1981** [comment]
Sure! Not certain it helps, but another hint that it's a binary file (in this case) is the presence of the `Content-Disposition: attachment` header, indicating that it's a file to be downloaded (rather than to be parsed/printed etc)

**Comment by couchoud-t** [comment]
Just a random comment, but I think that while making the class public the non null checks are off. Only content is verified and the rest seems like leftovers of copy/paste.
https://github.com/Kong/unirest-java/blob/cc1189427f0c0d4f7a287de20c8c4f35b0374e86/unirest/src/main/java/kong/unirest/core/MonitoringInputStream.java#L46-L49

**Comment by ryber** [comment]
derp

**Comment by ryber** [comment]
fixed the requireNotNull stuff in the last release
