### ISSUE TITLE
unirest-java-bom references wrong artifact unirest-object-mappers-jackson

### ISSUE THREAD

**Issue by timomeinen** [Kong/unirest-java#478]
**Describe the bug**
The new BOM uses the artifactId unirest-object-mappers-jackson [here](https://github.com/Kong/unirest-java/blob/64950c06e032c2121c4c452ce61ef58d02f82720/unirest-java-bom/pom.xml#L27). This artifact is not available in Maven Central. It seems, that the correct artifactId should be `unirest-objectmapper-jackson` as defined [here](https://github.com/Kong/unirest-java/blob/64950c06e032c2121c4c452ce61ef58d02f82720/object-mapper-jackson/pom.xml#L11).

**To Reproduce**

    <dependencyManagement>
        <dependency>
                <groupId>com.konghq</groupId>
                <artifactId>unirest-java-bom</artifactId>
                <version>${unirest.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>com.konghq</groupId>
            <artifactId>unirest-java-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.konghq</groupId>
            <artifactId>unirest-object-mappers-jackson</artifactId>
        </dependency>
    <dependencies>

Will produce the error:

    [WARNING] The POM for com.konghq:unirest-object-mappers-jackson:jar:4.0.1 is missing, no dependency information available

**Environmental Data:**
 - Version 4.0.1

**Comment by ryber** [comment]
this should be fixed now in

**Comment by timomeinen** [comment]
Works now. Thank you.
