### ISSUE TITLE
Mocking Unirest in Junit5

### ISSUE THREAD

**Issue by vamsi-6579** [Kong/unirest-java#482]
A clear and concise description of what the problem is,
 I'm always frustrated when I'm trying to mock the Unirest call in Junit5 
Provide features to mock the Unirest by updating the dependency or by adding a new dependency

**Comment by ryber** [comment]
Check out the tests for more examples: https://github.com/Kong/unirest-java/blob/main/unirest-mocks/src/test/java/kong/tests

**Comment by vamsi-6579** [comment]
we are using mashape import which is old,
But after changing to this import 
		<dependency>
			<groupId>com.konghq</groupId>
			<artifactId>unirest-java-core</artifactId>
			<version>4.0.3</version>
			<scope>provided</scope>
		</dependency>

Iam unable to import MockClient

**Comment by ryber** [comment]
you need to pull in the mocking module, its its own dependency
