### ISSUE TITLE
Small issue on Upgrade.md that prevents dependency installation

### ISSUE THREAD

**Issue by miguelingka** [Kong/unirest-java#488]
**Describe the bug**
The upgrade guide should be correctly updated about the unirest java dependency. Currently points to a non existing version.

https://github.com/Kong/unirest-java/blob/main/UPGRADE_GUIDE.md?plain=1#L42

This line should be updated to have java-core instead of just java.

**To Reproduce**
1. Follow the documentation regarding the version 4 installation
1. Get an error when trying to update maven dependencies

**Expected behavior**
Dependency is correctly instaled.

**Screenshots**
<img width="1319" alt="image" src="https://github.com/Kong/unirest-java/assets/100838584/83b7bbb6-ecd2-420e-b81f-e32031c23472">

<img width="351" alt="image" src="https://github.com/Kong/unirest-java/assets/100838584/6e50f1f9-213e-492d-91d4-69f74dc40b37">

**Environmental Data:**
 - 11
 - Version 4.*

**Comment by ryber** [comment]
thanks! Fixed
