### ISSUE TITLE
4.0.4 isn't on the maven repository.

### ISSUE THREAD

**Issue by hunterino** [Kong/unirest-java#489]
**Describe the bug**

if you go to release history
[Github shows 4.0.4 as latest release](https://github.com/Kong/unirest-java/releases)

Current release shows 4.0.4.  The link to mvnrepository.com
[mvnrepository shows 4.0.0-RC2](https://mvnrepository.com/artifact/com.konghq/unirest-java)

It shows version 4.0.0-RC2 is the latest.

**Expected behavior**
Expected to see 4.0.4 on mvnrepository

**Comment by ryber** [comment]
Its in different coordinates now. You are looking in the wrong one https://mvnrepository.com/artifact/com.konghq/unirest-java-core
