### ISSUE TITLE
Incorrect link to Interceptor file

### ISSUE THREAD

**Issue by sergey-morenets** [Kong/unirest-java#509]
Hi

Main documentation page (http://kong.github.io/unirest-java/#configuration) contains incorrect link to the Interceptor file:
https://github.com/Kong/unirest-java/blob/master/unirest/src/main/java/kong/unirest/Interceptor.java

It seems that correct link is:
https://github.com/Kong/unirest-java/blob/main/unirest/src/main/java/kong/unirest/core/Interceptor.java

**Comment by ryber** [comment]
fixed
