### ISSUE TITLE
How to set read timeout duration

### ISSUE THREAD

**Issue by RTException** [Kong/unirest-java#518]
Hi,
In version 3.13.6, I could use `Config#socketTimeout(int inMillies)` to set the read timeout for responses. However, in the latest version, this method has been removed. What other ways can I use to set the timeout for both sending and receiving data, in order to control the maximum waiting time for synchronous calls?

**Comment by RTException** [comment]
On the [Unirest-Java Documentation page](https://kong.github.io/unirest-java/#requests), the following code can still be found:

![code-socket-timeout](https://github.com/Kong/unirest-java/assets/146321368/54ef4949-970e-4bc2-93df-fe4bafe81778)

**Comment by ryber** [comment]
The setting does not exist in 4 because the Java client does not support it. I have just removed it from the documentation,

**Comment by ryber** [comment]
FYI there is a discussion about adding this to java: https://bugs.openjdk.org/browse/JDK-8258397

**Comment by RTException** [comment]
Thank you.
You are right. I have checked the JDK source code and found that `java.net.http.HttpClient` no longer supports the `socketTimeout` method. I hope it will be supported in the subsequent versions of JDK because this setting is still very useful in some cases.
