### ISSUE TITLE
Can we add a response failure retry function?

### ISSUE THREAD

**Issue by formatsystem** [Kong/unirest-java#520]
I want to use an interceptor to resubmit the response after it fails. However, it seems that there is no relevant function or is there any good way to implement it?
```[tasklist]
### Tasks
```

**Comment by ryber** [comment]
Unirest has a retry mechanism available in the config. It is designed for use with APIs that support the retry-after header but it can be customized. See the ```Unirest::config::retryAfter``` methods in particular the one that allows you to set a [RetryStrategy](https://github.com/Kong/unirest-java/blob/main/unirest/src/main/java/kong/unirest/core/RetryStrategy.java)
