### ISSUE TITLE
Requests are cancelled unexpectedly - connectTimeout limits request duration

### ISSUE THREAD

**Issue by grillbaer** [Kong/unirest-java#526]
**Describe the bug**
Longer-running requests are cancelled unexpectedly after 10 seconds, or `Config.connectTimeout()` if set, or `HttpRequest.connectTimeout()` if set. The request then fails (and still returns status 200). I would not expect a connect timeout to limit the request duration and having a 10 second default for this. This also contradicts the quite clear javadoc of  `Config.connectTimeout()`. 

**To Reproduce**
Try to download a larger file which takes longer than 10 seconds and see the download failing with an incomplete file and status 200:
```java
import kong.unirest.core.Unirest;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;

public class UnirestConnectionTimeout {
    public static void main(String[] args) throws IOException {
        var largeFileUrl = "https://github.com/szalony9szymek/large/releases/download/free/large";
        var targetFile = Path.of("large-testfile");
        Files.delete(targetFile);

        System.out.println("START " + Instant.now());

        // Unirest.config().connectTimeout(5_000); // override default connect/request timeout of 10s
        Unirest.get(largeFileUrl)
                // .connectTimeout(20_000)  // override the config's connect/request timeout
                .asFile(targetFile.toString())
                .ifSuccess(resp -> System.err.println("SUCCESS status " + resp.getStatus()))
                .ifFailure(resp -> System.err.println("FAILURE status " + resp.getStatus()));

        System.out.println("STOP " + Instant.now() + ", file size " + Files.size(targetFile));
    }
}
```

**Expected behavior**
The connect timeout should not limit the request duration. A request timeout should be handled separately and be unlimited by default.

**Screenshots**
n/a

**Environmental Data:**
 - Java Version 17.0.7
 - Version 4.3.2

**Additional context**
I think the cause is that `kong.unirest.core.HttpRequest.getConnectionTimeout()` is used for `java.net.http.HttpRequest.Builder.timeout(Duration)` in `kong.unirest.core.java.JavaClient.getRequest(HttpRequest<?>)` which acts as a _request_ timeout. Maybe the intention was to replace the formerly existing socket timeout, but this is HttpClient's request timeout.

BTW, thank you for the great Unirest library!

**Comment by ryber** [comment]
hrm, I think you are right, the timeout on the client and the timeout on the request are different. I'm up for splitting the two but its a breaking change and so will need to be eased into

**Comment by ryber** [comment]
this is complete in complete in 4.4.0. This splits connection timeout from request timeout. The request no longer has a connection timeout setting, and instead has a request timeout setting as a replacement. Previously these two settings had been conflated. The overall config also has a default request timeout that will be applied to all requests if the request setting is not set. The default setting is null which indicates a infinite timeout.

**Comment by grillbaer** [comment]
@ryber Thank you very much for fixing this so quickly!

For your information on how the story went on on our side, just in case somebody else runs into the same problems and blames Unirest 4:

Large downloads may still cause problems even without a request timeout. This is due a bug in the JRE itself in java.net.http.HttpClient leading to excessive heap memory consumption for large TLS/SSL downloads: [Uncontrolled memory consumption in SSLFlowDelegate.Reader](https://bugs.openjdk.org/browse/JDK-8308144). I our case it consumed hundreds of MB heap for a 2 GB download.

This bug is still present in all JREs from 11 to 21 as of today. We just asked for a backport of the fix into older JRE LTS versions.

**Comment by bgooren** [comment]
@ryber  Was there a particular reason for not setting a sensible default request timeout? Not setting any timeout seems like a bad choice to me.

We have had cases (unrelated to unirest, other libraries misbehaving) where remotes hang and don't respond, and a lack of timeouts lead to depleted connection pools etc. For this reason I ensure we always have timeouts set.
If I would have upgraded from 4.3.0 to 4.4.5 without checking the changelog, I would not have caught this significant change.

Before this change there was a request timeout of 10 seconds, and now there is no longer any timeout.
Probably better to set a default request timeout of 10 seconds, so the behavior of unirest does not change across minor versions?

**Comment by ryber** [comment]
I went with the same defaults as the Java Client itself, which has generally always been what we have deferred to in most cases (when Unrest wrapped Apache we also deferred to its settings).

**Comment by bgooren** [comment]
> I went with the same defaults as the Java Client itself, which has generally always been what we have deferred to in most cases (when Unrest wrapped Apache we also deferred to its settings).

Ok; Thanks for your quick reply.
Looking at https://docs.oracle.com/en/java/javase/17/docs/api/java.net.http/java/net/http/HttpRequest.Builder.html#timeout(java.time.Duration) I see that the default timeout (on java 17 at least) is no timeout (infinite).

Perhaps a good idea to at least mention in the docs that from version 4.3.2 => 4.4.0 the request timeout goes to infinite unless configured by the user.

In any case people should be able to find this ticket when they google for "unirest timeout".

**Comment by ryber** [comment]
When Unirest wrapped Apache there was no request timeout, this is a new setting. The fact that connection timeout was being used to populate a request timeout was a bug (and an egregious one as the setting was quite low for anyone with long running requests). I'll make sure the docs say what it is, but the changelog already documented the change.
