### ISSUE TITLE
UnirestInstance should implement AutoCloseable

### ISSUE THREAD

**Issue by ee-usgs** [Kong/unirest-java#536]
**Is your feature request related to a problem? Please describe.**
When creating individual instances, the AutoCloseable interface is the standard way to auto-close via a try-with-resource block.  This is clearly the intention, since the `close` method of UnirestInstance [mentions that usage in the javadoc](https://github.com/Kong/unirest-java/blob/197f2feecfd6cfdeb386e407e5aaef3f77e8ade0/unirest/src/main/java/kong/unirest/core/UnirestInstance.java#L151).  However, even though it has the `close` method, it doesn't implement the AutoCloseable interface, so it cannot be used that way currently.

**Describe the solution you'd like**
UnirestInstance should `implements AutoCloseable` so that it can be used in a try-with-resource block.

**Describe alternatives you've considered**
There are no other alternatives to make this work in a try-with-resource block. 

**Additional context**
Also to note:  The [multi-configuration section of the docs](http://kong.github.io/unirest-java/#configuration) very sternly warns that **_YOU are responsible for shutting it down when the JVM shuts down_**, however, it doesn't actually say how to do that.  Apparently `close()` is the way to do that, but as a user, it would be nice to know that for sure.  And of course, try-with-resource would be the preferred example to be able to put there after this issue is addressed.

**Comment by ryber** [comment]
I've added AutoCloseable to the UnirestInstance class, however I would just note that as of Unirest 4 this doesn't really do anything. It was more important with previous versions which used Apache HttpClient under the hood because there were monitoring threads to shut down. Now all it does is reset the config.

I've removed the warning from the documentation

**Comment by ryber** [comment]
released in 4.4.5, might take a hour to make it though maven centrals twisty tunnels

**Comment by ee-usgs** [comment]
Great - Thank you
