### ISSUE TITLE
Problem working with Content Coding in response

### ISSUE THREAD

**Issue by ladraum** [Kong/unirest-java#56]
I'm trying to use your UniRest for Java, but I'm struggling with one (I think) simple problem.
When trying to build a request with a response that has a content coding "ISO-8859-1" response, I got and UnirestException (Caused by: com.mashape.unirest.http.exceptions.UnirestException: org.apache.http.client.ClientProtocolException ==> Caused by: org.apache.http.HttpException: Unsupported Content-Coding: ISO-8859-1).
I've tried adding Content-Encoding and Accept-Encoding as headers in the request, with no luck.
Can you point me out in the right direction on how to solve this ?

Great library, btw :)

**Comment by thefosk** [comment]
Is there any way I can replicate this issue? Could you send me an URL I can use for tests?
