### ISSUE TITLE
Per request proxy config

### ISSUE THREAD

**Issue by reggiepierce** [Kong/unirest-java#72]
Hey All,

First of all this project is great. However, I have a special requirement where I need to connect to multiple proxies, and not just one system wide. Therefore Unirest as is wouldn't work for me.

I took it upon myself to tweak the code to support org.apache.http.client.config.RequestConfig on all requests. I also added the ability to use a custom credential provider. The code can now be used as follows:

``` java
        String url = "http://ipinfo.io";
        String proxyHost = "";
        int proxyPort = 8888;
        String proxyUser = "";
        String proxyPwd = "";
        BasicCredentialsProvider credsProvider = new BasicCredentialsProvider();
        credsProvider.setCredentials(new AuthScope(proxyHost, proxyPort),
                new NTCredentials(proxyUser, proxyPwd, proxyHost, ""));
        Unirest.setCredentialsProvider(credsProvider);
        HttpHost proxy = new HttpHost(proxyHost, proxyPort,
                Proxy.Type.HTTP.name());
        RequestConfig config = RequestConfig.custom().setProxy(proxy).build();
        String body = Unirest
                .get(url, config)
                .header(HttpHeaders.USER_AGENT,
                        "curl/7.9.8 (i686-pc-linux-gnu) libcurl 7.9.8 (OpenSSL 0.9.6b) (ipv6 enabled)")
                .header(HttpHeaders.ACCEPT, "application/json").asString()
                .getBody().toString();
        System.out.println(body);
```

However, this is my first time submitting to an open source project, and our company primarily uses bitbucket.org. If you have any interest in seeing the full code, respond and I can invite you to the repository. Or, if you can think of a better way of sharing, let me know.

One final thing, the following in your code is problematic:

``` java
        if (!request.getHeaders().containsKey(USER_AGENT_HEADER)) {
            request.header(USER_AGENT_HEADER, USER_AGENT);
        }
```

org.apache.http.HttpHeaders defines the user agent header as: "User-Agent". If one sets the header "User-Agent", Unirest will also add a "user-agent" header of "unirest-java/1.3.11". Therefore I modified the code to use the following:

``` java
        if (!containsHeaderIgnoreCase(request, USER_AGENT_HEADER)) {
            request.header(USER_AGENT_HEADER, USER_AGENT);
        }
        if (!containsHeaderIgnoreCase(request, ACCEPT_ENCODING_HEADER)) {
            request.header(ACCEPT_ENCODING_HEADER, "gzip");
        }
```

and added:

``` java
    private static boolean containsHeaderIgnoreCase(HttpRequest request,
            String userAgentHeader) {
        if (userAgentHeader != null && request != null
                && request.getHeaders() != null) {
            for (String key : request.getHeaders().keySet()) {
                if (userAgentHeader.equalsIgnoreCase(key)) {
                    return true;
                }
            }
        }
        return false;
    }
```

**Comment by goldjee** [comment]
Great idea! Has per-request-proxy been implemented natively?

**Comment by HaIDsIEx** [comment]
Hi,
> If you have any interest in seeing the full code, respond and I can invite you to the repository. 

I would really like to see your code because I'm exactly in the same issue. How should we get connected?

**Comment by reggiepierce** [comment]
We ended up abandoning unirest for OkHttp. With OkHttp it's easy to have a shared connection pool and create one client per proxy. Plus, it works well with Retrofit.

Not sure if a similar approach is possible with Unirest, but I'd go that route.

**Comment by reggiepierce** [comment]
Hey, for giggles, I uploaded the code to github. It's probably using an outdated version of unirest, but you can see it here:

https://github.com/reggiepierce/unirest-java-proxy

**Comment by ryber** [comment]
We now have multiple configs which means you can have different instances of unirest with different proxies. Unfortunately the underlying http client doesn't have a shim for doing proxies on a per request.

**Comment by ryber** [comment]
Re-opening. We can do this, but only with basic proxies, not officially credentialed ones unless you want to put the credentials in the URL (yuck)

**Comment by ryber** [comment]
released in 2.0.05

**Comment by shreyanshp** [comment]
>Re-opening. We can do this, but only with basic proxies, not officially credentialed ones unless you want to put the credentials in the URL (yuck)

Even though it is yuck, could you please help me with how to do that, I have been searching for days on this

**Comment by ryber** [comment]
> Even though it is yuck, could you please help me with how to do that

What? Put the credentials in the url?

I can’t guarantee it will work with your proxy but historically it’s

‘’’
https://username:password@example.com
‘’’
