### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by bmoers** [Kong/unirest-java#80]
Any chance to support auto pagination by following the "link" header?
Like: https://developer.github.com/v3/#link-header

**Comment by amirlanesman** [comment]
+1

**Comment by ryber** [comment]
synchronized

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.
