### ISSUE TITLE
Post should sort the fields as part of the request

### ISSUE THREAD

**Issue by jghoman** [Kong/unirest-java#84]
Fields added as the body should be provided in [key-sorted order](http://stackoverflow.com/questions/14085487/order-of-http-post-parameters-changed/14558030#14558030), but currently are enumerated in [added-order](https://github.com/Mashape/unirest-java/blob/master/src/main/java/com/mashape/unirest/request/body/MultipartBody.java#L51).  This can cause problems with mocking frameworks and servers expecting exact ordering.  Maintaining the sorted order or sorting on a call to getEntity seems more correct but may be a breaking change for previous code.

**Comment by ahmadnassri** [comment]
servers expecting "exact ordering" are likely not following the HTTP standard ... and probably not good to use them as an authority on this.

**Comment by ryber** [comment]
The only remaining document on this from the SO question says that the tree order is 

> "the term tree order means a pre-order, depth-first traversal of DOM nodes involved (through the parentNode/childNodes relationship)."

There is no DOM in the case of Unirest. It is not a browser. I also don't see why it would matter or what this would solve?

Unless there is some specific reason or spec to attempt to do this I'm going to close the issue
