### ISSUE TITLE
Force Multipart instead of x-www-form-urlencoded

### ISSUE THREAD

**Issue by aemreunal** [Kong/unirest-java#88]
I want to submit a JSON text as part of a Multipart request but if I don't provide a File object (for example, if I only send one [or more] JSON string), Unirest sends the request as `application/x-www-form-urlencoded`. Is there any way to force Unirest to submit this request as Multipart? Thanks in advance.

**Comment by aemreunal** [comment]
Created pull request #89.

**Comment by ryber** [comment]
The solution to this is the same as for #165 so I'm going to merge it with that one as there is more comments on it,
