### ISSUE TITLE
Camfind Image Response api timing issue

### ISSUE THREAD

**Issue by krishna18787** [Kong/unirest-java#94]
Hello Dear,

I have issue with the timing in making image request and image response api,Its taking min 30 sec to get the name of image. I want api response in max 20 seconds,but I failed to get this.I am developing in Android . please suggest me.
I hit service with the compressed image at jpeg level 5 and 640*480 sized.but still it gives "not complete" status for 6 to 7 times and then it carry image name .i really got frustrated.please help me with any specific code of line or give me any reference of library.or suggest me any another right way how to hit service by which we can get image name with minimum time.

**Comment by ryber** [comment]
I don't think this was a Unirest issue.
