### ISSUE TITLE
Override .body() on HttpRequestWithBody with  org.json.JSONObject.

### ISSUE THREAD

**Issue by mchiareli** [Kong/unirest-java#95]
Please overload the method .body() to receive a raw org.json.JSONObject.

**Comment by ipbeegle** [comment]
You can always call JsonNode.getObject() to retriever the underlying JSONObject.

**Comment by mchiareli** [comment]
I am talking about the parameter and not response, the body input expect a string and another formats, but not a raw JSONObject, so I have to call toString() and on this method it creates the JSONObject again, no sense at all.

**Comment by mchiareli** [comment]
I have changed the file to include the overloaded methods and created a pull request, can you take a look please?

https://github.com/Mashape/unirest-java/pull/116

**Comment by mchiareli** [comment]
Hey guys, can you check to merge this, is just a overload method that saves few lines of final code on client side.
thanks

**Comment by ryber** [comment]
looks like it was merged closing
