### ISSUE TITLE
Invalid Headers when using Unirest

### ISSUE THREAD

**Issue by artguy10** [Kong/unirest-java#97]
```
Unirest.post("https://dweet.io/dweet").fields(map).asJson(); // map is a HashMap of course
```

I am making a standard `POST` request to a server and I get the following while receiving a response.

```
Jun 06, 2015 4:36:18 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: dweet:thing=hallowed-mailbox; path=/; expires=Sun,
05 Jun 2016 20:36:16 GMT; httponly". Invalid 'expires' attribute: Sun, 05 Jun 2016 20:36:16 GMT
```

Can someone please help me fix this frustrating error? I love Unirest, it's like `requests` but in Java too!

**Comment by jthomas** [comment]
I encountered the same problem and found a solution:
<pre>
RequestConfig globalConfig = RequestConfig.custom()
.setCookieSpec(CookieSpecs.IGNORE_COOKIES).build();
		
HttpClient httpclient = HttpClients.custom().setDefaultRequestConfig(globalConfig).build();
Unirest.setHttpClient(httpclient);
</pre>

**Comment by maniankara** [comment]
Thanks for the response, Wondering is there a way to fix it than just IGNORING cookies/warnings?

**Comment by clickear** [comment]
CookieSpecs.IGNORE_COOKIES: just IGNORING cookies
CookieSpecs.STANDARD: will parse Invalid 'expires';The RFC 6265 compliant policy (interoprability profile).
see http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/client/config/CookieSpecs.html

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.

**Comment by Mailaender** [comment]
```java
Unirest.config().cookieSpec("standard");
```

solved it for me.
