### ISSUE TITLE
Feature Request: Being able to add headers before method chosen

### ISSUE THREAD

**Issue by jimmyhmiller** [Kong/unirest-java#99]
Here's my use case for this. I have two different services my application interacts with, each with its own set of auth credentials. I would love to be able to return an object that already contains those headers so my code can make requests all it wants without having worry about setting the appropriate headers. 

Currently the only way I can see to do something similar to that would be to set default headers. But that doesn't really help me here. That would set headers for all requests, I want two different sets of default headers. 

I'd happily take the time to implement something like this. Just wanted to see if this would be something you'd be receptive to or have any suggestions on how my goal can be accomplished without changes.

Thanks,
Jimmy

**Comment by ryber** [comment]
Hello, this should be resolved or addressed in Unirest 2. Please see the [upgrade guide](https://github.com/Kong/unirest-java/blob/master/UPGRADE_GUIDE.md) for important changes.

We now support multiple config instances which would work here
